-- ============================================================
-- ItemRack Revived — BIS.lua
-- Best-in-Slot comparison panel
-- Data is loaded from BIS_Data.lua (auto-generated by scripts/update-bis.ps1)
-- ============================================================

-- ----------------------------------------------------------------
-- Module state
-- ----------------------------------------------------------------
local IRR_BIS = {}
IRR_BIS.currentPhase   = 1       -- 1..5
IRR_BIS.currentSpecKey = nil     -- e.g. "fury_warrior"
IRR_BIS.frame          = nil     -- the panel container frame
IRR_BIS.rows           = {}      -- row frames keyed by slotId
IRR_BIS.phaseButtons   = {}      -- phase selector buttons

-- Slot list in display order with short abbreviations
local SLOT_LIST = {
    {id=1,  abbr="Head" }, {id=2,  abbr="Neck" }, {id=3,  abbr="Shldr"},
    {id=15, abbr="Back" }, {id=5,  abbr="Chest"}, {id=9,  abbr="Wrist"},
    {id=10, abbr="Hands"}, {id=6,  abbr="Waist"}, {id=7,  abbr="Legs" },
    {id=8,  abbr="Feet" }, {id=11, abbr="Ring1"}, {id=12, abbr="Ring2"},
    {id=13, abbr="Trn1" }, {id=14, abbr="Trn2" }, {id=16, abbr="MH"   },
    {id=17, abbr="OH"   }, {id=18, abbr="Rnge" },
}

-- ----------------------------------------------------------------
-- Spec detection
-- ----------------------------------------------------------------
local function IRR_BIS_DetectSpec()
    if not IRR_BIS_SPECS then return nil end
    local _, classToken = UnitClass("player")
    if not classToken then return nil end

    local numTabs = GetNumTalentTabs and GetNumTalentTabs() or 0
    local maxPoints, maxTab = 0, 1
    for i = 1, numTabs do
        local _, _, pts = GetTalentTabInfo(i)
        pts = tonumber(pts) or 0
        if pts > maxPoints then
            maxPoints = pts
            maxTab = i
        end
    end

    for key, spec in pairs(IRR_BIS_SPECS) do
        if spec.class == classToken and spec.specTab == maxTab then
            return key
        end
    end
    return nil
end

-- ----------------------------------------------------------------
-- Truncate a string to maxChars, appending ".." if needed
-- ----------------------------------------------------------------
local function Trunc(s, maxChars)
    if not s or s == "" then return "" end
    if #s <= maxChars then return s end
    return s:sub(1, maxChars - 2) .. ".."
end

-- ----------------------------------------------------------------
-- Resolve best available name for an item ID
-- Uses WoW's GetItemInfo (client cache) first, falls back to BIS_Data name
-- ----------------------------------------------------------------
local nameCache = {}
local function GetBISItemName(id, fallback)
    if nameCache[id] then return nameCache[id] end
    if GetItemInfo then
        local name = GetItemInfo(id)
        if name and name ~= "" then
            nameCache[id] = name
            return name
        end
    end
    return fallback or ("Item #" .. id)
end

-- ----------------------------------------------------------------
-- Build the BIS panel into `parent` frame
-- parent is already sized and positioned by UI.lua
-- ----------------------------------------------------------------
function IRR_BuildBISPanel(parent, availableH)
    IRR_BIS.frame = parent
    local W = parent:GetWidth()
    local yTop = 0  -- start from top of parent (using negative y offsets)

    -- ---- Phase selector strip ----
    local phaseLbl = parent:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    phaseLbl:SetFont(phaseLbl:GetFont(), 10, "")
    phaseLbl:SetText("Phase:")
    phaseLbl:SetTextColor(0.7, 0.7, 0.7)
    phaseLbl:SetPoint("TOPLEFT", parent, "TOPLEFT", 4, yTop - 4)

    local phBtnX = 46
    for ph = 1, 5 do
        local btn = CreateFrame("Button", nil, parent)
        btn:SetSize(28, 18)
        btn:SetPoint("TOPLEFT", parent, "TOPLEFT", phBtnX + (ph - 1) * 29, yTop - 2)

        local btnBg = btn:CreateTexture(nil, "BACKGROUND")
        btnBg:SetAllPoints(btn)
        btnBg:SetColorTexture(0.18, 0.18, 0.18, 1)
        btn.bg = btnBg

        local btnHl = btn:CreateTexture(nil, "HIGHLIGHT")
        btnHl:SetAllPoints(btn)
        btnHl:SetColorTexture(1, 1, 1, 0.1)

        local btnTxt = btn:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
        btnTxt:SetFont(btnTxt:GetFont(), 9, "OUTLINE")
        btnTxt:SetAllPoints(btn)
        btnTxt:SetJustifyH("CENTER")
        btnTxt:SetText("P" .. ph)
        btn.txt = btnTxt

        local function UpdatePhBtn()
            if IRR_BIS.currentPhase == ph then
                btn.txt:SetTextColor(0.2, 0.75, 1.0)
                btn.bg:SetColorTexture(0.10, 0.22, 0.35, 1)
            else
                btn.txt:SetTextColor(0.6, 0.6, 0.6)
                btn.bg:SetColorTexture(0.14, 0.14, 0.14, 1)
            end
        end
        btn:SetScript("OnClick", function()
            IRR_BIS.currentPhase = ph
            IRR_RefreshBISPanel()
        end)
        IRR_BIS.phaseButtons[ph] = btn
        IRR_BIS.phaseButtons[ph].UpdateColor = UpdatePhBtn
    end

    -- ---- Spec label ----
    local specLblKey = parent:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    specLblKey:SetFont(specLblKey:GetFont(), 10, "")
    specLblKey:SetText("Spec:")
    specLblKey:SetTextColor(0.7, 0.7, 0.7)
    specLblKey:SetPoint("TOPLEFT", parent, "TOPLEFT", 4, yTop - 24)
    IRR_BIS.specLbl = parent:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    IRR_BIS.specLbl:SetFont(IRR_BIS.specLbl:GetFont(), 10, "")
    IRR_BIS.specLbl:SetText("(detecting...)")
    IRR_BIS.specLbl:SetTextColor(1, 0.82, 0)
    IRR_BIS.specLbl:SetPoint("LEFT", specLblKey, "RIGHT", 4, 0)

    -- ---- Separator ----
    local sep = parent:CreateTexture(nil, "ARTWORK")
    sep:SetSize(W - 8, 1)
    sep:SetPoint("TOPLEFT", parent, "TOPLEFT", 4, yTop - 42)
    sep:SetColorTexture(0.35, 0.35, 0.35, 1)

    -- ---- Column headers ----
    local hSlot = parent:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    hSlot:SetFont(hSlot:GetFont(), 9, "")
    hSlot:SetText("Slot")
    hSlot:SetTextColor(0.6, 0.6, 0.6)
    hSlot:SetPoint("TOPLEFT", parent, "TOPLEFT", 4, yTop - 48)

    local hItem = parent:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    hItem:SetFont(hItem:GetFont(), 9, "")
    hItem:SetText("BIS Item")
    hItem:SetTextColor(0.6, 0.6, 0.6)
    hItem:SetPoint("TOPLEFT", parent, "TOPLEFT", 42, yTop - 48)

    local hStat = parent:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    hStat:SetFont(hStat:GetFont(), 9, "")
    hStat:SetText("St")
    hStat:SetTextColor(0.6, 0.6, 0.6)
    hStat:SetPoint("TOPLEFT", parent, "TOPLEFT", W - 28, yTop - 48)

    -- ---- Scroll frame for slot rows ----
    local scrollTop = yTop - 60
    local scrollH   = availableH - 62

    local scrollFrame = CreateFrame("ScrollFrame", nil, parent, "UIPanelScrollFrameTemplate")
    scrollFrame:SetSize(W - 18, scrollH)
    scrollFrame:SetPoint("TOPLEFT", parent, "TOPLEFT", 2, scrollTop)

    local scrollChild = CreateFrame("Frame")
    scrollChild:SetSize(W - 22, 1)   -- height will be set dynamically
    scrollFrame:SetScrollChild(scrollChild)
    IRR_BIS.scrollChild = scrollChild

    local ROW_H  = 20
    local ABBR_W = 38
    local NAME_W = W - 22 - ABBR_W - 22  -- leave room for scrollbar + status + padding

    -- Build one row per slot
    for idx, slot in ipairs(SLOT_LIST) do
        local rowY = -(idx - 1) * ROW_H
        local row  = CreateFrame("Frame", nil, scrollChild)
        row:SetSize(W - 22, ROW_H)
        row:SetPoint("TOPLEFT", scrollChild, "TOPLEFT", 0, rowY)

        -- Alternating row background
        if idx % 2 == 0 then
            local rowBg = row:CreateTexture(nil, "BACKGROUND")
            rowBg:SetAllPoints(row)
            rowBg:SetColorTexture(0.12, 0.12, 0.12, 0.6)
        end

        -- Slot abbreviation label
        local abbrTxt = row:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
        abbrTxt:SetFont(abbrTxt:GetFont(), 9, "")
        abbrTxt:SetText(slot.abbr)
        abbrTxt:SetTextColor(0.65, 0.65, 0.65)
        abbrTxt:SetJustifyH("LEFT")
        abbrTxt:SetPoint("LEFT", row, "LEFT", 2, 0)
        abbrTxt:SetWidth(ABBR_W)

        -- BIS item name label
        local nameTxt = row:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
        nameTxt:SetFont(nameTxt:GetFont(), 9, "")
        nameTxt:SetText("–")
        nameTxt:SetTextColor(0.9, 0.9, 0.9)
        nameTxt:SetJustifyH("LEFT")
        nameTxt:SetPoint("LEFT", row, "LEFT", ABBR_W + 2, 0)
        nameTxt:SetWidth(NAME_W)

        -- Status icon (✓ / ↑ / –)
        local statusTxt = row:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
        statusTxt:SetFont(statusTxt:GetFont(), 10, "OUTLINE")
        statusTxt:SetText("")
        statusTxt:SetJustifyH("CENTER")
        statusTxt:SetPoint("RIGHT", row, "RIGHT", -2, 0)
        statusTxt:SetWidth(18)

        row.nameTxt   = nameTxt
        row.statusTxt = statusTxt
        row.slot      = slot

        -- Tooltip on hover: show actual item tooltip via hyperlink
        row:SetScript("OnEnter", function(self)
            local specKey = IRR_BIS.currentSpecKey
            local phase   = IRR_BIS.currentPhase
            if not specKey or not IRR_BIS_DATA then return end
            local phaseData = IRR_BIS_DATA[specKey] and IRR_BIS_DATA[specKey][phase]
            if not phaseData then return end
            local slotData  = phaseData[self.slot.id]
            if not slotData or #slotData == 0 then return end

            GameTooltip:SetOwner(self, "ANCHOR_LEFT")
            GameTooltip:ClearLines()
            -- Show BIS header
            local specLabel = (IRR_BIS_SPECS and IRR_BIS_SPECS[specKey]) and IRR_BIS_SPECS[specKey].label or specKey
            GameTooltip:AddLine(self.slot.abbr .. " BIS — " .. specLabel .. " P" .. phase, 1, 0.82, 0)
            GameTooltip:AddLine(" ")
            for _, entry in ipairs(slotData) do
                local rankStr  = "#" .. tostring(entry.rank)
                local iname    = GetBISItemName(entry.id, entry.name)
                local equippedId = GetInventoryItemID("player", self.slot.id)
                local marker   = (equippedId and equippedId == entry.id) and " |cff00ff00[equipped]|r" or ""
                local scoreStr = entry.score and tonumber(entry.score) > 0 and string.format(" [%.0f pts]", entry.score) or ""
                GameTooltip:AddLine(rankStr .. " " .. iname .. scoreStr .. marker, 0.9, 0.9, 0.9)
            end
            GameTooltip:Show()
        end)
        row:SetScript("OnLeave", function() GameTooltip:Hide() end)

        IRR_BIS.rows[slot.id] = row
    end

    -- Set scroll child size
    scrollChild:SetHeight(#SLOT_LIST * ROW_H + 4)

    -- ---- Refresh button (re-detect spec) ----
    local redetectBtn = CreateFrame("Button", nil, parent)
    redetectBtn:SetSize(70, 18)
    redetectBtn:SetPoint("BOTTOMRIGHT", parent, "BOTTOMRIGHT", -4, 4)
    local rdBg = redetectBtn:CreateTexture(nil, "BACKGROUND")
    rdBg:SetAllPoints(redetectBtn)
    rdBg:SetColorTexture(0.18, 0.18, 0.18, 1)
    local rdHl = redetectBtn:CreateTexture(nil, "HIGHLIGHT")
    rdHl:SetAllPoints(redetectBtn)
    rdHl:SetColorTexture(1, 1, 1, 0.1)
    local rdTxt = redetectBtn:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    rdTxt:SetFont(rdTxt:GetFont(), 9, "OUTLINE")
    rdTxt:SetAllPoints(redetectBtn)
    rdTxt:SetJustifyH("CENTER")
    rdTxt:SetText("Re-detect")
    redetectBtn:SetScript("OnClick", function()
        IRR_BIS.currentSpecKey = IRR_BIS_DetectSpec()
        IRR_RefreshBISPanel()
    end)

    -- ---- No-data notice ----
    IRR_BIS.noDataTxt = parent:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    IRR_BIS.noDataTxt:SetFont(IRR_BIS.noDataTxt:GetFont(), 10, "")
    IRR_BIS.noDataTxt:SetText("No BIS data loaded.\nRun scripts/update-bis.ps1")
    IRR_BIS.noDataTxt:SetTextColor(0.8, 0.4, 0.4)
    IRR_BIS.noDataTxt:SetJustifyH("CENTER")
    IRR_BIS.noDataTxt:SetPoint("CENTER", parent, "CENTER", 0, -30)
    IRR_BIS.noDataTxt:Hide()

    -- ---- Make spec label clickable to cycle specs for this class ----
    local specClickFrame = CreateFrame("Button", nil, parent)
    specClickFrame:SetSize(120, 16)
    specClickFrame:SetPoint("LEFT", specLblKey, "RIGHT", 4, 0)
    specClickFrame:SetScript("OnClick", function()
        if not IRR_BIS_SPECS then return end
        local _, classToken = UnitClass("player")
        -- Gather all spec keys for this class, sorted
        local classSpecs = {}
        for key, spec in pairs(IRR_BIS_SPECS) do
            if spec.class == classToken then
                classSpecs[#classSpecs + 1] = key
            end
        end
        table.sort(classSpecs)
        if #classSpecs == 0 then return end
        -- Find current index and advance
        local currentIdx = 0
        for i, key in ipairs(classSpecs) do
            if key == IRR_BIS.currentSpecKey then currentIdx = i; break end
        end
        local nextIdx = (currentIdx % #classSpecs) + 1
        IRR_BIS.currentSpecKey = classSpecs[nextIdx]
        IRR_RefreshBISPanel()
    end)
    specClickFrame:SetScript("OnEnter", function()
        GameTooltip:SetOwner(specClickFrame, "ANCHOR_LEFT")
        GameTooltip:SetText("Click to cycle spec", 1,1,1)
        GameTooltip:Show()
    end)
    specClickFrame:SetScript("OnLeave", function() GameTooltip:Hide() end)

    -- Initial populate now that everything is set up
    -- Try talent-based detection first; fall back to first spec for this class;
    -- fall back to first spec in data so the tab always shows something.
    local function IRR_BIS_BestGuessSpec()
        local key = IRR_BIS_DetectSpec()
        if key then return key end
        if IRR_BIS_DATA then
            local _, cls = UnitClass("player")
            -- First pass: match class
            for k, _ in pairs(IRR_BIS_DATA) do
                if IRR_BIS_SPECS and IRR_BIS_SPECS[k] and IRR_BIS_SPECS[k].class == cls then
                    return k
                end
            end
            -- Second pass: any spec with data
            for k, _ in pairs(IRR_BIS_DATA) do return k end
        end
        return nil
    end
    IRR_BIS.currentSpecKey = IRR_BIS_BestGuessSpec()
    IRR_RefreshBISPanel()
end

-- ----------------------------------------------------------------
-- Refresh all rows to reflect current spec + phase selection
-- ----------------------------------------------------------------
function IRR_RefreshBISPanel()
    if not IRR_BIS.frame then return end

    -- Update phase button colors
    for ph, btn in pairs(IRR_BIS.phaseButtons) do
        btn.UpdateColor()
    end

    -- Auto-detect spec if not set
    if not IRR_BIS.currentSpecKey then
        IRR_BIS.currentSpecKey = IRR_BIS_DetectSpec()
        -- Fallback: pick first spec matching this class, then any spec
        if not IRR_BIS.currentSpecKey and IRR_BIS_DATA then
            local _, cls = UnitClass("player")
            for k, _ in pairs(IRR_BIS_DATA) do
                if IRR_BIS_SPECS and IRR_BIS_SPECS[k] and IRR_BIS_SPECS[k].class == cls then
                    IRR_BIS.currentSpecKey = k ; break
                end
            end
            if not IRR_BIS.currentSpecKey then
                for k, _ in pairs(IRR_BIS_DATA) do IRR_BIS.currentSpecKey = k ; break end
            end
        end
    end

    -- Update spec label
    if IRR_BIS.specLbl then
        local specKey = IRR_BIS.currentSpecKey
        if specKey and IRR_BIS_SPECS and IRR_BIS_SPECS[specKey] then
            IRR_BIS.specLbl:SetText(IRR_BIS_SPECS[specKey].label)
        else
            IRR_BIS.specLbl:SetText("Unknown")
        end
    end

    -- Check whether we have data at all
    if not IRR_BIS_DATA then
        if IRR_BIS.noDataTxt then IRR_BIS.noDataTxt:Show() end
        return
    end
    if IRR_BIS.noDataTxt then IRR_BIS.noDataTxt:Hide() end

    local specKey = IRR_BIS.currentSpecKey
    local phase   = IRR_BIS.currentPhase

    for _, slot in ipairs(SLOT_LIST) do
        local row = IRR_BIS.rows[slot.id]
        if row then
            local bisEntry = nil
            local bisRank  = nil
            local equippedRank = nil

            if specKey and IRR_BIS_DATA[specKey] and IRR_BIS_DATA[specKey][phase] then
                local slotData = IRR_BIS_DATA[specKey][phase][slot.id]
                if slotData and #slotData > 0 then
                    bisEntry = slotData[1]  -- rank 1 = best BIS

                    -- Check if equipped item is in BIS list
                    local equippedId = GetInventoryItemID("player", slot.id)
                    if equippedId then
                        for _, entry in ipairs(slotData) do
                            if entry.id == equippedId then
                                equippedRank = entry.rank
                                break
                            end
                        end
                    end
                end
            end

            if not bisEntry then
                -- No data for this slot
                row.nameTxt:SetText("–")
                row.nameTxt:SetTextColor(0.4, 0.4, 0.4)
                row.statusTxt:SetText("")
            else
                local equippedId = GetInventoryItemID("player", slot.id)
                local hasBIS     = equippedId and equippedId == bisEntry.id

                -- Name: show BIS item name (prefer client cache, fall back to stored)
                local nameStr = Trunc(GetBISItemName(bisEntry.id, bisEntry.name), 18)
                row.nameTxt:SetText(nameStr)

                if hasBIS then
                    -- Player has the best BIS item
                    row.nameTxt:SetTextColor(0.3, 0.9, 0.3)
                    row.statusTxt:SetText("|cff00ff00v|r")
                elseif equippedRank then
                    -- Player has a lower-ranked BIS item
                    row.nameTxt:SetTextColor(1.0, 0.82, 0.0)
                    row.statusTxt:SetText("|cffffff00^|r")
                else
                    -- Player does not have any BIS item for this slot
                    row.nameTxt:SetTextColor(0.9, 0.4, 0.4)
                    row.statusTxt:SetText("|cffff4444!|r")
                end
            end
        end
    end
end
