-- BIS_Data_DRUID.lua  (Auto-generated by scripts/update-bis.ps1)
-- Generated: 2026-03-01 19:51  -- DO NOT EDIT MANUALLY
IRR_BIS_DATA = IRR_BIS_DATA or {}
do local _d = {
    ["balance_druid"] = {
        [0] = {
            [1] = {
                {id=24266, name="Unknown Item 24266", score=0, rank=1, src="Vendor"},
                {id=31110, name="Unknown Item 31110", score=0, rank=2, src="Pre-Raid"},
                {id=28169, name="Unknown Item 28169", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=28134, name="Brooch of Heightened Potential", score=58.1, rank=1, src="Shadow Lab"},
                {id=27758, name="Hydra-fang Necklace", score=52.7, rank=2, src="Underbog"},
                {id=31692, name="Natasha's Ember Necklace", score=50, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=27796, name="Unknown Item 27796", score=0, rank=1, src="Slave Pens"},
                {id=27778, name="Unknown Item 27778", score=0, rank=2, src="Shadow Lab"},
                {id=30925, name="Unknown Item 30925", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=21848, name="Unknown Item 21848", score=0, rank=1, src="Vendor"},
                {id=29522, name="Unknown Item 29522", score=0, rank=2, src="Vendor"},
                {id=31297, name="Unknown Item 31297", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=21846, name="Unknown Item 21846", score=0, rank=1, src="Vendor"},
                {id=24256, name="Unknown Item 24256", score=0, rank=2, src="Vendor"},
                {id=29524, name="Unknown Item 29524", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=24262, name="Unknown Item 24262", score=0, rank=1, src="Vendor"},
                {id=30531, name="Unknown Item 30531", score=0, rank=2, src="Pre-Raid"},
                {id=29343, name="Unknown Item 29343", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=27821, name="Unknown Item 27821", score=0, rank=1, src="Mana-Tombs"},
                {id=28406, name="Unknown Item 28406", score=0, rank=2, src="Arcatraz"},
                {id=28179, name="Unknown Item 28179", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=29523, name="Unknown Item 29523", score=0, rank=1, src="Vendor"},
                {id=24250, name="Unknown Item 24250", score=0, rank=2, src="Vendor"},
                {id=27462, name="Unknown Item 27462", score=0, rank=3, src="Ramparts"},
            },
            [10] = {
                {id=21847, name="Unknown Item 21847", score=0, rank=1, src="Vendor"},
                {id=27493, name="Unknown Item 27493", score=0, rank=2, src="Auchenai"},
                {id=27537, name="Unknown Item 27537", score=0, rank=3, src="Slave Pens"},
            },
            [11] = {
                {id=29172, name="Ashyen's Gift", score=51.2, rank=1, src="Pre-Raid"},
                {id=28227, name="Sparking Arcanite Ring", score=59.1, rank=2, src="Black Morass"},
                {id=21709, name="Ring of the Fallen God", score=51.9, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=1, src="Pre-Raid"},
                {id=27683, name="Quagmirran's Eye", score=37, rank=2, src="Slave Pens"},
                {id=29132, name="Scryer's Bloodgem", score=38.4, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=27981, name="Unknown Item 27981", score=0, rank=1, src="Sethekk"},
                {id=31140, name="Unknown Item 31140", score=0, rank=2, src="Pre-Raid"},
                {id=23050, name="Unknown Item 23050", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [1] = {
            [1] = {
                {id=29093, name="Unknown Item 29093", score=0, rank=1, src="Kara/T4"},
                {id=28744, name="Unknown Item 28744", score=0, rank=2, src="Kara"},
                {id=23828, name="Unknown Item 23828", score=0, rank=3, src="Vendor"},
            },
            [2] = {
                {id=28530, name="Brooch of Unquenchable Fury", score=63.2, rank=1, src="Kara"},
                {id=28762, name="Adornment of Stolen Souls", score=66.5, rank=2, src="Kara"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=29095, name="Unknown Item 29095", score=0, rank=1, src="Kara/T4"},
                {id=27796, name="Unknown Item 27796", score=0, rank=2, src="Slave Pens"},
                {id=27778, name="Unknown Item 27778", score=0, rank=3, src="Shadow Lab"},
            },
            [5] = {
                {id=21848, name="Unknown Item 21848", score=0, rank=1, src="Vendor"},
                {id=29091, name="Unknown Item 29091", score=0, rank=2, src="Kara/T4"},
                {id=29522, name="Unknown Item 29522", score=0, rank=3, src="Vendor"},
            },
            [6] = {
                {id=21846, name="Unknown Item 21846", score=0, rank=1, src="Vendor"},
                {id=24256, name="Unknown Item 24256", score=0, rank=2, src="Vendor"},
                {id=28799, name="Unknown Item 28799", score=0, rank=3, src="Gruul"},
            },
            [7] = {
                {id=24262, name="Unknown Item 24262", score=0, rank=1, src="Vendor"},
                {id=30734, name="Unknown Item 30734", score=0, rank=2, src="Kara/T4"},
                {id=28594, name="Unknown Item 28594", score=0, rank=3, src="Kara"},
            },
            [8] = {
                {id=28517, name="Unknown Item 28517", score=0, rank=1, src="Kara"},
                {id=28585, name="Unknown Item 28585", score=0, rank=2, src="Kara"},
                {id=27821, name="Unknown Item 27821", score=0, rank=3, src="Mana-Tombs"},
            },
            [9] = {
                {id=29523, name="Unknown Item 29523", score=0, rank=1, src="Vendor"},
                {id=24250, name="Unknown Item 24250", score=0, rank=2, src="Vendor"},
                {id=27462, name="Unknown Item 27462", score=0, rank=3, src="Ramparts"},
            },
            [10] = {
                {id=21847, name="Unknown Item 21847", score=0, rank=1, src="Vendor"},
                {id=30725, name="Unknown Item 30725", score=0, rank=2, src="Kara/T4"},
                {id=28507, name="Unknown Item 28507", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=28793, name="Band of Crimson Fury", score=67, rank=1, src="Kara/T4"},
                {id=28753, name="Ring of Recurrence", score=62.6, rank=2, src="Kara"},
                {id=29287, name="Violet Signet of the Archmage", score=65.1, rank=3, src="Kara"},
            },
            [13] = {
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=1, src="Kara/T4"},
                {id=27683, name="Quagmirran's Eye", score=37, rank=2, src="Slave Pens"},
                {id=29132, name="Scryer's Bloodgem", score=38.4, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=28766, name="Unknown Item 28766", score=0, rank=1, src="Kara"},
                {id=30735, name="Unknown Item 30735", score=0, rank=2, src="Kara/T4"},
                {id=28797, name="Unknown Item 28797", score=0, rank=3, src="Gruul"},
            },
        },
        [2] = {
            [1] = {
                {id=30233, name="Unknown Item 30233", score=0, rank=1, src="SSC/TK"},
                {id=32480, name="Unknown Item 32480", score=0, rank=2, src="Vendor"},
                {id=29093, name="Unknown Item 29093", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=30015, name="The Sun King's Talisman", score=77.6, rank=1, src="SSC/TK"},
                {id=24116, name="Eye of the Night", score=42.6, rank=2, src="Vendor"},
                {id=28762, name="Adornment of Stolen Souls", score=66.5, rank=3, src="Kara"},
            },
            [3] = {
                {id=30235, name="Unknown Item 30235", score=0, rank=1, src="SSC/TK"},
                {id=30024, name="Unknown Item 30024", score=0, rank=2, src="TK"},
                {id=30079, name="Unknown Item 30079", score=0, rank=3, src="SSC"},
            },
            [5] = {
                {id=30231, name="Unknown Item 30231", score=0, rank=1, src="SSC/TK"},
                {id=30107, name="Unknown Item 30107", score=0, rank=2, src="SSC"},
                {id=21848, name="Unknown Item 21848", score=0, rank=3, src="Vendor"},
            },
            [6] = {
                {id=30038, name="Unknown Item 30038", score=0, rank=1, src="Vendor"},
                {id=30064, name="Unknown Item 30064", score=0, rank=2, src="SSC"},
                {id=21846, name="Unknown Item 21846", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=24262, name="Unknown Item 24262", score=0, rank=1, src="Vendor"},
                {id=30734, name="Unknown Item 30734", score=0, rank=2, src="SSC/TK"},
                {id=30234, name="Unknown Item 30234", score=0, rank=3, src="SSC/TK"},
            },
            [8] = {
                {id=30037, name="Unknown Item 30037", score=0, rank=1, src="Vendor"},
                {id=30067, name="Unknown Item 30067", score=0, rank=2, src="SSC"},
                {id=28517, name="Unknown Item 28517", score=0, rank=3, src="Kara"},
            },
            [9] = {
                {id=29918, name="Unknown Item 29918", score=0, rank=1, src="TK"},
                {id=29523, name="Unknown Item 29523", score=0, rank=2, src="Vendor"},
                {id=32655, name="Unknown Item 32655", score=0, rank=3, src="SSC/TK"},
            },
            [10] = {
                {id=30232, name="Unknown Item 30232", score=0, rank=1, src="SSC/TK"},
                {id=30725, name="Unknown Item 30725", score=0, rank=2, src="SSC/TK"},
                {id=21847, name="Unknown Item 21847", score=0, rank=3, src="Vendor"},
            },
            [11] = {
                {id=30109, name="Ring of Endless Coils", score=59.9, rank=1, src="SSC"},
                {id=28753, name="Ring of Recurrence", score=62.6, rank=2, src="Kara"},
                {id=29287, name="Violet Signet of the Archmage", score=65.1, rank=3, src="Kara"},
            },
            [13] = {
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=1, src="SSC/TK"},
                {id=27683, name="Quagmirran's Eye", score=37, rank=2, src="Slave Pens"},
                {id=30626, name="Sextant of Unstable Currents", score=36, rank=3, src="SSC"},
            },
            [15] = {
                {id=30735, name="Unknown Item 30735", score=0, rank=1, src="SSC/TK"},
                {id=28797, name="Unknown Item 28797", score=0, rank=2, src="Gruul"},
                {id=28766, name="Unknown Item 28766", score=0, rank=3, src="Kara"},
            },
        },
        [3] = {
            [1] = {
                {id=31040, name="Unknown Item 31040", score=0, rank=1, src="BT/Hyjal"},
                {id=32525, name="Unknown Item 32525", score=0, rank=2, src="BT"},
                {id=30233, name="Unknown Item 30233", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=30015, name="The Sun King's Talisman", score=77.6, rank=1, src="BT/Hyjal"},
                {id=32349, name="Translucent Spellthread Necklace", score=85.6, rank=2, src="BT"},
                {id=33920, name="Vindicator's Pendant of Conquest", score=59, rank=3, src="BT/Hyjal"},
            },
            [3] = {
                {id=31049, name="Unknown Item 31049", score=0, rank=1, src="BT/Hyjal"},
                {id=30884, name="Unknown Item 30884", score=0, rank=2, src="Hyjal"},
                {id=30235, name="Unknown Item 30235", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=31043, name="Unknown Item 31043", score=0, rank=1, src="BT/Hyjal"},
                {id=30231, name="Unknown Item 30231", score=0, rank=2, src="BT/Hyjal"},
                {id=30107, name="Unknown Item 30107", score=0, rank=3, src="SSC"},
            },
            [6] = {
                {id=30888, name="Unknown Item 30888", score=0, rank=1, src="Hyjal"},
                {id=30914, name="Unknown Item 30914", score=0, rank=2, src="Hyjal"},
                {id=30038, name="Unknown Item 30038", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=30916, name="Unknown Item 30916", score=0, rank=1, src="Hyjal"},
                {id=31046, name="Unknown Item 31046", score=0, rank=2, src="BT/Hyjal"},
                {id=32367, name="Unknown Item 32367", score=0, rank=3, src="BT"},
            },
            [8] = {
                {id=32239, name="Unknown Item 32239", score=0, rank=1, src="BT"},
                {id=32352, name="Unknown Item 32352", score=0, rank=2, src="BT"},
                {id=30894, name="Unknown Item 30894", score=0, rank=3, src="Hyjal"},
            },
            [9] = {
                {id=32586, name="Unknown Item 32586", score=0, rank=1, src="Vendor"},
                {id=32270, name="Unknown Item 32270", score=0, rank=2, src="BT"},
                {id=32351, name="Unknown Item 32351", score=0, rank=3, src="BT"},
            },
            [10] = {
                {id=31035, name="Unknown Item 31035", score=0, rank=1, src="BT/Hyjal"},
                {id=30232, name="Unknown Item 30232", score=0, rank=2, src="BT/Hyjal"},
                {id=32328, name="Unknown Item 32328", score=0, rank=3, src="BT/Hyjal"},
            },
            [11] = {
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=1, src="BT"},
                {id=29305, name="Band of the Eternal Sage", score=78.4, rank=2, src="BT/Hyjal"},
                {id=32247, name="Ring of Captured Storms", score=90.9, rank=3, src="BT"},
            },
            [13] = {
                {id=32483, name="The Skull of Gul'dan", score=85, rank=1, src="BT"},
                {id=32486, name="Ashtongue Talisman of Equilibrium", score=0, rank=2, src="BT"},
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=32331, name="Unknown Item 32331", score=0, rank=2, src="BT"},
                {id=28766, name="Unknown Item 28766", score=0, rank=3, src="Kara"},
            },
        },
        [4] = {
            [1] = {
                {id=31040, name="Unknown Item 31040", score=0, rank=1, src="ZA"},
                {id=30233, name="Unknown Item 30233", score=0, rank=2, src="ZA"},
                {id=32525, name="Unknown Item 32525", score=0, rank=3, src="BT"},
            },
            [2] = {
                {id=33281, name="Brooch of Nature's Mercy", score=44.2, rank=1, src="ZA"},
                {id=33466, name="Loop of Cursed Bones", score=49.9, rank=2, src="ZA"},
                {id=30015, name="The Sun King's Talisman", score=77.6, rank=3, src="ZA"},
            },
            [3] = {
                {id=31049, name="Unknown Item 31049", score=0, rank=1, src="ZA"},
                {id=30235, name="Unknown Item 30235", score=0, rank=2, src="ZA"},
                {id=33973, name="Unknown Item 33973", score=0, rank=3, src="ZA"},
            },
            [5] = {
                {id=31043, name="Unknown Item 31043", score=0, rank=1, src="ZA"},
                {id=30231, name="Unknown Item 30231", score=0, rank=2, src="ZA"},
                {id=30107, name="Unknown Item 30107", score=0, rank=3, src="SSC"},
            },
            [6] = {
                {id=30888, name="Unknown Item 30888", score=0, rank=1, src="Hyjal"},
                {id=30914, name="Unknown Item 30914", score=0, rank=2, src="Hyjal"},
                {id=30038, name="Unknown Item 30038", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=30916, name="Unknown Item 30916", score=0, rank=1, src="Hyjal"},
                {id=31046, name="Unknown Item 31046", score=0, rank=2, src="ZA"},
                {id=32367, name="Unknown Item 32367", score=0, rank=3, src="BT"},
            },
            [8] = {
                {id=32239, name="Unknown Item 32239", score=0, rank=1, src="BT"},
                {id=32352, name="Unknown Item 32352", score=0, rank=2, src="BT"},
                {id=33357, name="Unknown Item 33357", score=0, rank=3, src="ZA"},
            },
            [9] = {
                {id=32586, name="Unknown Item 32586", score=0, rank=1, src="Vendor"},
                {id=32270, name="Unknown Item 32270", score=0, rank=2, src="BT"},
                {id=32351, name="Unknown Item 32351", score=0, rank=3, src="BT"},
            },
            [10] = {
                {id=31035, name="Unknown Item 31035", score=0, rank=1, src="ZA"},
                {id=30232, name="Unknown Item 30232", score=0, rank=2, src="ZA"},
                {id=30725, name="Unknown Item 30725", score=0, rank=3, src="ZA"},
            },
            [11] = {
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=1, src="BT"},
                {id=29305, name="Band of the Eternal Sage", score=78.4, rank=2, src="ZA"},
                {id=33497, name="Mana Attuned Band", score=70.8, rank=3, src="ZA"},
            },
            [13] = {
                {id=32483, name="The Skull of Gul'dan", score=85, rank=1, src="BT"},
                {id=33829, name="Hex Shrunken Head", score=53, rank=2, src="ZA"},
                {id=32486, name="Ashtongue Talisman of Equilibrium", score=0, rank=3, src="BT"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=32331, name="Unknown Item 32331", score=0, rank=2, src="BT"},
                {id=33591, name="Unknown Item 33591", score=0, rank=3, src="ZA"},
            },
        },
        [5] = {
            [1] = {
                {id=34340, name="Unknown Item 34340", score=0, rank=1, src="SWP"},
                {id=34403, name="Unknown Item 34403", score=0, rank=2, src="SWP"},
                {id=32525, name="Unknown Item 32525", score=0, rank=3, src="BT"},
            },
            [2] = {
                {id=34359, name="Pendant of Sunfire", score=74.4, rank=1, src="Vendor"},
                {id=34204, name="Amulet of Unfettered Magics", score=73, rank=2, src="SWP"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=34210, name="Unknown Item 34210", score=0, rank=1, src="SWP"},
                {id=34391, name="Unknown Item 34391", score=0, rank=2, src="SWP"},
                {id=31049, name="Unknown Item 31049", score=0, rank=3, src="SWP"},
            },
            [5] = {
                {id=34364, name="Unknown Item 34364", score=0, rank=1, src="Vendor"},
                {id=34232, name="Unknown Item 34232", score=0, rank=2, src="SWP"},
                {id=34399, name="Unknown Item 34399", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34555, name="Unknown Item 34555", score=0, rank=1, src="SWP"},
                {id=30888, name="Unknown Item 30888", score=0, rank=2, src="Hyjal"},
                {id=30914, name="Unknown Item 30914", score=0, rank=3, src="Hyjal"},
            },
            [7] = {
                {id=34181, name="Unknown Item 34181", score=0, rank=1, src="SWP"},
                {id=34169, name="Unknown Item 34169", score=0, rank=2, src="SWP"},
                {id=34386, name="Unknown Item 34386", score=0, rank=3, src="SWP"},
            },
            [8] = {
                {id=34572, name="Unknown Item 34572", score=0, rank=1, src="SWP"},
                {id=32239, name="Unknown Item 32239", score=0, rank=2, src="BT"},
                {id=32352, name="Unknown Item 32352", score=0, rank=3, src="BT"},
            },
            [9] = {
                {id=34446, name="Unknown Item 34446", score=0, rank=1, src="SWP"},
                {id=32586, name="Unknown Item 32586", score=0, rank=2, src="Vendor"},
                {id=32270, name="Unknown Item 32270", score=0, rank=3, src="BT"},
            },
            [10] = {
                {id=34344, name="Unknown Item 34344", score=0, rank=1, src="SWP"},
                {id=34406, name="Unknown Item 34406", score=0, rank=2, src="SWP"},
                {id=34366, name="Unknown Item 34366", score=0, rank=3, src="Vendor"},
            },
            [11] = {
                {id=34362, name="Loop of Forged Power", score=81.9, rank=1, src="Vendor"},
                {id=34230, name="Ring of Omnipotence", score=73.1, rank=2, src="SWP"},
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=3, src="BT"},
            },
            [13] = {
                {id=34429, name="Shifting Naaru Sliver", score=0, rank=1, src="SWP"},
                {id=32483, name="The Skull of Gul'dan", score=85, rank=2, src="BT"},
                {id=33829, name="Hex Shrunken Head", score=53, rank=3, src="ZA"},
            },
            [15] = {
                {id=34242, name="Unknown Item 34242", score=0, rank=1, src="SWP"},
                {id=32331, name="Unknown Item 32331", score=0, rank=2, src="BT"},
                {id=32524, name="Unknown Item 32524", score=0, rank=3, src="BT"},
            },
        },
    },
    ["feral_dps_druid"] = {
        [0] = {
            [2] = {
                {id=24114, name="Braided Eternium Chain", score=42, rank=1, src="Vendor"},
                {id=29381, name="Choker of Vile Intent", score=109.8, rank=2, src="Pre-Raid"},
                {id=31275, name="Necklace of Trophies", score=98.9, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=27797, name="Unknown Item 27797", score=0, rank=1, src="Pre-Raid"},
                {id=25790, name="Unknown Item 25790", score=0, rank=2, src="Pre-Raid"},
                {id=28755, name="Unknown Item 28755", score=0, rank=3, src="Kara"},
            },
            [5] = {
                {id=29525, name="Unknown Item 29525", score=0, rank=1, src="Vendor"},
                {id=28204, name="Unknown Item 28204", score=0, rank=2, src="Mechanar"},
                {id=24396, name="Unknown Item 24396", score=0, rank=3, src="Sh. Halls"},
            },
            [6] = {
                {id=29247, name="Unknown Item 29247", score=0, rank=1, src="Pre-Raid"},
                {id=30372, name="Unknown Item 30372", score=0, rank=2, src="Pre-Raid"},
                {id=27911, name="Unknown Item 27911", score=0, rank=3, src="Black Morass"},
            },
            [7] = {
                {id=31544, name="Unknown Item 31544", score=0, rank=1, src="Pre-Raid"},
                {id=30257, name="Unknown Item 30257", score=0, rank=2, src="Pre-Raid"},
                {id=27837, name="Unknown Item 27837", score=0, rank=3, src="Mana-Tombs"},
            },
            [8] = {
                {id=25686, name="Unknown Item 25686", score=0, rank=1, src="Vendor"},
                {id=31288, name="Unknown Item 31288", score=0, rank=2, src="Pre-Raid"},
                {id=29248, name="Unknown Item 29248", score=0, rank=3, src="Arcatraz"},
            },
            [9] = {
                {id=29246, name="Unknown Item 29246", score=0, rank=1, src="Black Morass"},
                {id=28171, name="Unknown Item 28171", score=0, rank=2, src="Pre-Raid"},
            },
            [10] = {
                {id=28396, name="Unknown Item 28396", score=0, rank=1, src="Arcatraz"},
                {id=29507, name="Unknown Item 29507", score=0, rank=2, src="Vendor"},
                {id=25685, name="Unknown Item 25685", score=0, rank=3, src="Vendor"},
            },
            [11] = {
                {id=30834, name="Shapeshifter's Signet", score=79.3, rank=1, src="Pre-Raid"},
                {id=31920, name="Shaffar's Band of Brutality", score=106, rank=2, src="Pre-Raid"},
                {id=30365, name="Overseer's Signet", score=97.5, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=23206, name="Mark of the Champion", score=0, rank=1, src="Pre-Raid"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=2, src="Pre-Raid"},
                {id=28034, name="Hourglass of the Unraveller", score=44.8, rank=3, src="Black Morass"},
            },
            [15] = {
                {id=31255, name="Unknown Item 31255", score=0, rank=1, src="Pre-Raid"},
                {id=24259, name="Unknown Item 24259", score=0, rank=2, src="Vendor"},
                {id=27878, name="Unknown Item 27878", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [1] = {
            [2] = {
                {id=24114, name="Braided Eternium Chain", score=42, rank=1, src="Vendor"},
                {id=29381, name="Choker of Vile Intent", score=109.8, rank=2, src="Kara/T4"},
                {id=29119, name="Haramad's Bargain", score=94.7, rank=3, src="Kara/T4"},
            },
            [3] = {
                {id=29100, name="Unknown Item 29100", score=0, rank=1, src="Kara/T4"},
                {id=27797, name="Unknown Item 27797", score=0, rank=2, src="Kara/T4"},
                {id=25790, name="Unknown Item 25790", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=29096, name="Unknown Item 29096", score=0, rank=1, src="Kara/T4"},
                {id=30730, name="Unknown Item 30730", score=0, rank=2, src="Kara/T4"},
                {id=28601, name="Unknown Item 28601", score=0, rank=3, src="Kara"},
            },
            [6] = {
                {id=29247, name="Unknown Item 29247", score=0, rank=1, src="Kara/T4"},
                {id=30676, name="Unknown Item 30676", score=0, rank=2, src="Kara"},
                {id=28750, name="Unknown Item 28750", score=0, rank=3, src="Kara"},
            },
            [7] = {
                {id=28741, name="Unknown Item 28741", score=0, rank=1, src="Kara"},
                {id=31544, name="Unknown Item 31544", score=0, rank=2, src="Kara/T4"},
                {id=30257, name="Unknown Item 30257", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=28545, name="Unknown Item 28545", score=0, rank=1, src="Kara"},
                {id=25686, name="Unknown Item 25686", score=0, rank=2, src="Vendor"},
                {id=31288, name="Unknown Item 31288", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=29246, name="Unknown Item 29246", score=0, rank=1, src="Black Morass"},
                {id=30685, name="Unknown Item 30685", score=0, rank=2, src="Kara"},
                {id=28171, name="Unknown Item 28171", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=28506, name="Unknown Item 28506", score=0, rank=1, src="Kara"},
                {id=30644, name="Unknown Item 30644", score=0, rank=2, src="Kara"},
                {id=29507, name="Unknown Item 29507", score=0, rank=3, src="Vendor"},
            },
            [11] = {
                {id=30834, name="Shapeshifter's Signet", score=79.3, rank=1, src="Kara/T4"},
                {id=28649, name="Garona's Signet Ring", score=108.5, rank=2, src="Kara"},
                {id=28791, name="Ring of the Recalcitrant", score=92.7, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=23206, name="Mark of the Champion", score=0, rank=1, src="Kara/T4"},
                {id=28830, name="Dragonspine Trophy", score=40, rank=2, src="Gruul"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=28672, name="Unknown Item 28672", score=0, rank=1, src="Kara"},
                {id=24259, name="Unknown Item 24259", score=0, rank=2, src="Vendor"},
                {id=31255, name="Unknown Item 31255", score=0, rank=3, src="Kara/T4"},
            },
        },
        [2] = {
            [2] = {
                {id=24114, name="Braided Eternium Chain", score=42, rank=1, src="Vendor"},
                {id=30017, name="Telonicus's Pendant of Mayhem", score=113.1, rank=2, src="SSC/TK"},
                {id=29381, name="Choker of Vile Intent", score=109.8, rank=3, src="SSC/TK"},
            },
            [3] = {
                {id=30055, name="Unknown Item 30055", score=0, rank=1, src="SSC"},
                {id=29100, name="Unknown Item 29100", score=0, rank=2, src="SSC/TK"},
                {id=30230, name="Unknown Item 30230", score=0, rank=3, src="SSC/TK"},
            },
            [5] = {
                {id=30101, name="Unknown Item 30101", score=0, rank=1, src="SSC"},
                {id=29096, name="Unknown Item 29096", score=0, rank=2, src="SSC/TK"},
                {id=30222, name="Unknown Item 30222", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=30106, name="Unknown Item 30106", score=0, rank=1, src="SSC"},
                {id=30040, name="Unknown Item 30040", score=0, rank=2, src="Vendor"},
                {id=29247, name="Unknown Item 29247", score=0, rank=3, src="SSC/TK"},
            },
            [7] = {
                {id=28741, name="Unknown Item 28741", score=0, rank=1, src="Kara"},
                {id=29995, name="Unknown Item 29995", score=0, rank=2, src="SSC/TK"},
                {id=30229, name="Unknown Item 30229", score=0, rank=3, src="SSC/TK"},
            },
            [8] = {
                {id=28545, name="Unknown Item 28545", score=0, rank=1, src="Kara"},
                {id=30039, name="Unknown Item 30039", score=0, rank=2, src="Vendor"},
                {id=25686, name="Unknown Item 25686", score=0, rank=3, src="Vendor"},
            },
            [9] = {
                {id=29966, name="Unknown Item 29966", score=0, rank=1, src="TK"},
                {id=30685, name="Unknown Item 30685", score=0, rank=2, src="Kara"},
                {id=28171, name="Unknown Item 28171", score=0, rank=3, src="SSC/TK"},
            },
            [10] = {
                {id=29947, name="Unknown Item 29947", score=0, rank=1, src="TK"},
                {id=30223, name="Unknown Item 30223", score=0, rank=2, src="SSC/TK"},
                {id=28506, name="Unknown Item 28506", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=30052, name="Ring of Lethality", score=125.9, rank=1, src="SSC"},
                {id=29997, name="Band of the Ranger-General", score=133.9, rank=2, src="SSC/TK"},
                {id=30834, name="Shapeshifter's Signet", score=79.3, rank=3, src="SSC/TK"},
            },
            [13] = {
                {id=30627, name="Tsunami Talisman", score=73.2, rank=1, src="SSC"},
                {id=23206, name="Mark of the Champion", score=0, rank=2, src="SSC/TK"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=3, src="SSC/TK"},
            },
            [15] = {
                {id=28672, name="Unknown Item 28672", score=0, rank=1, src="Kara"},
                {id=29994, name="Unknown Item 29994", score=0, rank=2, src="SSC/TK"},
                {id=30098, name="Unknown Item 30098", score=0, rank=3, src="SSC"},
            },
        },
        [3] = {
            [1] = {
                {id=32235, name="Unknown Item 32235", score=0, rank=1, src="BT"},
                {id=33672, name="Unknown Item 33672", score=0, rank=2, src="BT/Hyjal"},
            },
            [2] = {
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=1, src="BT"},
                {id=30017, name="Telonicus's Pendant of Mayhem", score=113.1, rank=2, src="BT/Hyjal"},
                {id=32591, name="Choker of Serrated Blades", score=353.7, rank=3, src="BT"},
            },
            [3] = {
                {id=31048, name="Unknown Item 31048", score=0, rank=1, src="BT/Hyjal"},
                {id=29100, name="Unknown Item 29100", score=0, rank=2, src="BT/Hyjal"},
                {id=30230, name="Unknown Item 30230", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=32252, name="Unknown Item 32252", score=0, rank=1, src="BT"},
                {id=31042, name="Unknown Item 31042", score=0, rank=2, src="BT/Hyjal"},
                {id=29096, name="Unknown Item 29096", score=0, rank=3, src="BT/Hyjal"},
            },
            [6] = {
                {id=30106, name="Unknown Item 30106", score=0, rank=1, src="SSC"},
                {id=30040, name="Unknown Item 30040", score=0, rank=2, src="Vendor"},
                {id=30879, name="Unknown Item 30879", score=0, rank=3, src="Hyjal"},
            },
            [7] = {
                {id=31044, name="Unknown Item 31044", score=0, rank=1, src="BT/Hyjal"},
                {id=28741, name="Unknown Item 28741", score=0, rank=2, src="Kara"},
                {id=30898, name="Unknown Item 30898", score=0, rank=3, src="Hyjal"},
            },
            [8] = {
                {id=32366, name="Unknown Item 32366", score=0, rank=1, src="BT"},
                {id=28545, name="Unknown Item 28545", score=0, rank=2, src="Kara"},
                {id=25686, name="Unknown Item 25686", score=0, rank=3, src="Vendor"},
            },
            [9] = {
                {id=32324, name="Unknown Item 32324", score=0, rank=1, src="BT/Hyjal"},
                {id=33881, name="Unknown Item 33881", score=0, rank=2, src="BT/Hyjal"},
                {id=30863, name="Unknown Item 30863", score=0, rank=3, src="Hyjal"},
            },
            [10] = {
                {id=29947, name="Unknown Item 29947", score=0, rank=1, src="TK"},
                {id=31034, name="Unknown Item 31034", score=0, rank=2, src="BT/Hyjal"},
                {id=28506, name="Unknown Item 28506", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=32497, name="Stormrage Signet Ring", score=330.9, rank=1, src="BT"},
                {id=29301, name="Band of the Eternal Champion", score=107.8, rank=2, src="BT/Hyjal"},
                {id=30052, name="Ring of Lethality", score=125.9, rank=3, src="SSC"},
            },
            [13] = {
                {id=30627, name="Tsunami Talisman", score=73.2, rank=1, src="SSC"},
                {id=32505, name="Madness of the Betrayer", score=124, rank=2, src="BT"},
                {id=23206, name="Mark of the Champion", score=0, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32323, name="Unknown Item 32323", score=0, rank=1, src="BT/Hyjal"},
                {id=29994, name="Unknown Item 29994", score=0, rank=2, src="BT/Hyjal"},
                {id=28672, name="Unknown Item 28672", score=0, rank=3, src="Kara"},
            },
        },
        [4] = {
            [1] = {
                {id=32235, name="Unknown Item 32235", score=0, rank=1, src="BT"},
                {id=33672, name="Unknown Item 33672", score=0, rank=2, src="ZA"},
            },
            [2] = {
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=1, src="BT"},
                {id=30017, name="Telonicus's Pendant of Mayhem", score=113.1, rank=2, src="ZA"},
                {id=32591, name="Choker of Serrated Blades", score=353.7, rank=3, src="BT"},
            },
            [3] = {
                {id=31048, name="Unknown Item 31048", score=0, rank=1, src="ZA"},
                {id=29100, name="Unknown Item 29100", score=0, rank=2, src="ZA"},
                {id=30230, name="Unknown Item 30230", score=0, rank=3, src="ZA"},
            },
            [5] = {
                {id=32252, name="Unknown Item 32252", score=0, rank=1, src="BT"},
                {id=31042, name="Unknown Item 31042", score=0, rank=2, src="ZA"},
                {id=29096, name="Unknown Item 29096", score=0, rank=3, src="ZA"},
            },
            [6] = {
                {id=30106, name="Unknown Item 30106", score=0, rank=1, src="SSC"},
                {id=30040, name="Unknown Item 30040", score=0, rank=2, src="Vendor"},
                {id=30879, name="Unknown Item 30879", score=0, rank=3, src="Hyjal"},
            },
            [7] = {
                {id=31044, name="Unknown Item 31044", score=0, rank=1, src="ZA"},
                {id=30898, name="Unknown Item 30898", score=0, rank=2, src="Hyjal"},
                {id=28741, name="Unknown Item 28741", score=0, rank=3, src="Kara"},
            },
            [8] = {
                {id=33222, name="Unknown Item 33222", score=0, rank=1, src="ZA"},
                {id=32366, name="Unknown Item 32366", score=0, rank=2, src="BT"},
                {id=28545, name="Unknown Item 28545", score=0, rank=3, src="Kara"},
            },
            [9] = {
                {id=32324, name="Unknown Item 32324", score=0, rank=1, src="ZA"},
                {id=33881, name="Unknown Item 33881", score=0, rank=2, src="ZA"},
                {id=30863, name="Unknown Item 30863", score=0, rank=3, src="Hyjal"},
            },
            [10] = {
                {id=29947, name="Unknown Item 29947", score=0, rank=1, src="TK"},
                {id=31034, name="Unknown Item 31034", score=0, rank=2, src="ZA"},
                {id=28506, name="Unknown Item 28506", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=33496, name="Signet of Primal Wrath", score=304.6, rank=1, src="ZA"},
                {id=32497, name="Stormrage Signet Ring", score=330.9, rank=2, src="BT"},
                {id=29301, name="Band of the Eternal Champion", score=107.8, rank=3, src="ZA"},
            },
            [13] = {
                {id=30627, name="Tsunami Talisman", score=73.2, rank=1, src="SSC"},
                {id=32505, name="Madness of the Betrayer", score=124, rank=2, src="BT"},
                {id=33831, name="Berserker's Call", score=90, rank=3, src="ZA"},
            },
            [15] = {
                {id=32323, name="Unknown Item 32323", score=0, rank=1, src="ZA"},
                {id=29994, name="Unknown Item 29994", score=0, rank=2, src="ZA"},
                {id=28672, name="Unknown Item 28672", score=0, rank=3, src="Kara"},
            },
        },
        [5] = {
            [1] = {
                {id=34244, name="Unknown Item 34244", score=0, rank=1, src="SWP"},
                {id=31039, name="Unknown Item 31039", score=0, rank=2, src="SWP"},
                {id=32235, name="Unknown Item 32235", score=0, rank=3, src="BT"},
            },
            [2] = {
                {id=34358, name="Hard Khorium Choker", score=302.2, rank=1, src="Vendor"},
                {id=24114, name="Braided Eternium Chain", score=42, rank=2, src="Vendor"},
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=3, src="BT"},
            },
            [3] = {
                {id=34392, name="Unknown Item 34392", score=0, rank=1, src="SWP"},
                {id=31048, name="Unknown Item 31048", score=0, rank=2, src="SWP"},
                {id=34195, name="Unknown Item 34195", score=0, rank=3, src="SWP"},
            },
            [5] = {
                {id=34397, name="Unknown Item 34397", score=0, rank=1, src="SWP"},
                {id=34369, name="Unknown Item 34369", score=0, rank=2, src="Vendor"},
                {id=34211, name="Unknown Item 34211", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34556, name="Unknown Item 34556", score=0, rank=1, src="SWP"},
                {id=30106, name="Unknown Item 30106", score=0, rank=2, src="SSC"},
                {id=34929, name="Unknown Item 34929", score=0, rank=3, src="SWP"},
            },
            [7] = {
                {id=34188, name="Unknown Item 34188", score=0, rank=1, src="SWP"},
                {id=31044, name="Unknown Item 31044", score=0, rank=2, src="SWP"},
                {id=34385, name="Unknown Item 34385", score=0, rank=3, src="SWP"},
            },
            [8] = {
                {id=33222, name="Unknown Item 33222", score=0, rank=1, src="SWP"},
                {id=34573, name="Unknown Item 34573", score=0, rank=2, src="SWP"},
                {id=32366, name="Unknown Item 32366", score=0, rank=3, src="BT"},
            },
            [9] = {
                {id=34444, name="Unknown Item 34444", score=0, rank=1, src="SWP"},
                {id=35167, name="Unknown Item 35167", score=0, rank=2, src="SWP"},
                {id=32324, name="Unknown Item 32324", score=0, rank=3, src="SWP"},
            },
            [10] = {
                {id=34370, name="Unknown Item 34370", score=0, rank=1, src="Vendor"},
                {id=34408, name="Unknown Item 34408", score=0, rank=2, src="SWP"},
                {id=34234, name="Unknown Item 34234", score=0, rank=3, src="SWP"},
            },
            [11] = {
                {id=32497, name="Stormrage Signet Ring", score=330.9, rank=1, src="BT"},
                {id=34189, name="Band of Ruinous Delight", score=371.4, rank=2, src="SWP"},
                {id=34887, name="Angelista's Revenge", score=305.9, rank=3, src="SWP"},
            },
            [13] = {
                {id=34472, name="Shard of Contempt", score=88, rank=1, src="SWP"},
                {id=34427, name="Blackened Naaru Sliver", score=0, rank=2, src="SWP"},
                {id=32505, name="Madness of the Betrayer", score=124, rank=3, src="BT"},
            },
            [15] = {
                {id=34241, name="Unknown Item 34241", score=0, rank=1, src="SWP"},
                {id=32323, name="Unknown Item 32323", score=0, rank=2, src="SWP"},
                {id=28672, name="Unknown Item 28672", score=0, rank=3, src="Kara"},
            },
        },
    },
    ["feral_tank_druid"] = {
        [0] = {
            [1] = {
                {id=29502, name="Unknown Item 29502", score=0, rank=1, src="Vendor"},
                {id=28182, name="Unknown Item 28182", score=0, rank=2, src="Pre-Raid"},
                {id=32087, name="Unknown Item 32087", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=29815, name="Chain of Glowing Tendrils", score=59, rank=1, src="Pre-Raid"},
                {id=28168, name="Insignia of the Mag'hari Hero", score=42, rank=2, src="Pre-Raid"},
                {id=29381, name="Choker of Vile Intent", score=36, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=27434, name="Unknown Item 27434", score=0, rank=1, src="Black Morass"},
                {id=27776, name="Unknown Item 27776", score=0, rank=2, src="Sethekk"},
                {id=32080, name="Unknown Item 32080", score=0, rank=3, src="Sh. Halls"},
            },
            [5] = {
                {id=25689, name="Unknown Item 25689", score=0, rank=1, src="Vendor"},
                {id=28204, name="Unknown Item 28204", score=0, rank=2, src="Mechanar"},
                {id=29525, name="Unknown Item 29525", score=0, rank=3, src="Vendor"},
            },
            [6] = {
                {id=30942, name="Unknown Item 30942", score=0, rank=1, src="Pre-Raid"},
                {id=29264, name="Unknown Item 29264", score=0, rank=2, src="Pre-Raid"},
                {id=29247, name="Unknown Item 29247", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=25690, name="Unknown Item 25690", score=0, rank=1, src="Vendor"},
                {id=31544, name="Unknown Item 31544", score=0, rank=2, src="Pre-Raid"},
                {id=30538, name="Unknown Item 30538", score=0, rank=3, src="Slave Pens"},
            },
            [8] = {
                {id=28987, name="Unknown Item 28987", score=0, rank=1, src="Pre-Raid"},
                {id=25691, name="Unknown Item 25691", score=0, rank=2, src="Vendor"},
                {id=28339, name="Unknown Item 28339", score=0, rank=3, src="Botanica"},
            },
            [9] = {
                {id=30944, name="Unknown Item 30944", score=0, rank=1, src="Pre-Raid"},
                {id=28978, name="Unknown Item 28978", score=0, rank=2, src="Pre-Raid"},
                {id=29263, name="Unknown Item 29263", score=0, rank=3, src="Slave Pens"},
            },
            [10] = {
                {id=30943, name="Unknown Item 30943", score=0, rank=1, src="Pre-Raid"},
                {id=30341, name="Unknown Item 30341", score=0, rank=2, src="Pre-Raid"},
                {id=29507, name="Unknown Item 29507", score=0, rank=3, src="Vendor"},
            },
            [11] = {
                {id=30834, name="Shapeshifter's Signet", score=36, rank=1, src="Pre-Raid"},
                {id=29384, name="Ring of Unyielding Force", score=130.9, rank=2, src="Pre-Raid"},
                {id=27436, name="Iron Band of the Unbreakable", score=106.7, rank=3, src="Old Hill."},
            },
            [13] = {
                {id=23206, name="Mark of the Champion", score=0, rank=1, src="Pre-Raid"},
                {id=29383, name="Bloodlust Brooch", score=0, rank=2, src="Pre-Raid"},
                {id=28121, name="Icon of Unyielding Courage", score=0, rank=3, src="Sh. Halls"},
            },
            [15] = {
                {id=28256, name="Unknown Item 28256", score=0, rank=1, src="Mechanar"},
                {id=24258, name="Unknown Item 24258", score=0, rank=2, src="Vendor"},
                {id=28377, name="Unknown Item 28377", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [1] = {
            [1] = {
                {id=29098, name="Unknown Item 29098", score=0, rank=1, src="Kara/T4"},
                {id=28796, name="Unknown Item 28796", score=0, rank=2, src="Gruul"},
                {id=28127, name="Unknown Item 28127", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=28509, name="Worgen Claw Necklace", score=42, rank=1, src="Kara"},
                {id=29381, name="Choker of Vile Intent", score=36, rank=2, src="Kara/T4"},
                {id=28674, name="Saberclaw Talisman", score=66, rank=3, src="Kara"},
            },
            [3] = {
                {id=29100, name="Unknown Item 29100", score=0, rank=1, src="Kara/T4"},
                {id=28129, name="Unknown Item 28129", score=0, rank=2, src="Kara/T4"},
                {id=28755, name="Unknown Item 28755", score=0, rank=3, src="Kara"},
            },
            [5] = {
                {id=29096, name="Unknown Item 29096", score=0, rank=1, src="Kara/T4"},
                {id=28130, name="Unknown Item 28130", score=0, rank=2, src="Kara/T4"},
                {id=29525, name="Unknown Item 29525", score=0, rank=3, src="Vendor"},
            },
            [6] = {
                {id=29264, name="Unknown Item 29264", score=0, rank=1, src="Kara/T4"},
                {id=28828, name="Unknown Item 28828", score=0, rank=2, src="Kara/T4"},
                {id=28750, name="Unknown Item 28750", score=0, rank=3, src="Kara"},
            },
            [7] = {
                {id=29099, name="Unknown Item 29099", score=0, rank=1, src="Kara/T4"},
                {id=28741, name="Unknown Item 28741", score=0, rank=2, src="Kara"},
                {id=30535, name="Unknown Item 30535", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=30674, name="Unknown Item 30674", score=0, rank=1, src="Kara/T4"},
                {id=28545, name="Unknown Item 28545", score=0, rank=2, src="Kara"},
                {id=28987, name="Unknown Item 28987", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=28978, name="Unknown Item 28978", score=0, rank=1, src="Kara/T4"},
                {id=29263, name="Unknown Item 29263", score=0, rank=2, src="Slave Pens"},
                {id=30944, name="Unknown Item 30944", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=29097, name="Unknown Item 29097", score=0, rank=1, src="Kara/T4"},
                {id=30644, name="Unknown Item 30644", score=0, rank=2, src="Kara"},
                {id=28506, name="Unknown Item 28506", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=29279, name="Violet Signet of the Great Protector", score=134.9, rank=1, src="Kara/T4"},
                {id=28792, name="A'dal's Signet of Defense", score=131.7, rank=2, src="Kara/T4"},
                {id=30834, name="Shapeshifter's Signet", score=36, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=23206, name="Mark of the Champion", score=0, rank=1, src="Kara/T4"},
                {id=28830, name="Dragonspine Trophy", score=0, rank=2, src="Gruul"},
                {id=29383, name="Bloodlust Brooch", score=0, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=28660, name="Unknown Item 28660", score=0, rank=1, src="Kara/T4"},
                {id=28672, name="Unknown Item 28672", score=0, rank=2, src="Kara"},
                {id=28777, name="Unknown Item 28777", score=0, rank=3, src="Kara/T4"},
            },
        },
        [2] = {
            [1] = {
                {id=30228, name="Unknown Item 30228", score=0, rank=1, src="SSC/TK"},
                {id=29098, name="Unknown Item 29098", score=0, rank=2, src="SSC/TK"},
                {id=32478, name="Unknown Item 32478", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=30017, name="Telonicus's Pendant of Mayhem", score=52, rank=1, src="SSC/TK"},
                {id=33066, name="Veteran's Pendant of Triumph", score=62, rank=2, src="SSC/TK"},
                {id=28509, name="Worgen Claw Necklace", score=42, rank=3, src="Kara"},
            },
            [3] = {
                {id=30230, name="Unknown Item 30230", score=0, rank=1, src="SSC/TK"},
                {id=30055, name="Unknown Item 30055", score=0, rank=2, src="SSC"},
                {id=29100, name="Unknown Item 29100", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=30222, name="Unknown Item 30222", score=0, rank=1, src="SSC/TK"},
                {id=29096, name="Unknown Item 29096", score=0, rank=2, src="Kara/T4"},
                {id=31972, name="Unknown Item 31972", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=30106, name="Unknown Item 30106", score=0, rank=1, src="SSC"},
                {id=30042, name="Unknown Item 30042", score=0, rank=2, src="SSC/TK"},
                {id=30040, name="Unknown Item 30040", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=30229, name="Unknown Item 30229", score=0, rank=1, src="SSC/TK"},
                {id=29099, name="Unknown Item 29099", score=0, rank=2, src="Kara/T4"},
                {id=29995, name="Unknown Item 29995", score=0, rank=3, src="SSC/TK"},
            },
            [8] = {
                {id=30041, name="Unknown Item 30041", score=0, rank=1, src="SSC/TK"},
                {id=32790, name="Unknown Item 32790", score=0, rank=2, src="SSC/TK"},
                {id=30674, name="Unknown Item 30674", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=32810, name="Unknown Item 32810", score=0, rank=1, src="SSC/TK"},
                {id=32814, name="Unknown Item 32814", score=0, rank=2, src="SSC/TK"},
                {id=28978, name="Unknown Item 28978", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=30223, name="Unknown Item 30223", score=0, rank=1, src="SSC/TK"},
                {id=29947, name="Unknown Item 29947", score=0, rank=2, src="TK"},
                {id=29097, name="Unknown Item 29097", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=29279, name="Violet Signet of the Great Protector", score=134.9, rank=1, src="Kara/T4"},
                {id=28792, name="A'dal's Signet of Defense", score=131.7, rank=2, src="Kara/T4"},
                {id=30834, name="Shapeshifter's Signet", score=36, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=32658, name="Badge of Tenacity", score=3.1, rank=1, src="SSC/TK"},
                {id=28579, name="Romulo's Poison Vial", score=0, rank=2, src="SSC/TK"},
                {id=28830, name="Dragonspine Trophy", score=0, rank=3, src="Gruul"},
            },
            [15] = {
                {id=28660, name="Unknown Item 28660", score=0, rank=1, src="Kara/T4"},
                {id=29994, name="Unknown Item 29994", score=0, rank=2, src="SSC/TK"},
                {id=24258, name="Unknown Item 24258", score=0, rank=3, src="Vendor"},
            },
        },
        [3] = {
            [1] = {
                {id=31039, name="Unknown Item 31039", score=0, rank=1, src="BT/Hyjal"},
                {id=33672, name="Unknown Item 33672", score=0, rank=2, src="BT/Hyjal"},
                {id=32235, name="Unknown Item 32235", score=0, rank=3, src="BT"},
            },
            [2] = {
                {id=30017, name="Telonicus's Pendant of Mayhem", score=52, rank=1, src="SSC/TK"},
                {id=33923, name="Vindicator's Pendant of Triumph", score=70, rank=2, src="BT/Hyjal"},
                {id=32362, name="Pendant of Titans", score=211.5, rank=3, src="BT/Hyjal"},
            },
            [3] = {
                {id=31048, name="Unknown Item 31048", score=0, rank=1, src="BT/Hyjal"},
                {id=33674, name="Unknown Item 33674", score=0, rank=2, src="BT/Hyjal"},
                {id=30230, name="Unknown Item 30230", score=0, rank=3, src="SSC/TK"},
            },
            [5] = {
                {id=31042, name="Unknown Item 31042", score=0, rank=1, src="BT/Hyjal"},
                {id=30222, name="Unknown Item 30222", score=0, rank=2, src="SSC/TK"},
                {id=33675, name="Unknown Item 33675", score=0, rank=3, src="BT/Hyjal"},
            },
            [6] = {
                {id=30106, name="Unknown Item 30106", score=0, rank=1, src="SSC"},
                {id=30042, name="Unknown Item 30042", score=0, rank=2, src="SSC/TK"},
                {id=30879, name="Unknown Item 30879", score=0, rank=3, src="Hyjal"},
            },
            [7] = {
                {id=31044, name="Unknown Item 31044", score=0, rank=1, src="BT/Hyjal"},
                {id=30229, name="Unknown Item 30229", score=0, rank=2, src="SSC/TK"},
                {id=30898, name="Unknown Item 30898", score=0, rank=3, src="Hyjal"},
            },
            [8] = {
                {id=32593, name="Unknown Item 32593", score=0, rank=1, src="BT/Hyjal"},
                {id=32366, name="Unknown Item 32366", score=0, rank=2, src="BT"},
                {id=33880, name="Unknown Item 33880", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=32324, name="Unknown Item 32324", score=0, rank=1, src="BT/Hyjal"},
                {id=33881, name="Unknown Item 33881", score=0, rank=2, src="BT/Hyjal"},
                {id=33893, name="Unknown Item 33893", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=31034, name="Unknown Item 31034", score=0, rank=1, src="BT/Hyjal"},
                {id=30223, name="Unknown Item 30223", score=0, rank=2, src="SSC/TK"},
                {id=29947, name="Unknown Item 29947", score=0, rank=3, src="TK"},
            },
            [11] = {
                {id=29279, name="Violet Signet of the Great Protector", score=134.9, rank=1, src="Kara/T4"},
                {id=32266, name="Ring of Deceitful Intent", score=84, rank=2, src="BT/Hyjal"},
                {id=29301, name="Band of the Eternal Champion", score=86, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=32501, name="Shadowmoon Insignia", score=188, rank=1, src="BT/Hyjal"},
                {id=34578, name="Battlemaster's Determination", score=0, rank=2, src="BT/Hyjal"},
                {id=29383, name="Bloodlust Brooch", score=0, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=28660, name="Unknown Item 28660", score=0, rank=1, src="Kara/T4"},
                {id=29994, name="Unknown Item 29994", score=0, rank=2, src="SSC/TK"},
                {id=34010, name="Unknown Item 34010", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [4] = {
            [1] = {
                {id=32235, name="Unknown Item 32235", score=0, rank=1, src="BT"},
                {id=33672, name="Unknown Item 33672", score=0, rank=2, src="BT/Hyjal"},
                {id=31039, name="Unknown Item 31039", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=33296, name="Brooch of Deftness", score=96, rank=1, src="ZA"},
                {id=24114, name="Braided Eternium Chain", score=0, rank=2, src="Vendor"},
                {id=32362, name="Pendant of Titans", score=211.5, rank=3, src="BT/Hyjal"},
            },
            [3] = {
                {id=31048, name="Unknown Item 31048", score=0, rank=1, src="BT/Hyjal"},
                {id=33674, name="Unknown Item 33674", score=0, rank=2, src="BT/Hyjal"},
                {id=30230, name="Unknown Item 30230", score=0, rank=3, src="SSC/TK"},
            },
            [5] = {
                {id=31042, name="Unknown Item 31042", score=0, rank=1, src="BT/Hyjal"},
                {id=30222, name="Unknown Item 30222", score=0, rank=2, src="SSC/TK"},
                {id=33675, name="Unknown Item 33675", score=0, rank=3, src="BT/Hyjal"},
            },
            [6] = {
                {id=30106, name="Unknown Item 30106", score=0, rank=1, src="SSC"},
                {id=33583, name="Unknown Item 33583", score=0, rank=2, src="ZA"},
                {id=30042, name="Unknown Item 30042", score=0, rank=3, src="SSC/TK"},
            },
            [7] = {
                {id=31044, name="Unknown Item 31044", score=0, rank=1, src="BT/Hyjal"},
                {id=30229, name="Unknown Item 30229", score=0, rank=2, src="SSC/TK"},
                {id=30898, name="Unknown Item 30898", score=0, rank=3, src="Hyjal"},
            },
            [8] = {
                {id=32593, name="Unknown Item 32593", score=0, rank=1, src="BT/Hyjal"},
                {id=33880, name="Unknown Item 33880", score=0, rank=2, src="BT/Hyjal"},
                {id=32366, name="Unknown Item 32366", score=0, rank=3, src="BT"},
            },
            [9] = {
                {id=32324, name="Unknown Item 32324", score=0, rank=1, src="BT/Hyjal"},
                {id=33881, name="Unknown Item 33881", score=0, rank=2, src="BT/Hyjal"},
                {id=33580, name="Unknown Item 33580", score=0, rank=3, src="ZA"},
            },
            [10] = {
                {id=31034, name="Unknown Item 31034", score=0, rank=1, src="BT/Hyjal"},
                {id=30223, name="Unknown Item 30223", score=0, rank=2, src="SSC/TK"},
                {id=29947, name="Unknown Item 29947", score=0, rank=3, src="TK"},
            },
            [11] = {
                {id=29279, name="Violet Signet of the Great Protector", score=134.9, rank=1, src="Kara/T4"},
                {id=32266, name="Ring of Deceitful Intent", score=84, rank=2, src="BT/Hyjal"},
                {id=29301, name="Band of the Eternal Champion", score=86, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=32501, name="Shadowmoon Insignia", score=188, rank=1, src="BT/Hyjal"},
                {id=34578, name="Battlemaster's Determination", score=0, rank=2, src="BT/Hyjal"},
                {id=28288, name="Abacus of Violent Odds", score=0, rank=3, src="ZA"},
            },
            [15] = {
                {id=33593, name="Unknown Item 33593", score=0, rank=1, src="ZA"},
                {id=33484, name="Unknown Item 33484", score=0, rank=2, src="ZA"},
                {id=28660, name="Unknown Item 28660", score=0, rank=3, src="Kara/T4"},
            },
        },
        [5] = {
            [1] = {
                {id=34404, name="Unknown Item 34404", score=0, rank=1, src="SWP"},
                {id=34244, name="Unknown Item 34244", score=0, rank=2, src="SWP"},
                {id=31039, name="Unknown Item 31039", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=34178, name="Collar of the Pit Lord", score=201, rank=1, src="SWP"},
                {id=32362, name="Pendant of Titans", score=211.5, rank=2, src="BT/Hyjal"},
                {id=33296, name="Brooch of Deftness", score=96, rank=3, src="ZA"},
            },
            [3] = {
                {id=34392, name="Unknown Item 34392", score=0, rank=1, src="SWP"},
                {id=31048, name="Unknown Item 31048", score=0, rank=2, src="BT/Hyjal"},
                {id=35001, name="Unknown Item 35001", score=0, rank=3, src="SWP"},
            },
            [5] = {
                {id=34211, name="Unknown Item 34211", score=0, rank=1, src="SWP"},
                {id=31042, name="Unknown Item 31042", score=0, rank=2, src="BT/Hyjal"},
                {id=34369, name="Unknown Item 34369", score=0, rank=3, src="Vendor"},
            },
            [6] = {
                {id=35156, name="Unknown Item 35156", score=0, rank=1, src="SWP"},
                {id=34556, name="Unknown Item 34556", score=0, rank=2, src="SWP"},
                {id=30106, name="Unknown Item 30106", score=0, rank=3, src="SSC"},
            },
            [7] = {
                {id=34385, name="Unknown Item 34385", score=0, rank=1, src="SWP"},
                {id=34910, name="Unknown Item 34910", score=0, rank=2, src="SWP"},
                {id=34188, name="Unknown Item 34188", score=0, rank=3, src="SWP"},
            },
            [8] = {
                {id=34573, name="Unknown Item 34573", score=0, rank=1, src="SWP"},
                {id=32593, name="Unknown Item 32593", score=0, rank=2, src="BT/Hyjal"},
                {id=33222, name="Unknown Item 33222", score=0, rank=3, src="SWP"},
            },
            [9] = {
                {id=34444, name="Unknown Item 34444", score=0, rank=1, src="SWP"},
                {id=35171, name="Unknown Item 35171", score=0, rank=2, src="SWP"},
                {id=35167, name="Unknown Item 35167", score=0, rank=3, src="SWP"},
            },
            [10] = {
                {id=34408, name="Unknown Item 34408", score=0, rank=1, src="SWP"},
                {id=34911, name="Unknown Item 34911", score=0, rank=2, src="SWP"},
                {id=34234, name="Unknown Item 34234", score=0, rank=3, src="SWP"},
            },
            [11] = {
                {id=34213, name="Ring of Hardened Resolve", score=195.1, rank=1, src="SWP"},
                {id=34888, name="Ring of the Stalwart Protector", score=163.9, rank=2, src="SWP"},
                {id=34361, name="Hard Khorium Band", score=84, rank=3, src="SWP"},
            },
            [13] = {
                {id=32501, name="Shadowmoon Insignia", score=188, rank=1, src="BT/Hyjal"},
                {id=32658, name="Badge of Tenacity", score=3.1, rank=2, src="SSC/TK"},
                {id=34473, name="Commendation of Kael'thas", score=114, rank=3, src="SWP"},
            },
            [15] = {
                {id=34190, name="Unknown Item 34190", score=0, rank=1, src="SWP"},
                {id=34241, name="Unknown Item 34241", score=0, rank=2, src="SWP"},
                {id=34010, name="Unknown Item 34010", score=0, rank=3, src="BT/Hyjal"},
            },
        },
    },
    ["resto_druid"] = {
        [0] = {
            [1] = {
                {id=24264, name="Unknown Item 24264", score=0, rank=1, src="Pre-Raid"},
                {id=31376, name="Unknown Item 31376", score=0, rank=2, src="Pre-Raid"},
                {id=32090, name="Unknown Item 32090", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=30377, name="Karja's Medallion", score=65, rank=1, src="Pre-Raid"},
                {id=31691, name="Natasha's Guardian Cord", score=56.5, rank=2, src="Pre-Raid"},
                {id=29374, name="Necklace of Eternal Hope", score=60.1, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=21874, name="Unknown Item 21874", score=0, rank=1, src="Pre-Raid"},
                {id=27775, name="Unknown Item 27775", score=0, rank=2, src="Pre-Raid"},
                {id=31378, name="Unknown Item 31378", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=21875, name="Unknown Item 21875", score=0, rank=1, src="Pre-Raid"},
                {id=29522, name="Unknown Item 29522", score=0, rank=2, src="Vendor"},
                {id=31379, name="Unknown Item 31379", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=21873, name="Unknown Item 21873", score=0, rank=1, src="Pre-Raid"},
                {id=29524, name="Unknown Item 29524", score=0, rank=2, src="Vendor"},
                {id=29250, name="Unknown Item 29250", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=24261, name="Unknown Item 24261", score=0, rank=1, src="Pre-Raid"},
                {id=30543, name="Unknown Item 30543", score=0, rank=2, src="Pre-Raid"},
                {id=31343, name="Unknown Item 31343", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=27411, name="Unknown Item 27411", score=0, rank=1, src="Pre-Raid"},
                {id=29251, name="Unknown Item 29251", score=0, rank=2, src="Pre-Raid"},
                {id=25792, name="Unknown Item 25792", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=29183, name="Unknown Item 29183", score=0, rank=1, src="Pre-Raid"},
                {id=29523, name="Unknown Item 29523", score=0, rank=2, src="Vendor"},
                {id=29249, name="Unknown Item 29249", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=29506, name="Unknown Item 29506", score=0, rank=1, src="Pre-Raid"},
                {id=31375, name="Unknown Item 31375", score=0, rank=2, src="Pre-Raid"},
                {id=24393, name="Unknown Item 24393", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=27780, name="Ring of Fabled Hope", score=67, rank=1, src="Pre-Raid"},
                {id=31383, name="Spiritualist's Mark of the Sha'tar", score=63.6, rank=2, src="Pre-Raid"},
                {id=29373, name="Band of Halos", score=58.3, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=30841, name="Lower City Prayerbook", score=63, rank=2, src="Pre-Raid"},
                {id=19395, name="Rejuvenating Gem", score=59.4, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=31329, name="Unknown Item 31329", score=0, rank=1, src="Pre-Raid"},
                {id=24254, name="Unknown Item 24254", score=0, rank=2, src="Pre-Raid"},
                {id=27946, name="Unknown Item 27946", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [1] = {
            [1] = {
                {id=24264, name="Unknown Item 24264", score=0, rank=1, src="Pre-Raid"},
                {id=29086, name="Unknown Item 29086", score=0, rank=2, src="Kara/T4"},
                {id=31376, name="Unknown Item 31376", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=30726, name="Archaic Charm of Presence", score=83.6, rank=1, src="Kara/T4"},
                {id=28822, name="Teeth of Gruul", score=65.6, rank=2, src="Kara/T4"},
                {id=28609, name="Emberspur Talisman", score=59.4, rank=3, src="Kara/T4"},
            },
            [3] = {
                {id=21874, name="Unknown Item 21874", score=0, rank=1, src="Pre-Raid"},
                {id=29089, name="Unknown Item 29089", score=0, rank=2, src="Kara/T4"},
                {id=28612, name="Unknown Item 28612", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=21875, name="Unknown Item 21875", score=0, rank=1, src="Pre-Raid"},
                {id=29087, name="Unknown Item 29087", score=0, rank=2, src="Kara/T4"},
                {id=29522, name="Unknown Item 29522", score=0, rank=3, src="Vendor"},
            },
            [6] = {
                {id=21873, name="Unknown Item 21873", score=0, rank=1, src="Pre-Raid"},
                {id=28655, name="Unknown Item 28655", score=0, rank=2, src="Kara/T4"},
                {id=29524, name="Unknown Item 29524", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=30727, name="Unknown Item 30727", score=0, rank=1, src="Kara/T4"},
                {id=24261, name="Unknown Item 24261", score=0, rank=2, src="Pre-Raid"},
                {id=28591, name="Unknown Item 28591", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=30737, name="Unknown Item 30737", score=0, rank=1, src="Kara/T4"},
                {id=28752, name="Unknown Item 28752", score=0, rank=2, src="Kara/T4"},
                {id=28663, name="Unknown Item 28663", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=29183, name="Unknown Item 29183", score=0, rank=1, src="Pre-Raid"},
                {id=29523, name="Unknown Item 29523", score=0, rank=2, src="Vendor"},
                {id=28511, name="Unknown Item 28511", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=28521, name="Unknown Item 28521", score=0, rank=1, src="Kara/T4"},
                {id=28508, name="Unknown Item 28508", score=0, rank=2, src="Kara/T4"},
                {id=29090, name="Unknown Item 29090", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=29290, name="Violet Signet of the Grand Restorer", score=76.5, rank=1, src="Kara/T4"},
                {id=28763, name="Jade Ring of the Everliving", score=61.2, rank=2, src="Kara/T4"},
                {id=28790, name="Naaru Lightwarden's Band", score=69.1, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=25634, name="Oshu'gun Relic", score=47.7, rank=2, src="Kara/T4"},
                {id=19395, name="Rejuvenating Gem", score=59.4, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=28765, name="Unknown Item 28765", score=0, rank=1, src="Kara/T4"},
                {id=31329, name="Unknown Item 31329", score=0, rank=2, src="Pre-Raid"},
                {id=29354, name="Unknown Item 29354", score=0, rank=3, src="Kara/T4"},
            },
        },
        [2] = {
        },
        [3] = {
            [1] = {
                {id=31037, name="Unknown Item 31037", score=0, rank=1, src="BT/Hyjal"},
                {id=32329, name="Unknown Item 32329", score=0, rank=2, src="BT/Hyjal"},
                {id=30219, name="Unknown Item 30219", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=30018, name="Lord Sanguinar's Claim", score=86.9, rank=1, src="BT/Hyjal"},
                {id=32370, name="Nadina's Pendant of Purity", score=92, rank=2, src="BT/Hyjal"},
                {id=30726, name="Archaic Charm of Presence", score=83.6, rank=3, src="Kara/T4"},
            },
            [3] = {
                {id=31047, name="Unknown Item 31047", score=0, rank=1, src="BT/Hyjal"},
                {id=30221, name="Unknown Item 30221", score=0, rank=2, src="BT/Hyjal"},
                {id=32583, name="Unknown Item 32583", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=31041, name="Unknown Item 31041", score=0, rank=1, src="BT/Hyjal"},
                {id=30216, name="Unknown Item 30216", score=0, rank=2, src="BT/Hyjal"},
                {id=21875, name="Unknown Item 21875", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=30895, name="Unknown Item 30895", score=0, rank=1, src="BT/Hyjal"},
                {id=32339, name="Unknown Item 32339", score=0, rank=2, src="BT/Hyjal"},
                {id=21873, name="Unknown Item 21873", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=30912, name="Unknown Item 30912", score=0, rank=1, src="BT/Hyjal"},
                {id=32271, name="Unknown Item 32271", score=0, rank=2, src="BT/Hyjal"},
                {id=30727, name="Unknown Item 30727", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=30737, name="Unknown Item 30737", score=0, rank=1, src="Kara/T4"},
                {id=32609, name="Unknown Item 32609", score=0, rank=2, src="BT/Hyjal"},
                {id=30092, name="Unknown Item 30092", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=30868, name="Unknown Item 30868", score=0, rank=1, src="BT/Hyjal"},
                {id=32584, name="Unknown Item 32584", score=0, rank=2, src="BT/Hyjal"},
                {id=32582, name="Unknown Item 32582", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=32328, name="Unknown Item 32328", score=0, rank=1, src="BT/Hyjal"},
                {id=32353, name="Unknown Item 32353", score=0, rank=2, src="BT/Hyjal"},
                {id=31032, name="Unknown Item 31032", score=0, rank=3, src="BT/Hyjal"},
            },
            [11] = {
                {id=32528, name="Blessed Band of Karabor", score=81.7, rank=1, src="BT/Hyjal"},
                {id=30110, name="Coral Band of the Revived", score=92.9, rank=2, src="BT/Hyjal"},
                {id=29309, name="Band of the Eternal Restorer", score=77.9, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=38288, name="Direbrew Hops", score=75.6, rank=2, src="BT/Hyjal"},
                {id=32496, name="Memento of Tyrande", score=106.2, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=32337, name="Unknown Item 32337", score=0, rank=2, src="BT/Hyjal"},
                {id=29989, name="Unknown Item 29989", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [4] = {
            [1] = {
                {id=31037, name="Unknown Item 31037", score=0, rank=1, src="BT/Hyjal"},
                {id=32329, name="Unknown Item 32329", score=0, rank=2, src="BT/Hyjal"},
                {id=30219, name="Unknown Item 30219", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=33281, name="Brooch of Nature's Mercy", score=93.8, rank=1, src="ZA"},
                {id=35317, name="Vindicator's Pendant of Reprieve", score=59.3, rank=2, src="ZA"},
                {id=30018, name="Lord Sanguinar's Claim", score=86.9, rank=3, src="BT/Hyjal"},
            },
            [3] = {
                {id=31047, name="Unknown Item 31047", score=0, rank=1, src="BT/Hyjal"},
                {id=30221, name="Unknown Item 30221", score=0, rank=2, src="BT/Hyjal"},
                {id=33287, name="Unknown Item 33287", score=0, rank=3, src="ZA"},
            },
            [5] = {
                {id=31041, name="Unknown Item 31041", score=0, rank=1, src="BT/Hyjal"},
                {id=30216, name="Unknown Item 30216", score=0, rank=2, src="BT/Hyjal"},
                {id=33203, name="Unknown Item 33203", score=0, rank=3, src="ZA"},
            },
            [6] = {
                {id=30895, name="Unknown Item 30895", score=0, rank=1, src="BT/Hyjal"},
                {id=32339, name="Unknown Item 32339", score=0, rank=2, src="BT/Hyjal"},
                {id=33483, name="Unknown Item 33483", score=0, rank=3, src="ZA"},
            },
            [7] = {
                {id=30912, name="Unknown Item 30912", score=0, rank=1, src="BT/Hyjal"},
                {id=32271, name="Unknown Item 32271", score=0, rank=2, src="BT/Hyjal"},
                {id=30727, name="Unknown Item 30727", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=32609, name="Unknown Item 32609", score=0, rank=1, src="BT/Hyjal"},
                {id=30737, name="Unknown Item 30737", score=0, rank=2, src="Kara/T4"},
                {id=30092, name="Unknown Item 30092", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=30868, name="Unknown Item 30868", score=0, rank=1, src="BT/Hyjal"},
                {id=32584, name="Unknown Item 32584", score=0, rank=2, src="BT/Hyjal"},
                {id=32582, name="Unknown Item 32582", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=32328, name="Unknown Item 32328", score=0, rank=1, src="BT/Hyjal"},
                {id=32353, name="Unknown Item 32353", score=0, rank=2, src="BT/Hyjal"},
                {id=33587, name="Unknown Item 33587", score=0, rank=3, src="ZA"},
            },
            [11] = {
                {id=32528, name="Blessed Band of Karabor", score=81.7, rank=1, src="BT/Hyjal"},
                {id=30110, name="Coral Band of the Revived", score=92.9, rank=2, src="BT/Hyjal"},
                {id=29309, name="Band of the Eternal Restorer", score=77.9, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=38288, name="Direbrew Hops", score=75.6, rank=2, src="BT/Hyjal"},
                {id=32496, name="Memento of Tyrande", score=106.2, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=32337, name="Unknown Item 32337", score=0, rank=2, src="BT/Hyjal"},
                {id=29989, name="Unknown Item 29989", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [5] = {
            [1] = {
                {id=34339, name="Unknown Item 34339", score=0, rank=1, src="SWP"},
                {id=34245, name="Unknown Item 34245", score=0, rank=2, src="SWP"},
                {id=35183, name="Unknown Item 35183", score=0, rank=3, src="SWP"},
            },
            [2] = {
                {id=33281, name="Brooch of Nature's Mercy", score=93.8, rank=1, src="ZA"},
                {id=34360, name="Amulet of Flowing Life", score=73.6, rank=2, src="SWP"},
                {id=34677, name="Shattered Sun Pendant of Restoration", score=64.9, rank=3, src="SWP"},
            },
            [3] = {
                {id=34209, name="Unknown Item 34209", score=0, rank=1, src="SWP"},
                {id=34202, name="Unknown Item 34202", score=0, rank=2, src="SWP"},
                {id=31047, name="Unknown Item 31047", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=34212, name="Unknown Item 34212", score=0, rank=1, src="SWP"},
                {id=34233, name="Unknown Item 34233", score=0, rank=2, src="SWP"},
                {id=34365, name="Unknown Item 34365", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34554, name="Unknown Item 34554", score=0, rank=1, src="SWP"},
                {id=30895, name="Unknown Item 30895", score=0, rank=2, src="BT/Hyjal"},
                {id=32339, name="Unknown Item 32339", score=0, rank=3, src="BT/Hyjal"},
            },
            [7] = {
                {id=34384, name="Unknown Item 34384", score=0, rank=1, src="SWP"},
                {id=34170, name="Unknown Item 34170", score=0, rank=2, src="SWP"},
                {id=30912, name="Unknown Item 30912", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=34571, name="Unknown Item 34571", score=0, rank=1, src="SWP"},
                {id=32609, name="Unknown Item 32609", score=0, rank=2, src="BT/Hyjal"},
                {id=30737, name="Unknown Item 30737", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=34445, name="Unknown Item 34445", score=0, rank=1, src="SWP"},
                {id=30868, name="Unknown Item 30868", score=0, rank=2, src="BT/Hyjal"},
                {id=32584, name="Unknown Item 32584", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=34342, name="Unknown Item 34342", score=0, rank=1, src="SWP"},
                {id=34372, name="Unknown Item 34372", score=0, rank=2, src="SWP"},
                {id=34367, name="Unknown Item 34367", score=0, rank=3, src="SWP"},
            },
            [11] = {
                {id=32528, name="Blessed Band of Karabor", score=81.7, rank=1, src="BT/Hyjal"},
                {id=34166, name="Band of Lucent Beams", score=85.6, rank=2, src="SWP"},
                {id=29309, name="Band of the Eternal Restorer", score=77.9, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=38288, name="Direbrew Hops", score=75.6, rank=2, src="BT/Hyjal"},
                {id=35750, name="Redeemer's Alchemist Stone", score=107.1, rank=3, src="SWP"},
            },
            [15] = {
                {id=32337, name="Unknown Item 32337", score=0, rank=1, src="BT/Hyjal"},
                {id=32524, name="Unknown Item 32524", score=0, rank=2, src="BT"},
                {id=29989, name="Unknown Item 29989", score=0, rank=3, src="BT/Hyjal"},
            },
        },
    },
}
for k,v in pairs(_d) do IRR_BIS_DATA[k] = v end
end
