-- BIS_Data_HUNTER.lua  (Auto-generated by scripts/update-bis.ps1)
-- Generated: 2026-03-01 19:51  -- DO NOT EDIT MANUALLY
IRR_BIS_DATA = IRR_BIS_DATA or {}
do local _d = {
    ["bm_hunter"] = {
        [0] = {
            [1] = {
                {id=28275, name="Unknown Item 28275", score=0, rank=1, src="Pre-Raid"},
                {id=22438, name="Unknown Item 22438", score=0, rank=2, src="Pre-Raid"},
                {id=31109, name="Unknown Item 31109", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=29381, name="Choker of Vile Intent", score=119.8, rank=1, src="Pre-Raid"},
                {id=19377, name="Prestor's Talisman of Connivery", score=92, rank=2, src="Pre-Raid"},
                {id=28343, name="Jagged Bark Pendant", score=83.5, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=27801, name="Unknown Item 27801", score=0, rank=1, src="Pre-Raid"},
                {id=25790, name="Unknown Item 25790", score=0, rank=2, src="Pre-Raid"},
                {id=22439, name="Unknown Item 22439", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=28228, name="Unknown Item 28228", score=0, rank=1, src="Pre-Raid"},
                {id=29525, name="Unknown Item 29525", score=0, rank=2, src="Vendor"},
                {id=29515, name="Unknown Item 29515", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=29526, name="Unknown Item 29526", score=0, rank=1, src="Pre-Raid"},
                {id=27760, name="Unknown Item 27760", score=0, rank=2, src="Pre-Raid"},
                {id=29516, name="Unknown Item 29516", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=27874, name="Unknown Item 27874", score=0, rank=1, src="Pre-Raid"},
                {id=30538, name="Unknown Item 30538", score=0, rank=2, src="Slave Pens"},
                {id=27837, name="Unknown Item 27837", score=0, rank=3, src="Mana-Tombs"},
            },
            [8] = {
                {id=25686, name="Unknown Item 25686", score=0, rank=1, src="Vendor"},
                {id=31288, name="Unknown Item 31288", score=0, rank=2, src="Pre-Raid"},
                {id=22440, name="Unknown Item 22440", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=29527, name="Unknown Item 29527", score=0, rank=1, src="Pre-Raid"},
                {id=29246, name="Unknown Item 29246", score=0, rank=2, src="Black Morass"},
                {id=25697, name="Unknown Item 25697", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=27474, name="Unknown Item 27474", score=0, rank=1, src="Pre-Raid"},
                {id=30951, name="Unknown Item 30951", score=0, rank=2, src="Pre-Raid"},
                {id=22441, name="Unknown Item 22441", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=30860, name="Kaylaan's Signet", score=100, rank=1, src="Pre-Raid"},
                {id=31077, name="Unknown Item 31077", score=0, rank=2, src="Pre-Raid"},
                {id=27925, name="Ravenclaw Band", score=97.5, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=29383, name="Bloodlust Brooch", score=72, rank=1, src="Kara/T4"},
                {id=28288, name="Abacus of Violent Odds", score=64, rank=2, src="ZA"},
                {id=28034, name="Hourglass of the Unraveller", score=44.8, rank=3, src="Black Morass"},
            },
            [15] = {
                {id=24259, name="Unknown Item 24259", score=0, rank=1, src="Vendor"},
                {id=29382, name="Unknown Item 29382", score=0, rank=2, src="Pre-Raid"},
                {id=31255, name="Unknown Item 31255", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [1] = {
            [1] = {
                {id=28275, name="Unknown Item 28275", score=0, rank=1, src="Pre-Raid"},
                {id=29081, name="Unknown Item 29081", score=0, rank=2, src="Kara/T4"},
                {id=31109, name="Unknown Item 31109", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=29381, name="Choker of Vile Intent", score=119.8, rank=1, src="Pre-Raid"},
                {id=28509, name="Worgen Claw Necklace", score=118.1, rank=2, src="Kara"},
                {id=28674, name="Saberclaw Talisman", score=91.3, rank=3, src="Kara"},
            },
            [3] = {
                {id=27801, name="Unknown Item 27801", score=0, rank=1, src="Pre-Raid"},
                {id=25790, name="Unknown Item 25790", score=0, rank=2, src="Pre-Raid"},
                {id=27797, name="Unknown Item 27797", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=28228, name="Unknown Item 28228", score=0, rank=1, src="Pre-Raid"},
                {id=29525, name="Unknown Item 29525", score=0, rank=2, src="Vendor"},
                {id=29515, name="Unknown Item 29515", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=28828, name="Unknown Item 28828", score=0, rank=1, src="Kara/T4"},
                {id=28750, name="Unknown Item 28750", score=0, rank=2, src="Kara"},
                {id=29247, name="Unknown Item 29247", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=30739, name="Unknown Item 30739", score=0, rank=1, src="Kara/T4"},
                {id=28741, name="Unknown Item 28741", score=0, rank=2, src="Kara"},
                {id=30538, name="Unknown Item 30538", score=0, rank=3, src="Slave Pens"},
            },
            [8] = {
                {id=28545, name="Unknown Item 28545", score=0, rank=1, src="Kara"},
                {id=25686, name="Unknown Item 25686", score=0, rank=2, src="Vendor"},
                {id=28746, name="Unknown Item 28746", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=29246, name="Unknown Item 29246", score=0, rank=1, src="Black Morass"},
                {id=29527, name="Unknown Item 29527", score=0, rank=2, src="Pre-Raid"},
                {id=25697, name="Unknown Item 25697", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=27474, name="Unknown Item 27474", score=0, rank=1, src="Pre-Raid"},
                {id=28506, name="Unknown Item 28506", score=0, rank=2, src="Kara"},
                {id=28827, name="Unknown Item 28827", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=28791, name="Ring of the Recalcitrant", score=104.7, rank=1, src="Kara/T4"},
                {id=28757, name="Ring of a Thousand Marks", score=116.3, rank=2, src="Kara/T4"},
                {id=28649, name="Garona's Signet Ring", score=118.5, rank=3, src="Kara"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=2, src="Kara/T4"},
                {id=28288, name="Abacus of Violent Odds", score=64, rank=3, src="ZA"},
            },
            [15] = {
                {id=24259, name="Unknown Item 24259", score=0, rank=1, src="Vendor"},
                {id=29382, name="Unknown Item 29382", score=0, rank=2, src="Pre-Raid"},
                {id=28777, name="Unknown Item 28777", score=0, rank=3, src="Kara/T4"},
            },
            [16] = {
                {id=27846, name="Unknown Item 27846", score=0, rank=1, src="Kara/T4"},
                {id=29121, name="Unknown Item 29121", score=0, rank=2, src="Kara/T4"},
                {id=28524, name="Unknown Item 28524", score=0, rank=3, src="Kara/T4"},
            },
            [17] = {
                {id=28572, name="Unknown Item 28572", score=0, rank=1, src="Kara/T4"},
                {id=28315, name="Unknown Item 28315", score=0, rank=2, src="Kara/T4"},
                {id=29372, name="Unknown Item 29372", score=0, rank=3, src="Kara/T4"},
            },
            [18] = {
                {id=28772, name="Unknown Item 28772", score=0, rank=1, src="Kara/T4"},
                {id=30724, name="Unknown Item 30724", score=0, rank=2, src="Kara/T4"},
                {id=28581, name="Unknown Item 28581", score=0, rank=3, src="Kara/T4"},
            },
        },
        [2] = {
            [1] = {
                {id=30141, name="Unknown Item 30141", score=0, rank=1, src="SSC/TK"},
                {id=28275, name="Unknown Item 28275", score=0, rank=2, src="Pre-Raid"},
                {id=32474, name="Unknown Item 32474", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=30017, name="Telonicus's Pendant of Mayhem", score=126.6, rank=1, src="SSC/TK"},
                {id=30059, name="Choker of Animalistic Fury", score=98.6, rank=2, src="SSC/TK"},
                {id=28674, name="Saberclaw Talisman", score=91.3, rank=3, src="Kara"},
            },
            [3] = {
                {id=30143, name="Unknown Item 30143", score=0, rank=1, src="SSC/TK"},
                {id=27801, name="Unknown Item 27801", score=0, rank=2, src="Pre-Raid"},
                {id=30055, name="Unknown Item 30055", score=0, rank=3, src="SSC"},
            },
            [5] = {
                {id=30139, name="Unknown Item 30139", score=0, rank=1, src="SSC/TK"},
                {id=28228, name="Unknown Item 28228", score=0, rank=2, src="Pre-Raid"},
                {id=30054, name="Unknown Item 30054", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=30040, name="Unknown Item 30040", score=0, rank=1, src="Vendor"},
                {id=30046, name="Unknown Item 30046", score=0, rank=2, src="SSC/TK"},
                {id=30106, name="Unknown Item 30106", score=0, rank=3, src="SSC"},
            },
            [7] = {
                {id=29995, name="Unknown Item 29995", score=0, rank=1, src="SSC/TK"},
                {id=29985, name="Unknown Item 29985", score=0, rank=2, src="SSC/TK"},
                {id=30739, name="Unknown Item 30739", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=30104, name="Unknown Item 30104", score=0, rank=1, src="SSC/TK"},
                {id=29951, name="Unknown Item 29951", score=0, rank=2, src="SSC/TK"},
                {id=30060, name="Unknown Item 30060", score=0, rank=3, src="SSC/TK"},
            },
            [9] = {
                {id=29966, name="Unknown Item 29966", score=0, rank=1, src="TK"},
                {id=30026, name="Unknown Item 30026", score=0, rank=2, src="SSC/TK"},
                {id=30091, name="Unknown Item 30091", score=0, rank=3, src="SSC/TK"},
            },
            [10] = {
                {id=30140, name="Unknown Item 30140", score=0, rank=1, src="SSC/TK"},
                {id=27474, name="Unknown Item 27474", score=0, rank=2, src="Pre-Raid"},
                {id=28506, name="Unknown Item 28506", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=28791, name="Ring of the Recalcitrant", score=104.7, rank=1, src="Kara/T4"},
                {id=29997, name="Band of the Ranger-General", score=133.9, rank=2, src="SSC/TK"},
                {id=30052, name="Ring of Lethality", score=137.9, rank=3, src="SSC"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=2, src="Kara/T4"},
                {id=28288, name="Abacus of Violent Odds", score=64, rank=3, src="ZA"},
            },
            [15] = {
                {id=29994, name="Unknown Item 29994", score=0, rank=1, src="SSC/TK"},
                {id=24259, name="Unknown Item 24259", score=0, rank=2, src="Vendor"},
                {id=29382, name="Unknown Item 29382", score=0, rank=3, src="Pre-Raid"},
            },
            [16] = {
                {id=32944, name="Unknown Item 32944", score=0, rank=1, src="SSC/TK"},
                {id=29948, name="Unknown Item 29948", score=0, rank=2, src="SSC/TK"},
                {id=27846, name="Unknown Item 27846", score=0, rank=3, src="Kara/T4"},
            },
            [18] = {
                {id=30105, name="Unknown Item 30105", score=0, rank=1, src="SSC/TK"},
                {id=31986, name="Unknown Item 31986", score=0, rank=2, src="SSC/TK"},
                {id=28772, name="Unknown Item 28772", score=0, rank=3, src="Kara/T4"},
            },
        },
        [3] = {
            [1] = {
                {id=32235, name="Unknown Item 32235", score=0, rank=1, src="BT"},
                {id=33666, name="Unknown Item 33666", score=0, rank=2, src="BT/Hyjal"},
                {id=31003, name="Unknown Item 31003", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=32591, name="Choker of Serrated Blades", score=73.7, rank=1, src="BT"},
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=2, src="BT"},
                {id=30017, name="Telonicus's Pendant of Mayhem", score=126.6, rank=3, src="SSC/TK"},
            },
            [3] = {
                {id=31006, name="Unknown Item 31006", score=0, rank=1, src="BT/Hyjal"},
                {id=30143, name="Unknown Item 30143", score=0, rank=2, src="SSC/TK"},
                {id=30892, name="Unknown Item 30892", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=31004, name="Unknown Item 31004", score=0, rank=1, src="BT/Hyjal"},
                {id=30139, name="Unknown Item 30139", score=0, rank=2, src="SSC/TK"},
                {id=28228, name="Unknown Item 28228", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=30879, name="Unknown Item 30879", score=0, rank=1, src="Hyjal"},
                {id=32346, name="Unknown Item 32346", score=0, rank=2, src="BT/Hyjal"},
                {id=30040, name="Unknown Item 30040", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=31005, name="Unknown Item 31005", score=0, rank=1, src="BT/Hyjal"},
                {id=30142, name="Unknown Item 30142", score=0, rank=2, src="BT/Hyjal"},
                {id=30898, name="Unknown Item 30898", score=0, rank=3, src="Hyjal"},
            },
            [8] = {
                {id=32366, name="Unknown Item 32366", score=0, rank=1, src="BT"},
                {id=28545, name="Unknown Item 28545", score=0, rank=2, src="Kara"},
                {id=32510, name="Unknown Item 32510", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=32324, name="Unknown Item 32324", score=0, rank=1, src="BT/Hyjal"},
                {id=29966, name="Unknown Item 29966", score=0, rank=2, src="TK"},
                {id=32251, name="Unknown Item 32251", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=31001, name="Unknown Item 31001", score=0, rank=1, src="BT/Hyjal"},
                {id=30140, name="Unknown Item 30140", score=0, rank=2, src="SSC/TK"},
                {id=27474, name="Unknown Item 27474", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=32497, name="Stormrage Signet Ring", score=129.3, rank=1, src="BT"},
                {id=29301, name="Band of the Eternal Champion", score=122.3, rank=2, src="BT/Hyjal"},
                {id=29997, name="Band of the Ranger-General", score=133.9, rank=3, src="SSC/TK"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=32505, name="Madness of the Betrayer", score=124, rank=2, src="BT"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=29994, name="Unknown Item 29994", score=0, rank=1, src="SSC/TK"},
                {id=32323, name="Unknown Item 32323", score=0, rank=2, src="BT/Hyjal"},
                {id=28672, name="Unknown Item 28672", score=0, rank=3, src="Kara"},
            },
            [18] = {
                {id=30906, name="Unknown Item 30906", score=0, rank=1, src="BT/Hyjal"},
                {id=34530, name="Unknown Item 34530", score=0, rank=2, src="BT/Hyjal"},
                {id=32336, name="Unknown Item 32336", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [4] = {
            [1] = {
                {id=32235, name="Unknown Item 32235", score=0, rank=1, src="BT"},
                {id=33666, name="Unknown Item 33666", score=0, rank=2, src="BT/Hyjal"},
                {id=31003, name="Unknown Item 31003", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=1, src="BT"},
                {id=32591, name="Choker of Serrated Blades", score=73.7, rank=2, src="BT"},
                {id=30017, name="Telonicus's Pendant of Mayhem", score=126.6, rank=3, src="SSC/TK"},
            },
            [3] = {
                {id=31006, name="Unknown Item 31006", score=0, rank=1, src="BT/Hyjal"},
                {id=30143, name="Unknown Item 30143", score=0, rank=2, src="SSC/TK"},
                {id=30892, name="Unknown Item 30892", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=31004, name="Unknown Item 31004", score=0, rank=1, src="BT/Hyjal"},
                {id=30139, name="Unknown Item 30139", score=0, rank=2, src="SSC/TK"},
                {id=28228, name="Unknown Item 28228", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=32346, name="Unknown Item 32346", score=0, rank=1, src="BT/Hyjal"},
                {id=30879, name="Unknown Item 30879", score=0, rank=2, src="Hyjal"},
                {id=33211, name="Unknown Item 33211", score=0, rank=3, src="ZA"},
            },
            [7] = {
                {id=31005, name="Unknown Item 31005", score=0, rank=1, src="BT/Hyjal"},
                {id=30142, name="Unknown Item 30142", score=0, rank=2, src="BT/Hyjal"},
                {id=30898, name="Unknown Item 30898", score=0, rank=3, src="Hyjal"},
            },
            [8] = {
                {id=32366, name="Unknown Item 32366", score=0, rank=1, src="BT"},
                {id=33222, name="Unknown Item 33222", score=0, rank=2, src="SWP"},
                {id=28545, name="Unknown Item 28545", score=0, rank=3, src="Kara"},
            },
            [9] = {
                {id=32324, name="Unknown Item 32324", score=0, rank=1, src="BT/Hyjal"},
                {id=33540, name="Unknown Item 33540", score=0, rank=2, src="ZA"},
                {id=29966, name="Unknown Item 29966", score=0, rank=3, src="TK"},
            },
            [10] = {
                {id=31001, name="Unknown Item 31001", score=0, rank=1, src="BT/Hyjal"},
                {id=30140, name="Unknown Item 30140", score=0, rank=2, src="SSC/TK"},
                {id=27474, name="Unknown Item 27474", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=33496, name="Signet of Primal Wrath", score=117, rank=1, src="ZA"},
                {id=32497, name="Stormrage Signet Ring", score=129.3, rank=2, src="BT"},
                {id=29301, name="Band of the Eternal Champion", score=122.3, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=33831, name="Berserker's Call", score=90, rank=2, src="ZA"},
                {id=32505, name="Madness of the Betrayer", score=124, rank=3, src="BT"},
            },
            [15] = {
                {id=32323, name="Unknown Item 32323", score=0, rank=1, src="BT/Hyjal"},
                {id=29994, name="Unknown Item 29994", score=0, rank=2, src="SSC/TK"},
                {id=28672, name="Unknown Item 28672", score=0, rank=3, src="Kara"},
            },
            [18] = {
                {id=30906, name="Unknown Item 30906", score=0, rank=1, src="BT/Hyjal"},
                {id=34530, name="Unknown Item 34530", score=0, rank=2, src="BT/Hyjal"},
                {id=32336, name="Unknown Item 32336", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [5] = {
            [1] = {
                {id=34333, name="Unknown Item 34333", score=0, rank=1, src="SWP"},
                {id=34244, name="Unknown Item 34244", score=0, rank=2, src="SWP"},
                {id=32235, name="Unknown Item 32235", score=0, rank=3, src="BT"},
            },
            [2] = {
                {id=34358, name="Hard Khorium Choker", score=62.2, rank=1, src="Vendor"},
                {id=34177, name="Clutch of Demise", score=117.3, rank=2, src="SWP"},
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=3, src="BT"},
            },
            [3] = {
                {id=31006, name="Unknown Item 31006", score=0, rank=1, src="BT/Hyjal"},
                {id=34194, name="Unknown Item 34194", score=0, rank=2, src="SWP"},
                {id=34195, name="Unknown Item 34195", score=0, rank=3, src="SWP"},
            },
            [5] = {
                {id=34397, name="Unknown Item 34397", score=0, rank=1, src="SWP"},
                {id=34228, name="Unknown Item 34228", score=0, rank=2, src="SWP"},
                {id=34373, name="Unknown Item 34373", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34549, name="Unknown Item 34549", score=0, rank=1, src="SWP"},
                {id=32346, name="Unknown Item 32346", score=0, rank=2, src="BT/Hyjal"},
                {id=30879, name="Unknown Item 30879", score=0, rank=3, src="Hyjal"},
            },
            [7] = {
                {id=34188, name="Unknown Item 34188", score=0, rank=1, src="SWP"},
                {id=34168, name="Unknown Item 34168", score=0, rank=2, src="SWP"},
                {id=34928, name="Unknown Item 34928", score=0, rank=3, src="SWP"},
            },
            [8] = {
                {id=34570, name="Unknown Item 34570", score=0, rank=1, src="SWP"},
                {id=32366, name="Unknown Item 32366", score=0, rank=2, src="BT"},
                {id=33222, name="Unknown Item 33222", score=0, rank=3, src="SWP"},
            },
            [9] = {
                {id=34443, name="Unknown Item 34443", score=0, rank=1, src="SWP"},
                {id=32324, name="Unknown Item 32324", score=0, rank=2, src="BT/Hyjal"},
                {id=33540, name="Unknown Item 33540", score=0, rank=3, src="ZA"},
            },
            [10] = {
                {id=34370, name="Unknown Item 34370", score=0, rank=1, src="Vendor"},
                {id=34343, name="Unknown Item 34343", score=0, rank=2, src="SWP"},
                {id=31001, name="Unknown Item 31001", score=0, rank=3, src="BT/Hyjal"},
            },
            [11] = {
                {id=34189, name="Band of Ruinous Delight", score=113.8, rank=1, src="SWP"},
                {id=34361, name="Hard Khorium Band", score=122.2, rank=2, src="SWP"},
                {id=34887, name="Angelista's Revenge", score=118.8, rank=3, src="SWP"},
            },
            [13] = {
                {id=34427, name="Blackened Naaru Sliver", score=0, rank=1, src="SWP"},
                {id=28830, name="Dragonspine Trophy", score=40, rank=2, src="Gruul"},
                {id=33831, name="Berserker's Call", score=90, rank=3, src="ZA"},
            },
            [15] = {
                {id=34241, name="Unknown Item 34241", score=0, rank=1, src="SWP"},
                {id=32323, name="Unknown Item 32323", score=0, rank=2, src="BT/Hyjal"},
                {id=29994, name="Unknown Item 29994", score=0, rank=3, src="SSC/TK"},
            },
            [18] = {
                {id=34334, name="Unknown Item 34334", score=0, rank=1, src="SWP"},
                {id=34196, name="Unknown Item 34196", score=0, rank=2, src="SWP"},
                {id=30906, name="Unknown Item 30906", score=0, rank=3, src="BT/Hyjal"},
            },
        },
    },
    ["mm_hunter"] = {
        [0] = {
            [1] = {
                {id=28275, name="Unknown Item 28275", score=0, rank=1, src="Pre-Raid"},
                {id=22438, name="Unknown Item 22438", score=0, rank=2, src="Pre-Raid"},
                {id=31109, name="Unknown Item 31109", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=29381, name="Choker of Vile Intent", score=119.8, rank=1, src="Pre-Raid"},
                {id=19377, name="Prestor's Talisman of Connivery", score=92, rank=2, src="Pre-Raid"},
                {id=28343, name="Jagged Bark Pendant", score=83.5, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=27801, name="Unknown Item 27801", score=0, rank=1, src="Pre-Raid"},
                {id=25790, name="Unknown Item 25790", score=0, rank=2, src="Pre-Raid"},
                {id=22439, name="Unknown Item 22439", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=28228, name="Unknown Item 28228", score=0, rank=1, src="Pre-Raid"},
                {id=29525, name="Unknown Item 29525", score=0, rank=2, src="Vendor"},
                {id=29515, name="Unknown Item 29515", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=29526, name="Unknown Item 29526", score=0, rank=1, src="Pre-Raid"},
                {id=27760, name="Unknown Item 27760", score=0, rank=2, src="Pre-Raid"},
                {id=29516, name="Unknown Item 29516", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=27874, name="Unknown Item 27874", score=0, rank=1, src="Pre-Raid"},
                {id=30538, name="Unknown Item 30538", score=0, rank=2, src="Slave Pens"},
                {id=27837, name="Unknown Item 27837", score=0, rank=3, src="Mana-Tombs"},
            },
            [8] = {
                {id=25686, name="Unknown Item 25686", score=0, rank=1, src="Vendor"},
                {id=31288, name="Unknown Item 31288", score=0, rank=2, src="Pre-Raid"},
                {id=22440, name="Unknown Item 22440", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=29527, name="Unknown Item 29527", score=0, rank=1, src="Pre-Raid"},
                {id=29246, name="Unknown Item 29246", score=0, rank=2, src="Black Morass"},
                {id=25697, name="Unknown Item 25697", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=27474, name="Unknown Item 27474", score=0, rank=1, src="Pre-Raid"},
                {id=30951, name="Unknown Item 30951", score=0, rank=2, src="Pre-Raid"},
                {id=22441, name="Unknown Item 22441", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=30860, name="Kaylaan's Signet", score=100, rank=1, src="Pre-Raid"},
                {id=31077, name="Unknown Item 31077", score=0, rank=2, src="Pre-Raid"},
                {id=27925, name="Ravenclaw Band", score=97.5, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=29383, name="Bloodlust Brooch", score=72, rank=1, src="Kara/T4"},
                {id=28288, name="Abacus of Violent Odds", score=64, rank=2, src="ZA"},
                {id=28034, name="Hourglass of the Unraveller", score=44.8, rank=3, src="Black Morass"},
            },
            [15] = {
                {id=24259, name="Unknown Item 24259", score=0, rank=1, src="Vendor"},
                {id=29382, name="Unknown Item 29382", score=0, rank=2, src="Pre-Raid"},
                {id=31255, name="Unknown Item 31255", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [1] = {
            [1] = {
                {id=28275, name="Unknown Item 28275", score=0, rank=1, src="Pre-Raid"},
                {id=29081, name="Unknown Item 29081", score=0, rank=2, src="Kara/T4"},
                {id=31109, name="Unknown Item 31109", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=29381, name="Choker of Vile Intent", score=119.8, rank=1, src="Pre-Raid"},
                {id=28509, name="Worgen Claw Necklace", score=118.1, rank=2, src="Kara"},
                {id=28674, name="Saberclaw Talisman", score=91.3, rank=3, src="Kara"},
            },
            [3] = {
                {id=27801, name="Unknown Item 27801", score=0, rank=1, src="Pre-Raid"},
                {id=25790, name="Unknown Item 25790", score=0, rank=2, src="Pre-Raid"},
                {id=27797, name="Unknown Item 27797", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=28228, name="Unknown Item 28228", score=0, rank=1, src="Pre-Raid"},
                {id=29525, name="Unknown Item 29525", score=0, rank=2, src="Vendor"},
                {id=29515, name="Unknown Item 29515", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=28828, name="Unknown Item 28828", score=0, rank=1, src="Kara/T4"},
                {id=29247, name="Unknown Item 29247", score=0, rank=2, src="Kara/T4"},
                {id=29526, name="Unknown Item 29526", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=30739, name="Unknown Item 30739", score=0, rank=1, src="Kara/T4"},
                {id=28741, name="Unknown Item 28741", score=0, rank=2, src="Kara"},
                {id=27874, name="Unknown Item 27874", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=28545, name="Unknown Item 28545", score=0, rank=1, src="Kara"},
                {id=25686, name="Unknown Item 25686", score=0, rank=2, src="Vendor"},
                {id=28746, name="Unknown Item 28746", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=29527, name="Unknown Item 29527", score=0, rank=1, src="Pre-Raid"},
                {id=29246, name="Unknown Item 29246", score=0, rank=2, src="Black Morass"},
                {id=25697, name="Unknown Item 25697", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=27474, name="Unknown Item 27474", score=0, rank=1, src="Pre-Raid"},
                {id=28506, name="Unknown Item 28506", score=0, rank=2, src="Kara"},
                {id=28827, name="Unknown Item 28827", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=28791, name="Ring of the Recalcitrant", score=104.7, rank=1, src="Kara/T4"},
                {id=28757, name="Ring of a Thousand Marks", score=116.3, rank=2, src="Kara/T4"},
                {id=28649, name="Garona's Signet Ring", score=118.5, rank=3, src="Kara"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=2, src="Kara/T4"},
                {id=28034, name="Hourglass of the Unraveller", score=44.8, rank=3, src="Black Morass"},
            },
            [15] = {
                {id=24259, name="Unknown Item 24259", score=0, rank=1, src="Vendor"},
                {id=29382, name="Unknown Item 29382", score=0, rank=2, src="Pre-Raid"},
                {id=28777, name="Unknown Item 28777", score=0, rank=3, src="Kara/T4"},
            },
        },
        [2] = {
            [1] = {
                {id=30141, name="Unknown Item 30141", score=0, rank=1, src="SSC/TK"},
                {id=28275, name="Unknown Item 28275", score=0, rank=2, src="Pre-Raid"},
                {id=32474, name="Unknown Item 32474", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=30017, name="Telonicus's Pendant of Mayhem", score=126.6, rank=1, src="SSC/TK"},
                {id=30059, name="Choker of Animalistic Fury", score=98.6, rank=2, src="SSC/TK"},
                {id=28674, name="Saberclaw Talisman", score=91.3, rank=3, src="Kara"},
            },
            [3] = {
                {id=30143, name="Unknown Item 30143", score=0, rank=1, src="SSC/TK"},
                {id=27801, name="Unknown Item 27801", score=0, rank=2, src="Pre-Raid"},
                {id=30055, name="Unknown Item 30055", score=0, rank=3, src="SSC"},
            },
            [5] = {
                {id=30139, name="Unknown Item 30139", score=0, rank=1, src="SSC/TK"},
                {id=28228, name="Unknown Item 28228", score=0, rank=2, src="Pre-Raid"},
                {id=30054, name="Unknown Item 30054", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=30040, name="Unknown Item 30040", score=0, rank=1, src="Vendor"},
                {id=30046, name="Unknown Item 30046", score=0, rank=2, src="SSC/TK"},
                {id=30106, name="Unknown Item 30106", score=0, rank=3, src="SSC"},
            },
            [7] = {
                {id=29995, name="Unknown Item 29995", score=0, rank=1, src="SSC/TK"},
                {id=29985, name="Unknown Item 29985", score=0, rank=2, src="SSC/TK"},
                {id=30739, name="Unknown Item 30739", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=30104, name="Unknown Item 30104", score=0, rank=1, src="SSC/TK"},
                {id=29951, name="Unknown Item 29951", score=0, rank=2, src="SSC/TK"},
                {id=30060, name="Unknown Item 30060", score=0, rank=3, src="SSC/TK"},
            },
            [9] = {
                {id=29966, name="Unknown Item 29966", score=0, rank=1, src="TK"},
                {id=30026, name="Unknown Item 30026", score=0, rank=2, src="SSC/TK"},
                {id=30091, name="Unknown Item 30091", score=0, rank=3, src="SSC/TK"},
            },
            [10] = {
                {id=30140, name="Unknown Item 30140", score=0, rank=1, src="SSC/TK"},
                {id=27474, name="Unknown Item 27474", score=0, rank=2, src="Pre-Raid"},
                {id=28506, name="Unknown Item 28506", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=28791, name="Ring of the Recalcitrant", score=104.7, rank=1, src="Kara/T4"},
                {id=29997, name="Band of the Ranger-General", score=133.9, rank=2, src="SSC/TK"},
                {id=30052, name="Ring of Lethality", score=137.9, rank=3, src="SSC"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=2, src="Kara/T4"},
                {id=28288, name="Abacus of Violent Odds", score=64, rank=3, src="ZA"},
            },
            [15] = {
                {id=29994, name="Unknown Item 29994", score=0, rank=1, src="SSC/TK"},
                {id=24259, name="Unknown Item 24259", score=0, rank=2, src="Vendor"},
                {id=29382, name="Unknown Item 29382", score=0, rank=3, src="Pre-Raid"},
            },
            [16] = {
                {id=32944, name="Unknown Item 32944", score=0, rank=1, src="SSC/TK"},
                {id=29948, name="Unknown Item 29948", score=0, rank=2, src="SSC/TK"},
                {id=27846, name="Unknown Item 27846", score=0, rank=3, src="Kara/T4"},
            },
            [18] = {
                {id=30105, name="Unknown Item 30105", score=0, rank=1, src="SSC/TK"},
                {id=31986, name="Unknown Item 31986", score=0, rank=2, src="SSC/TK"},
                {id=28772, name="Unknown Item 28772", score=0, rank=3, src="Kara/T4"},
            },
        },
        [3] = {
            [1] = {
                {id=32235, name="Unknown Item 32235", score=0, rank=1, src="BT"},
                {id=33666, name="Unknown Item 33666", score=0, rank=2, src="BT/Hyjal"},
                {id=31003, name="Unknown Item 31003", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=32591, name="Choker of Serrated Blades", score=73.7, rank=1, src="BT"},
                {id=30017, name="Telonicus's Pendant of Mayhem", score=126.6, rank=2, src="SSC/TK"},
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=3, src="BT"},
            },
            [3] = {
                {id=31006, name="Unknown Item 31006", score=0, rank=1, src="BT/Hyjal"},
                {id=30143, name="Unknown Item 30143", score=0, rank=2, src="SSC/TK"},
                {id=30892, name="Unknown Item 30892", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=31004, name="Unknown Item 31004", score=0, rank=1, src="BT/Hyjal"},
                {id=30139, name="Unknown Item 30139", score=0, rank=2, src="SSC/TK"},
                {id=28228, name="Unknown Item 28228", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=30879, name="Unknown Item 30879", score=0, rank=1, src="Hyjal"},
                {id=32346, name="Unknown Item 32346", score=0, rank=2, src="BT/Hyjal"},
                {id=30040, name="Unknown Item 30040", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=31005, name="Unknown Item 31005", score=0, rank=1, src="BT/Hyjal"},
                {id=30142, name="Unknown Item 30142", score=0, rank=2, src="BT/Hyjal"},
                {id=30898, name="Unknown Item 30898", score=0, rank=3, src="Hyjal"},
            },
            [8] = {
                {id=32366, name="Unknown Item 32366", score=0, rank=1, src="BT"},
                {id=28545, name="Unknown Item 28545", score=0, rank=2, src="Kara"},
                {id=32510, name="Unknown Item 32510", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=32324, name="Unknown Item 32324", score=0, rank=1, src="BT/Hyjal"},
                {id=29966, name="Unknown Item 29966", score=0, rank=2, src="TK"},
                {id=32251, name="Unknown Item 32251", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=31001, name="Unknown Item 31001", score=0, rank=1, src="BT/Hyjal"},
                {id=30140, name="Unknown Item 30140", score=0, rank=2, src="SSC/TK"},
                {id=27474, name="Unknown Item 27474", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=32497, name="Stormrage Signet Ring", score=129.3, rank=1, src="BT"},
                {id=29301, name="Band of the Eternal Champion", score=122.3, rank=2, src="BT/Hyjal"},
                {id=29997, name="Band of the Ranger-General", score=133.9, rank=3, src="SSC/TK"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=32505, name="Madness of the Betrayer", score=124, rank=2, src="BT"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=29994, name="Unknown Item 29994", score=0, rank=1, src="SSC/TK"},
                {id=32323, name="Unknown Item 32323", score=0, rank=2, src="BT/Hyjal"},
                {id=28672, name="Unknown Item 28672", score=0, rank=3, src="Kara"},
            },
            [18] = {
                {id=30906, name="Unknown Item 30906", score=0, rank=1, src="BT/Hyjal"},
                {id=34530, name="Unknown Item 34530", score=0, rank=2, src="BT/Hyjal"},
                {id=32336, name="Unknown Item 32336", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [4] = {
            [1] = {
                {id=32235, name="Unknown Item 32235", score=0, rank=1, src="BT"},
                {id=33666, name="Unknown Item 33666", score=0, rank=2, src="BT/Hyjal"},
                {id=31003, name="Unknown Item 31003", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=1, src="BT"},
                {id=32591, name="Choker of Serrated Blades", score=73.7, rank=2, src="BT"},
                {id=30017, name="Telonicus's Pendant of Mayhem", score=126.6, rank=3, src="SSC/TK"},
            },
            [3] = {
                {id=31006, name="Unknown Item 31006", score=0, rank=1, src="BT/Hyjal"},
                {id=30143, name="Unknown Item 30143", score=0, rank=2, src="SSC/TK"},
                {id=30892, name="Unknown Item 30892", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=31004, name="Unknown Item 31004", score=0, rank=1, src="BT/Hyjal"},
                {id=30139, name="Unknown Item 30139", score=0, rank=2, src="SSC/TK"},
                {id=28228, name="Unknown Item 28228", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=32346, name="Unknown Item 32346", score=0, rank=1, src="BT/Hyjal"},
                {id=30879, name="Unknown Item 30879", score=0, rank=2, src="Hyjal"},
                {id=33211, name="Unknown Item 33211", score=0, rank=3, src="ZA"},
            },
            [7] = {
                {id=31005, name="Unknown Item 31005", score=0, rank=1, src="BT/Hyjal"},
                {id=30142, name="Unknown Item 30142", score=0, rank=2, src="BT/Hyjal"},
                {id=30898, name="Unknown Item 30898", score=0, rank=3, src="Hyjal"},
            },
            [8] = {
                {id=32366, name="Unknown Item 32366", score=0, rank=1, src="BT"},
                {id=33222, name="Unknown Item 33222", score=0, rank=2, src="SWP"},
                {id=28545, name="Unknown Item 28545", score=0, rank=3, src="Kara"},
            },
            [9] = {
                {id=32324, name="Unknown Item 32324", score=0, rank=1, src="BT/Hyjal"},
                {id=33540, name="Unknown Item 33540", score=0, rank=2, src="ZA"},
                {id=29966, name="Unknown Item 29966", score=0, rank=3, src="TK"},
            },
            [10] = {
                {id=31001, name="Unknown Item 31001", score=0, rank=1, src="BT/Hyjal"},
                {id=30140, name="Unknown Item 30140", score=0, rank=2, src="SSC/TK"},
                {id=27474, name="Unknown Item 27474", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=33496, name="Signet of Primal Wrath", score=117, rank=1, src="ZA"},
                {id=32497, name="Stormrage Signet Ring", score=129.3, rank=2, src="BT"},
                {id=29301, name="Band of the Eternal Champion", score=122.3, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=33831, name="Berserker's Call", score=90, rank=2, src="ZA"},
                {id=32505, name="Madness of the Betrayer", score=124, rank=3, src="BT"},
            },
            [15] = {
                {id=32323, name="Unknown Item 32323", score=0, rank=1, src="BT/Hyjal"},
                {id=29994, name="Unknown Item 29994", score=0, rank=2, src="SSC/TK"},
                {id=28672, name="Unknown Item 28672", score=0, rank=3, src="Kara"},
            },
            [18] = {
                {id=30906, name="Unknown Item 30906", score=0, rank=1, src="BT/Hyjal"},
                {id=34530, name="Unknown Item 34530", score=0, rank=2, src="BT/Hyjal"},
                {id=32336, name="Unknown Item 32336", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [5] = {
            [1] = {
                {id=34333, name="Unknown Item 34333", score=0, rank=1, src="SWP"},
                {id=34244, name="Unknown Item 34244", score=0, rank=2, src="SWP"},
                {id=32235, name="Unknown Item 32235", score=0, rank=3, src="BT"},
            },
            [2] = {
                {id=34358, name="Hard Khorium Choker", score=62.2, rank=1, src="Vendor"},
                {id=34177, name="Clutch of Demise", score=117.3, rank=2, src="SWP"},
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=3, src="BT"},
            },
            [3] = {
                {id=31006, name="Unknown Item 31006", score=0, rank=1, src="BT/Hyjal"},
                {id=34194, name="Unknown Item 34194", score=0, rank=2, src="SWP"},
                {id=34195, name="Unknown Item 34195", score=0, rank=3, src="SWP"},
            },
            [5] = {
                {id=34397, name="Unknown Item 34397", score=0, rank=1, src="SWP"},
                {id=34228, name="Unknown Item 34228", score=0, rank=2, src="SWP"},
                {id=34373, name="Unknown Item 34373", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34549, name="Unknown Item 34549", score=0, rank=1, src="SWP"},
                {id=32346, name="Unknown Item 32346", score=0, rank=2, src="BT/Hyjal"},
                {id=30879, name="Unknown Item 30879", score=0, rank=3, src="Hyjal"},
            },
            [7] = {
                {id=34188, name="Unknown Item 34188", score=0, rank=1, src="SWP"},
                {id=34168, name="Unknown Item 34168", score=0, rank=2, src="SWP"},
                {id=34928, name="Unknown Item 34928", score=0, rank=3, src="SWP"},
            },
            [8] = {
                {id=34570, name="Unknown Item 34570", score=0, rank=1, src="SWP"},
                {id=32366, name="Unknown Item 32366", score=0, rank=2, src="BT"},
                {id=33222, name="Unknown Item 33222", score=0, rank=3, src="SWP"},
            },
            [9] = {
                {id=34443, name="Unknown Item 34443", score=0, rank=1, src="SWP"},
                {id=32324, name="Unknown Item 32324", score=0, rank=2, src="BT/Hyjal"},
                {id=33540, name="Unknown Item 33540", score=0, rank=3, src="ZA"},
            },
            [10] = {
                {id=34370, name="Unknown Item 34370", score=0, rank=1, src="Vendor"},
                {id=34343, name="Unknown Item 34343", score=0, rank=2, src="SWP"},
                {id=31001, name="Unknown Item 31001", score=0, rank=3, src="BT/Hyjal"},
            },
            [11] = {
                {id=34189, name="Band of Ruinous Delight", score=113.8, rank=1, src="SWP"},
                {id=34361, name="Hard Khorium Band", score=122.2, rank=2, src="SWP"},
                {id=34887, name="Angelista's Revenge", score=118.8, rank=3, src="SWP"},
            },
            [13] = {
                {id=34427, name="Blackened Naaru Sliver", score=0, rank=1, src="SWP"},
                {id=28830, name="Dragonspine Trophy", score=40, rank=2, src="Gruul"},
                {id=33831, name="Berserker's Call", score=90, rank=3, src="ZA"},
            },
            [15] = {
                {id=34241, name="Unknown Item 34241", score=0, rank=1, src="SWP"},
                {id=32323, name="Unknown Item 32323", score=0, rank=2, src="BT/Hyjal"},
                {id=29994, name="Unknown Item 29994", score=0, rank=3, src="SSC/TK"},
            },
            [18] = {
                {id=34334, name="Unknown Item 34334", score=0, rank=1, src="SWP"},
                {id=34196, name="Unknown Item 34196", score=0, rank=2, src="SWP"},
                {id=30906, name="Unknown Item 30906", score=0, rank=3, src="BT/Hyjal"},
            },
        },
    },
    ["surv_hunter"] = {
        [0] = {
            [1] = {
                {id=28275, name="Unknown Item 28275", score=0, rank=1, src="Pre-Raid"},
                {id=22438, name="Unknown Item 22438", score=0, rank=2, src="Pre-Raid"},
                {id=31109, name="Unknown Item 31109", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=29381, name="Choker of Vile Intent", score=119.8, rank=1, src="Pre-Raid"},
                {id=19377, name="Prestor's Talisman of Connivery", score=92, rank=2, src="Pre-Raid"},
                {id=28343, name="Jagged Bark Pendant", score=83.5, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=27801, name="Unknown Item 27801", score=0, rank=1, src="Pre-Raid"},
                {id=25790, name="Unknown Item 25790", score=0, rank=2, src="Pre-Raid"},
                {id=22439, name="Unknown Item 22439", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=28228, name="Unknown Item 28228", score=0, rank=1, src="Pre-Raid"},
                {id=29525, name="Unknown Item 29525", score=0, rank=2, src="Vendor"},
                {id=29515, name="Unknown Item 29515", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=29526, name="Unknown Item 29526", score=0, rank=1, src="Pre-Raid"},
                {id=27760, name="Unknown Item 27760", score=0, rank=2, src="Pre-Raid"},
                {id=29516, name="Unknown Item 29516", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=27874, name="Unknown Item 27874", score=0, rank=1, src="Pre-Raid"},
                {id=30538, name="Unknown Item 30538", score=0, rank=2, src="Slave Pens"},
                {id=27837, name="Unknown Item 27837", score=0, rank=3, src="Mana-Tombs"},
            },
            [8] = {
                {id=25686, name="Unknown Item 25686", score=0, rank=1, src="Vendor"},
                {id=31288, name="Unknown Item 31288", score=0, rank=2, src="Pre-Raid"},
                {id=22440, name="Unknown Item 22440", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=29527, name="Unknown Item 29527", score=0, rank=1, src="Pre-Raid"},
                {id=29246, name="Unknown Item 29246", score=0, rank=2, src="Black Morass"},
                {id=25697, name="Unknown Item 25697", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=27474, name="Unknown Item 27474", score=0, rank=1, src="Pre-Raid"},
                {id=30951, name="Unknown Item 30951", score=0, rank=2, src="Pre-Raid"},
                {id=22441, name="Unknown Item 22441", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=30860, name="Kaylaan's Signet", score=100, rank=1, src="Pre-Raid"},
                {id=31077, name="Unknown Item 31077", score=0, rank=2, src="Pre-Raid"},
                {id=27925, name="Ravenclaw Band", score=97.5, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=29383, name="Bloodlust Brooch", score=72, rank=1, src="Kara/T4"},
                {id=28288, name="Abacus of Violent Odds", score=64, rank=2, src="ZA"},
                {id=28034, name="Hourglass of the Unraveller", score=44.8, rank=3, src="Black Morass"},
            },
            [15] = {
                {id=24259, name="Unknown Item 24259", score=0, rank=1, src="Vendor"},
                {id=29382, name="Unknown Item 29382", score=0, rank=2, src="Pre-Raid"},
                {id=31255, name="Unknown Item 31255", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [1] = {
            [1] = {
                {id=28275, name="Unknown Item 28275", score=0, rank=1, src="Pre-Raid"},
                {id=29081, name="Unknown Item 29081", score=0, rank=2, src="Kara/T4"},
                {id=31109, name="Unknown Item 31109", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=28343, name="Jagged Bark Pendant", score=83.5, rank=1, src="Pre-Raid"},
                {id=28674, name="Saberclaw Talisman", score=91.3, rank=2, src="Kara"},
                {id=19377, name="Prestor's Talisman of Connivery", score=92, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=27801, name="Unknown Item 27801", score=0, rank=1, src="Pre-Raid"},
                {id=25790, name="Unknown Item 25790", score=0, rank=2, src="Pre-Raid"},
                {id=27797, name="Unknown Item 27797", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=28228, name="Unknown Item 28228", score=0, rank=1, src="Pre-Raid"},
                {id=29525, name="Unknown Item 29525", score=0, rank=2, src="Vendor"},
                {id=29515, name="Unknown Item 29515", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=30677, name="Unknown Item 30677", score=0, rank=1, src="Kara/T4"},
                {id=28750, name="Unknown Item 28750", score=0, rank=2, src="Kara"},
                {id=29247, name="Unknown Item 29247", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=30739, name="Unknown Item 30739", score=0, rank=1, src="Kara/T4"},
                {id=28741, name="Unknown Item 28741", score=0, rank=2, src="Kara"},
                {id=27874, name="Unknown Item 27874", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=30682, name="Unknown Item 30682", score=0, rank=1, src="Kara/T4"},
                {id=28545, name="Unknown Item 28545", score=0, rank=2, src="Kara"},
                {id=28746, name="Unknown Item 28746", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=30686, name="Unknown Item 30686", score=0, rank=1, src="Kara/T4"},
                {id=29246, name="Unknown Item 29246", score=0, rank=2, src="Black Morass"},
                {id=29527, name="Unknown Item 29527", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=27474, name="Unknown Item 27474", score=0, rank=1, src="Pre-Raid"},
                {id=28506, name="Unknown Item 28506", score=0, rank=2, src="Kara"},
                {id=28827, name="Unknown Item 28827", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=28791, name="Ring of the Recalcitrant", score=104.7, rank=1, src="Kara/T4"},
                {id=31277, name="Pathfinder's Band", score=84, rank=2, src="Kara/T4"},
                {id=28649, name="Garona's Signet Ring", score=118.5, rank=3, src="Kara"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=2, src="Kara/T4"},
                {id=28034, name="Hourglass of the Unraveller", score=44.8, rank=3, src="Black Morass"},
            },
            [15] = {
                {id=28672, name="Unknown Item 28672", score=0, rank=1, src="Kara"},
                {id=29382, name="Unknown Item 29382", score=0, rank=2, src="Pre-Raid"},
                {id=24259, name="Unknown Item 24259", score=0, rank=3, src="Vendor"},
            },
        },
        [2] = {
            [1] = {
                {id=30141, name="Unknown Item 30141", score=0, rank=1, src="SSC/TK"},
                {id=28275, name="Unknown Item 28275", score=0, rank=2, src="Pre-Raid"},
                {id=32474, name="Unknown Item 32474", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=30017, name="Telonicus's Pendant of Mayhem", score=126.6, rank=1, src="SSC/TK"},
                {id=32508, name="Necklace of the Deep", score=44, rank=2, src="SSC/TK"},
                {id=28343, name="Jagged Bark Pendant", score=83.5, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=30143, name="Unknown Item 30143", score=0, rank=1, src="SSC/TK"},
                {id=27801, name="Unknown Item 27801", score=0, rank=2, src="Pre-Raid"},
                {id=30055, name="Unknown Item 30055", score=0, rank=3, src="SSC"},
            },
            [5] = {
                {id=30139, name="Unknown Item 30139", score=0, rank=1, src="SSC/TK"},
                {id=28228, name="Unknown Item 28228", score=0, rank=2, src="Pre-Raid"},
                {id=29525, name="Unknown Item 29525", score=0, rank=3, src="Vendor"},
            },
            [6] = {
                {id=30040, name="Unknown Item 30040", score=0, rank=1, src="Vendor"},
                {id=30677, name="Unknown Item 30677", score=0, rank=2, src="Kara/T4"},
                {id=30106, name="Unknown Item 30106", score=0, rank=3, src="SSC"},
            },
            [7] = {
                {id=30142, name="Unknown Item 30142", score=0, rank=1, src="BT/Hyjal"},
                {id=30739, name="Unknown Item 30739", score=0, rank=2, src="Kara/T4"},
                {id=29985, name="Unknown Item 29985", score=0, rank=3, src="SSC/TK"},
            },
            [8] = {
                {id=30104, name="Unknown Item 30104", score=0, rank=1, src="SSC/TK"},
                {id=29951, name="Unknown Item 29951", score=0, rank=2, src="SSC/TK"},
                {id=30682, name="Unknown Item 30682", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=29966, name="Unknown Item 29966", score=0, rank=1, src="TK"},
                {id=30686, name="Unknown Item 30686", score=0, rank=2, src="Kara/T4"},
                {id=25697, name="Unknown Item 25697", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=28506, name="Unknown Item 28506", score=0, rank=1, src="Kara"},
                {id=27474, name="Unknown Item 27474", score=0, rank=2, src="Pre-Raid"},
                {id=28827, name="Unknown Item 28827", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=28791, name="Ring of the Recalcitrant", score=104.7, rank=1, src="Kara/T4"},
                {id=29298, name="Band of Eternity", score=103.7, rank=2, src="SSC/TK"},
                {id=30052, name="Ring of Lethality", score=137.9, rank=3, src="SSC"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=2, src="Kara/T4"},
                {id=28288, name="Abacus of Violent Odds", score=64, rank=3, src="ZA"},
            },
            [15] = {
                {id=29994, name="Unknown Item 29994", score=0, rank=1, src="SSC/TK"},
                {id=28672, name="Unknown Item 28672", score=0, rank=2, src="Kara"},
                {id=29382, name="Unknown Item 29382", score=0, rank=3, src="Pre-Raid"},
            },
            [18] = {
                {id=30105, name="Unknown Item 30105", score=0, rank=1, src="SSC/TK"},
                {id=29949, name="Unknown Item 29949", score=0, rank=2, src="SSC/TK"},
                {id=30724, name="Unknown Item 30724", score=0, rank=3, src="Kara/T4"},
            },
        },
        [3] = {
            [1] = {
                {id=31003, name="Unknown Item 31003", score=0, rank=1, src="BT/Hyjal"},
                {id=30141, name="Unknown Item 30141", score=0, rank=2, src="SSC/TK"},
                {id=28275, name="Unknown Item 28275", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=30017, name="Telonicus's Pendant of Mayhem", score=126.6, rank=1, src="SSC/TK"},
                {id=32508, name="Necklace of the Deep", score=44, rank=2, src="SSC/TK"},
                {id=28343, name="Jagged Bark Pendant", score=83.5, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=31006, name="Unknown Item 31006", score=0, rank=1, src="BT/Hyjal"},
                {id=30143, name="Unknown Item 30143", score=0, rank=2, src="SSC/TK"},
                {id=27801, name="Unknown Item 27801", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=31004, name="Unknown Item 31004", score=0, rank=1, src="BT/Hyjal"},
                {id=30139, name="Unknown Item 30139", score=0, rank=2, src="SSC/TK"},
                {id=28228, name="Unknown Item 28228", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=30879, name="Unknown Item 30879", score=0, rank=1, src="Hyjal"},
                {id=30046, name="Unknown Item 30046", score=0, rank=2, src="SSC/TK"},
                {id=30677, name="Unknown Item 30677", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=30900, name="Unknown Item 30900", score=0, rank=1, src="BT/Hyjal"},
                {id=31005, name="Unknown Item 31005", score=0, rank=2, src="BT/Hyjal"},
                {id=30142, name="Unknown Item 30142", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=32366, name="Unknown Item 32366", score=0, rank=1, src="BT"},
                {id=30104, name="Unknown Item 30104", score=0, rank=2, src="SSC/TK"},
                {id=29951, name="Unknown Item 29951", score=0, rank=3, src="SSC/TK"},
            },
            [9] = {
                {id=32324, name="Unknown Item 32324", score=0, rank=1, src="BT/Hyjal"},
                {id=29966, name="Unknown Item 29966", score=0, rank=2, src="TK"},
                {id=30686, name="Unknown Item 30686", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=31001, name="Unknown Item 31001", score=0, rank=1, src="BT/Hyjal"},
                {id=28506, name="Unknown Item 28506", score=0, rank=2, src="Kara"},
                {id=30140, name="Unknown Item 30140", score=0, rank=3, src="SSC/TK"},
            },
            [11] = {
                {id=28791, name="Ring of the Recalcitrant", score=104.7, rank=1, src="Kara/T4"},
                {id=29301, name="Band of the Eternal Champion", score=122.3, rank=2, src="BT/Hyjal"},
                {id=30052, name="Ring of Lethality", score=137.9, rank=3, src="SSC"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=32505, name="Madness of the Betrayer", score=124, rank=2, src="BT"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=29994, name="Unknown Item 29994", score=0, rank=1, src="SSC/TK"},
                {id=28672, name="Unknown Item 28672", score=0, rank=2, src="Kara"},
                {id=29382, name="Unknown Item 29382", score=0, rank=3, src="Pre-Raid"},
            },
            [18] = {
                {id=30906, name="Unknown Item 30906", score=0, rank=1, src="BT/Hyjal"},
                {id=34530, name="Unknown Item 34530", score=0, rank=2, src="BT/Hyjal"},
                {id=32336, name="Unknown Item 32336", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [4] = {
            [1] = {
                {id=31003, name="Unknown Item 31003", score=0, rank=1, src="BT/Hyjal"},
                {id=32235, name="Unknown Item 32235", score=0, rank=2, src="BT"},
                {id=30141, name="Unknown Item 30141", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=30017, name="Telonicus's Pendant of Mayhem", score=126.6, rank=1, src="SSC/TK"},
                {id=32508, name="Necklace of the Deep", score=44, rank=2, src="SSC/TK"},
                {id=28343, name="Jagged Bark Pendant", score=83.5, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=31006, name="Unknown Item 31006", score=0, rank=1, src="BT/Hyjal"},
                {id=30143, name="Unknown Item 30143", score=0, rank=2, src="SSC/TK"},
                {id=27801, name="Unknown Item 27801", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=31004, name="Unknown Item 31004", score=0, rank=1, src="BT/Hyjal"},
                {id=30139, name="Unknown Item 30139", score=0, rank=2, src="SSC/TK"},
                {id=28228, name="Unknown Item 28228", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=30879, name="Unknown Item 30879", score=0, rank=1, src="Hyjal"},
                {id=30046, name="Unknown Item 30046", score=0, rank=2, src="SSC/TK"},
                {id=30677, name="Unknown Item 30677", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=30900, name="Unknown Item 30900", score=0, rank=1, src="BT/Hyjal"},
                {id=31005, name="Unknown Item 31005", score=0, rank=2, src="BT/Hyjal"},
                {id=30142, name="Unknown Item 30142", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=32366, name="Unknown Item 32366", score=0, rank=1, src="BT"},
                {id=30104, name="Unknown Item 30104", score=0, rank=2, src="SSC/TK"},
                {id=29951, name="Unknown Item 29951", score=0, rank=3, src="SSC/TK"},
            },
            [9] = {
                {id=32324, name="Unknown Item 32324", score=0, rank=1, src="BT/Hyjal"},
                {id=29966, name="Unknown Item 29966", score=0, rank=2, src="TK"},
                {id=30686, name="Unknown Item 30686", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=31001, name="Unknown Item 31001", score=0, rank=1, src="BT/Hyjal"},
                {id=28506, name="Unknown Item 28506", score=0, rank=2, src="Kara"},
                {id=30140, name="Unknown Item 30140", score=0, rank=3, src="SSC/TK"},
            },
            [11] = {
                {id=33496, name="Signet of Primal Wrath", score=117, rank=1, src="ZA"},
                {id=29301, name="Band of the Eternal Champion", score=122.3, rank=2, src="BT/Hyjal"},
                {id=28791, name="Ring of the Recalcitrant", score=104.7, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=32505, name="Madness of the Betrayer", score=124, rank=2, src="BT"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=29994, name="Unknown Item 29994", score=0, rank=1, src="SSC/TK"},
                {id=28672, name="Unknown Item 28672", score=0, rank=2, src="Kara"},
                {id=29382, name="Unknown Item 29382", score=0, rank=3, src="Pre-Raid"},
            },
            [18] = {
                {id=30906, name="Unknown Item 30906", score=0, rank=1, src="BT/Hyjal"},
                {id=34530, name="Unknown Item 34530", score=0, rank=2, src="BT/Hyjal"},
                {id=32336, name="Unknown Item 32336", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [5] = {
            [1] = {
                {id=34333, name="Unknown Item 34333", score=0, rank=1, src="SWP"},
                {id=34244, name="Unknown Item 34244", score=0, rank=2, src="SWP"},
                {id=32235, name="Unknown Item 32235", score=0, rank=3, src="BT"},
            },
            [2] = {
                {id=34177, name="Clutch of Demise", score=117.3, rank=1, src="SWP"},
                {id=34358, name="Hard Khorium Choker", score=62.2, rank=2, src="Vendor"},
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=3, src="BT"},
            },
            [3] = {
                {id=31006, name="Unknown Item 31006", score=0, rank=1, src="BT/Hyjal"},
                {id=34194, name="Unknown Item 34194", score=0, rank=2, src="SWP"},
                {id=34195, name="Unknown Item 34195", score=0, rank=3, src="SWP"},
            },
            [5] = {
                {id=34397, name="Unknown Item 34397", score=0, rank=1, src="SWP"},
                {id=34228, name="Unknown Item 34228", score=0, rank=2, src="SWP"},
                {id=34373, name="Unknown Item 34373", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34549, name="Unknown Item 34549", score=0, rank=1, src="SWP"},
                {id=30879, name="Unknown Item 30879", score=0, rank=2, src="Hyjal"},
                {id=32346, name="Unknown Item 32346", score=0, rank=3, src="BT/Hyjal"},
            },
            [7] = {
                {id=34188, name="Unknown Item 34188", score=0, rank=1, src="SWP"},
                {id=34168, name="Unknown Item 34168", score=0, rank=2, src="SWP"},
                {id=34928, name="Unknown Item 34928", score=0, rank=3, src="SWP"},
            },
            [8] = {
                {id=34570, name="Unknown Item 34570", score=0, rank=1, src="SWP"},
                {id=32366, name="Unknown Item 32366", score=0, rank=2, src="BT"},
                {id=33222, name="Unknown Item 33222", score=0, rank=3, src="SWP"},
            },
            [9] = {
                {id=34443, name="Unknown Item 34443", score=0, rank=1, src="SWP"},
                {id=32324, name="Unknown Item 32324", score=0, rank=2, src="BT/Hyjal"},
                {id=33540, name="Unknown Item 33540", score=0, rank=3, src="ZA"},
            },
            [10] = {
                {id=34343, name="Unknown Item 34343", score=0, rank=1, src="SWP"},
                {id=34370, name="Unknown Item 34370", score=0, rank=2, src="Vendor"},
                {id=31001, name="Unknown Item 31001", score=0, rank=3, src="BT/Hyjal"},
            },
            [11] = {
                {id=34361, name="Hard Khorium Band", score=122.2, rank=1, src="SWP"},
                {id=34887, name="Angelista's Revenge", score=118.8, rank=2, src="SWP"},
                {id=33496, name="Signet of Primal Wrath", score=117, rank=3, src="ZA"},
            },
            [13] = {
                {id=34427, name="Blackened Naaru Sliver", score=0, rank=1, src="SWP"},
                {id=28830, name="Dragonspine Trophy", score=40, rank=2, src="Gruul"},
                {id=33831, name="Berserker's Call", score=90, rank=3, src="ZA"},
            },
            [15] = {
                {id=34241, name="Unknown Item 34241", score=0, rank=1, src="SWP"},
                {id=29994, name="Unknown Item 29994", score=0, rank=2, src="SSC/TK"},
                {id=33484, name="Unknown Item 33484", score=0, rank=3, src="ZA"},
            },
            [18] = {
                {id=34334, name="Unknown Item 34334", score=0, rank=1, src="SWP"},
                {id=34196, name="Unknown Item 34196", score=0, rank=2, src="SWP"},
                {id=30906, name="Unknown Item 30906", score=0, rank=3, src="BT/Hyjal"},
            },
        },
    },
}
for k,v in pairs(_d) do IRR_BIS_DATA[k] = v end
end
