-- BIS_Data_MAGE.lua  (Auto-generated by scripts/update-bis.ps1)
-- Generated: 2026-03-01 19:51  -- DO NOT EDIT MANUALLY
IRR_BIS_DATA = IRR_BIS_DATA or {}
do local _d = {
    ["arcane_mage"] = {
        [0] = {
            [1] = {
                {id=28193, name="Unknown Item 28193", score=0, rank=1, src="Pre-Raid"},
                {id=32089, name="Unknown Item 32089", score=0, rank=2, src="Pre-Raid"},
                {id=28415, name="Unknown Item 28415", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=28134, name="Brooch of Heightened Potential", score=58.1, rank=1, src="Shadow Lab"},
                {id=24121, name="Chain of the Twilight Owl", score=36.2, rank=2, src="Pre-Raid"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=27796, name="Unknown Item 27796", score=0, rank=1, src="Slave Pens"},
                {id=35343, name="Unknown Item 35343", score=0, rank=2, src="Pre-Raid"},
                {id=28866, name="Unknown Item 28866", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=21848, name="Unknown Item 21848", score=0, rank=1, src="Vendor"},
                {id=31340, name="Unknown Item 31340", score=0, rank=2, src="Pre-Raid"},
                {id=28191, name="Unknown Item 28191", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=21846, name="Unknown Item 21846", score=0, rank=1, src="Vendor"},
                {id=24256, name="Unknown Item 24256", score=0, rank=2, src="Vendor"},
                {id=29241, name="Unknown Item 29241", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=24262, name="Unknown Item 24262", score=0, rank=1, src="Vendor"},
                {id=30531, name="Unknown Item 30531", score=0, rank=2, src="Pre-Raid"},
                {id=28185, name="Unknown Item 28185", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=28406, name="Unknown Item 28406", score=0, rank=1, src="Arcatraz"},
                {id=28179, name="Unknown Item 28179", score=0, rank=2, src="Pre-Raid"},
                {id=28410, name="Unknown Item 28410", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=28411, name="Unknown Item 28411", score=0, rank=1, src="Pre-Raid"},
                {id=24250, name="Unknown Item 24250", score=0, rank=2, src="Vendor"},
                {id=29240, name="Unknown Item 29240", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=21847, name="Unknown Item 21847", score=0, rank=1, src="Vendor"},
                {id=29270, name="Unknown Item 29270", score=0, rank=1, src="Pre-Raid"},
                {id=31149, name="Unknown Item 31149", score=0, rank=2, src="Pre-Raid"},
            },
            [11] = {
                {id=28555, name="Seal of the Exorcist", score=44.8, rank=1, src="Pre-Raid"},
                {id=29172, name="Ashyen's Gift", score=51.2, rank=2, src="Pre-Raid"},
                {id=21709, name="Ring of the Fallen God", score=51.9, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=27683, name="Quagmirran's Eye", score=37, rank=1, src="Slave Pens"},
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=2, src="Pre-Raid"},
                {id=23207, name="Mark of the Champion", score=0, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=23050, name="Unknown Item 23050", score=0, rank=1, src="Pre-Raid"},
                {id=22731, name="Unknown Item 22731", score=0, rank=2, src="Pre-Raid"},
                {id=27981, name="Unknown Item 27981", score=0, rank=3, src="Sethekk"},
            },
        },
        [1] = {
            [1] = {
                {id=29076, name="Unknown Item 29076", score=0, rank=1, src="Kara/T4"},
                {id=28278, name="Unknown Item 28278", score=0, rank=2, src="Kara/T4"},
                {id=28415, name="Unknown Item 28415", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=28762, name="Adornment of Stolen Souls", score=66.5, rank=1, src="Kara"},
                {id=28530, name="Brooch of Unquenchable Fury", score=63.2, rank=2, src="Kara"},
                {id=24121, name="Chain of the Twilight Owl", score=36.2, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=29079, name="Unknown Item 29079", score=0, rank=1, src="Kara/T4"},
                {id=27796, name="Unknown Item 27796", score=0, rank=2, src="Slave Pens"},
                {id=27994, name="Unknown Item 27994", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=21848, name="Unknown Item 21848", score=0, rank=1, src="Vendor"},
                {id=28602, name="Unknown Item 28602", score=0, rank=2, src="Kara/T4"},
                {id=31340, name="Unknown Item 31340", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=21846, name="Unknown Item 21846", score=0, rank=1, src="Vendor"},
                {id=28799, name="Unknown Item 28799", score=0, rank=2, src="Gruul"},
                {id=24256, name="Unknown Item 24256", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=29078, name="Unknown Item 29078", score=0, rank=1, src="Kara/T4"},
                {id=28594, name="Unknown Item 28594", score=0, rank=2, src="Kara"},
                {id=30734, name="Unknown Item 30734", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=28517, name="Unknown Item 28517", score=0, rank=1, src="Kara"},
                {id=28585, name="Unknown Item 28585", score=0, rank=2, src="Kara"},
                {id=28410, name="Unknown Item 28410", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=28411, name="Unknown Item 28411", score=0, rank=1, src="Pre-Raid"},
                {id=24250, name="Unknown Item 24250", score=0, rank=2, src="Vendor"},
                {id=28515, name="Unknown Item 28515", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=21847, name="Unknown Item 21847", score=0, rank=1, src="Vendor"},
                {id=28780, name="Unknown Item 28780", score=0, rank=2, src="Kara/T4"},
                {id=29080, name="Unknown Item 29080", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=28793, name="Band of Crimson Fury", score=67, rank=1, src="Kara/T4"},
                {id=29287, name="Violet Signet of the Archmage", score=65.1, rank=2, src="Kara"},
                {id=28753, name="Ring of Recurrence", score=62.6, rank=3, src="Kara"},
            },
            [13] = {
                {id=28785, name="The Lightning Capacitor", score=0, rank=1, src="Kara/T4"},
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=2, src="Pre-Raid"},
                {id=23207, name="Mark of the Champion", score=0, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=28797, name="Unknown Item 28797", score=0, rank=1, src="Gruul"},
                {id=28766, name="Unknown Item 28766", score=0, rank=2, src="Kara"},
                {id=30735, name="Unknown Item 30735", score=0, rank=3, src="Kara/T4"},
            },
        },
        [2] = {
            [1] = {
                {id=30206, name="Unknown Item 30206", score=0, rank=1, src="SSC/TK"},
                {id=29076, name="Unknown Item 29076", score=0, rank=2, src="Kara/T4"},
                {id=32494, name="Unknown Item 32494", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=30015, name="The Sun King's Talisman", score=77.6, rank=1, src="SSC/TK"},
                {id=28762, name="Adornment of Stolen Souls", score=66.5, rank=2, src="Kara"},
                {id=33067, name="Veteran's Pendant of Conquest", score=49.5, rank=3, src="SSC/TK"},
            },
            [3] = {
                {id=30210, name="Unknown Item 30210", score=0, rank=1, src="SSC/TK"},
                {id=29079, name="Unknown Item 29079", score=0, rank=2, src="Kara/T4"},
                {id=30079, name="Unknown Item 30079", score=0, rank=3, src="SSC"},
            },
            [5] = {
                {id=30196, name="Unknown Item 30196", score=0, rank=1, src="SSC/TK"},
                {id=30107, name="Unknown Item 30107", score=0, rank=2, src="SSC"},
                {id=30056, name="Unknown Item 30056", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=30064, name="Unknown Item 30064", score=0, rank=1, src="SSC"},
                {id=30038, name="Unknown Item 30038", score=0, rank=2, src="Vendor"},
                {id=21846, name="Unknown Item 21846", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=30207, name="Unknown Item 30207", score=0, rank=1, src="SSC/TK"},
                {id=29972, name="Unknown Item 29972", score=0, rank=2, src="SSC/TK"},
                {id=29078, name="Unknown Item 29078", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=30067, name="Unknown Item 30067", score=0, rank=1, src="SSC"},
                {id=28517, name="Unknown Item 28517", score=0, rank=2, src="Kara"},
                {id=30037, name="Unknown Item 30037", score=0, rank=3, src="Vendor"},
            },
            [9] = {
                {id=29918, name="Unknown Item 29918", score=0, rank=1, src="TK"},
                {id=32820, name="Unknown Item 32820", score=0, rank=2, src="SSC/TK"},
                {id=28411, name="Unknown Item 28411", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=29987, name="Unknown Item 29987", score=0, rank=1, src="SSC/TK"},
                {id=30205, name="Unknown Item 30205", score=0, rank=2, src="SSC/TK"},
                {id=28780, name="Unknown Item 28780", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=29302, name="Band of Eternity", score=67.9, rank=1, src="SSC/TK"},
                {id=29287, name="Violet Signet of the Archmage", score=65.1, rank=2, src="Kara"},
                {id=29922, name="Band of Al'ar", score=57.8, rank=3, src="SSC/TK"},
            },
            [13] = {
                {id=30720, name="Serpent-Coil Braid", score=41.4, rank=1, src="SSC/TK"},
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=2, src="Pre-Raid"},
                {id=28785, name="The Lightning Capacitor", score=0, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=29992, name="Unknown Item 29992", score=0, rank=1, src="SSC/TK"},
                {id=28797, name="Unknown Item 28797", score=0, rank=2, src="Gruul"},
                {id=30735, name="Unknown Item 30735", score=0, rank=3, src="Kara/T4"},
            },
        },
        [3] = {
            [1] = {
                {id=30206, name="Unknown Item 30206", score=0, rank=1, src="SSC/TK"},
                {id=32525, name="Unknown Item 32525", score=0, rank=2, src="BT"},
                {id=31056, name="Unknown Item 31056", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=30015, name="The Sun King's Talisman", score=77.6, rank=1, src="SSC/TK"},
                {id=24116, name="Eye of the Night", score=42.6, rank=2, src="Vendor"},
                {id=24121, name="Chain of the Twilight Owl", score=36.2, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=30210, name="Unknown Item 30210", score=0, rank=1, src="SSC/TK"},
                {id=32587, name="Unknown Item 32587", score=0, rank=2, src="BT/Hyjal"},
                {id=29079, name="Unknown Item 29079", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=30196, name="Unknown Item 30196", score=0, rank=1, src="SSC/TK"},
                {id=31057, name="Unknown Item 31057", score=0, rank=2, src="BT/Hyjal"},
                {id=29077, name="Unknown Item 29077", score=0, rank=3, src="BT/Hyjal"},
            },
            [6] = {
                {id=30888, name="Unknown Item 30888", score=0, rank=1, src="Hyjal"},
                {id=32256, name="Unknown Item 32256", score=0, rank=2, src="BT/Hyjal"},
                {id=30038, name="Unknown Item 30038", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=31058, name="Unknown Item 31058", score=0, rank=1, src="BT/Hyjal"},
                {id=30916, name="Unknown Item 30916", score=0, rank=2, src="Hyjal"},
                {id=30207, name="Unknown Item 30207", score=0, rank=3, src="SSC/TK"},
            },
            [8] = {
                {id=32239, name="Unknown Item 32239", score=0, rank=1, src="BT"},
                {id=30067, name="Unknown Item 30067", score=0, rank=2, src="SSC"},
                {id=30894, name="Unknown Item 30894", score=0, rank=3, src="Hyjal"},
            },
            [9] = {
                {id=30870, name="Unknown Item 30870", score=0, rank=1, src="BT/Hyjal"},
                {id=32586, name="Unknown Item 32586", score=0, rank=2, src="Vendor"},
                {id=33913, name="Unknown Item 33913", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=30205, name="Unknown Item 30205", score=0, rank=1, src="SSC/TK"},
                {id=31055, name="Unknown Item 31055", score=0, rank=2, src="BT/Hyjal"},
                {id=29987, name="Unknown Item 29987", score=0, rank=3, src="SSC/TK"},
            },
            [11] = {
                {id=29305, name="Band of the Eternal Sage", score=78.4, rank=1, src="BT/Hyjal"},
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=2, src="BT"},
                {id=29287, name="Violet Signet of the Archmage", score=65.1, rank=3, src="Kara"},
            },
            [13] = {
                {id=30720, name="Serpent-Coil Braid", score=41.4, rank=1, src="SSC/TK"},
                {id=32483, name="The Skull of Gul'dan", score=85, rank=2, src="BT"},
                {id=32488, name="Ashtongue Talisman of Insight", score=0, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32331, name="Unknown Item 32331", score=0, rank=1, src="BT"},
                {id=32524, name="Unknown Item 32524", score=0, rank=2, src="BT"},
                {id=29992, name="Unknown Item 29992", score=0, rank=3, src="SSC/TK"},
            },
        },
        [4] = {
            [1] = {
                {id=30206, name="Unknown Item 30206", score=0, rank=1, src="SSC/TK"},
                {id=32525, name="Unknown Item 32525", score=0, rank=2, src="BT"},
                {id=31056, name="Unknown Item 31056", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=33281, name="Brooch of Nature's Mercy", score=44.2, rank=1, src="ZA"},
                {id=24116, name="Eye of the Night", score=42.6, rank=2, src="Vendor"},
                {id=24121, name="Chain of the Twilight Owl", score=36.2, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=30210, name="Unknown Item 30210", score=0, rank=1, src="SSC/TK"},
                {id=32587, name="Unknown Item 32587", score=0, rank=2, src="BT/Hyjal"},
                {id=33489, name="Unknown Item 33489", score=0, rank=3, src="ZA"},
            },
            [5] = {
                {id=30196, name="Unknown Item 30196", score=0, rank=1, src="SSC/TK"},
                {id=31057, name="Unknown Item 31057", score=0, rank=2, src="BT/Hyjal"},
                {id=30913, name="Unknown Item 30913", score=0, rank=3, src="ZA"},
            },
            [6] = {
                {id=30888, name="Unknown Item 30888", score=0, rank=1, src="Hyjal"},
                {id=32256, name="Unknown Item 32256", score=0, rank=2, src="BT/Hyjal"},
                {id=30038, name="Unknown Item 30038", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=30916, name="Unknown Item 30916", score=0, rank=1, src="Hyjal"},
                {id=31058, name="Unknown Item 31058", score=0, rank=2, src="BT/Hyjal"},
                {id=30207, name="Unknown Item 30207", score=0, rank=3, src="SSC/TK"},
            },
            [8] = {
                {id=32239, name="Unknown Item 32239", score=0, rank=1, src="BT"},
                {id=33357, name="Unknown Item 33357", score=0, rank=2, src="ZA"},
                {id=30894, name="Unknown Item 30894", score=0, rank=3, src="Hyjal"},
            },
            [9] = {
                {id=30870, name="Unknown Item 30870", score=0, rank=1, src="BT/Hyjal"},
                {id=32586, name="Unknown Item 32586", score=0, rank=2, src="Vendor"},
                {id=33588, name="Unknown Item 33588", score=0, rank=3, src="ZA"},
            },
            [10] = {
                {id=30205, name="Unknown Item 30205", score=0, rank=1, src="SSC/TK"},
                {id=31055, name="Unknown Item 31055", score=0, rank=2, src="BT/Hyjal"},
                {id=33586, name="Unknown Item 33586", score=0, rank=3, src="ZA"},
            },
            [11] = {
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=1, src="BT"},
                {id=33497, name="Mana Attuned Band", score=70.8, rank=2, src="ZA"},
                {id=29305, name="Band of the Eternal Sage", score=78.4, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=32483, name="The Skull of Gul'dan", score=85, rank=1, src="BT"},
                {id=33829, name="Hex Shrunken Head", score=53, rank=2, src="ZA"},
                {id=32488, name="Ashtongue Talisman of Insight", score=0, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=32331, name="Unknown Item 32331", score=0, rank=2, src="BT"},
                {id=33591, name="Unknown Item 33591", score=0, rank=3, src="ZA"},
            },
        },
        [5] = {
            [1] = {
                {id=30206, name="Unknown Item 30206", score=0, rank=1, src="SSC/TK"},
                {id=34340, name="Unknown Item 34340", score=0, rank=2, src="SWP"},
                {id=34847, name="Unknown Item 34847", score=0, rank=3, src="SWP"},
            },
            [2] = {
                {id=34204, name="Amulet of Unfettered Magics", score=73, rank=1, src="SWP"},
                {id=33281, name="Brooch of Nature's Mercy", score=44.2, rank=2, src="ZA"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=30210, name="Unknown Item 30210", score=0, rank=1, src="SSC/TK"},
                {id=34393, name="Unknown Item 34393", score=0, rank=2, src="SWP"},
                {id=34210, name="Unknown Item 34210", score=0, rank=3, src="SWP"},
            },
            [5] = {
                {id=34399, name="Unknown Item 34399", score=0, rank=1, src="SWP"},
                {id=34364, name="Unknown Item 34364", score=0, rank=2, src="Vendor"},
                {id=30196, name="Unknown Item 30196", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=34557, name="Unknown Item 34557", score=0, rank=1, src="SWP"},
                {id=30888, name="Unknown Item 30888", score=0, rank=2, src="Hyjal"},
                {id=32256, name="Unknown Item 32256", score=0, rank=3, src="BT/Hyjal"},
            },
            [7] = {
                {id=34181, name="Unknown Item 34181", score=0, rank=1, src="SWP"},
                {id=34386, name="Unknown Item 34386", score=0, rank=2, src="SWP"},
                {id=30916, name="Unknown Item 30916", score=0, rank=3, src="Hyjal"},
            },
            [8] = {
                {id=34574, name="Unknown Item 34574", score=0, rank=1, src="SWP"},
                {id=32239, name="Unknown Item 32239", score=0, rank=2, src="BT"},
                {id=34919, name="Unknown Item 34919", score=0, rank=3, src="SWP"},
            },
            [9] = {
                {id=34447, name="Unknown Item 34447", score=0, rank=1, src="SWP"},
                {id=30870, name="Unknown Item 30870", score=0, rank=2, src="BT/Hyjal"},
                {id=32586, name="Unknown Item 32586", score=0, rank=3, src="Vendor"},
            },
            [10] = {
                {id=34406, name="Unknown Item 34406", score=0, rank=1, src="SWP"},
                {id=30205, name="Unknown Item 30205", score=0, rank=2, src="SSC/TK"},
                {id=34344, name="Unknown Item 34344", score=0, rank=3, src="SWP"},
            },
            [11] = {
                {id=29305, name="Band of the Eternal Sage", score=78.4, rank=1, src="BT/Hyjal"},
                {id=34362, name="Loop of Forged Power", score=81.9, rank=2, src="Vendor"},
                {id=34230, name="Ring of Omnipotence", score=73.1, rank=3, src="SWP"},
            },
            [13] = {
                {id=34429, name="Shifting Naaru Sliver", score=0, rank=1, src="SWP"},
                {id=32483, name="The Skull of Gul'dan", score=85, rank=2, src="BT"},
                {id=33829, name="Hex Shrunken Head", score=53, rank=3, src="ZA"},
            },
            [15] = {
                {id=34242, name="Unknown Item 34242", score=0, rank=1, src="SWP"},
                {id=32524, name="Unknown Item 32524", score=0, rank=2, src="BT"},
                {id=32331, name="Unknown Item 32331", score=0, rank=3, src="BT"},
            },
        },
    },
    ["fire_mage"] = {
        [0] = {
            [1] = {
                {id=28193, name="Unknown Item 28193", score=0, rank=1, src="Pre-Raid"},
                {id=32089, name="Unknown Item 32089", score=0, rank=2, src="Pre-Raid"},
                {id=28415, name="Unknown Item 28415", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=28134, name="Brooch of Heightened Potential", score=58.1, rank=1, src="Shadow Lab"},
                {id=24121, name="Chain of the Twilight Owl", score=36.2, rank=2, src="Pre-Raid"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=27796, name="Unknown Item 27796", score=0, rank=1, src="Slave Pens"},
                {id=35343, name="Unknown Item 35343", score=0, rank=2, src="Pre-Raid"},
                {id=28866, name="Unknown Item 28866", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=21848, name="Unknown Item 21848", score=0, rank=1, src="Vendor"},
                {id=31340, name="Unknown Item 31340", score=0, rank=2, src="Pre-Raid"},
                {id=28191, name="Unknown Item 28191", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=21846, name="Unknown Item 21846", score=0, rank=1, src="Vendor"},
                {id=24256, name="Unknown Item 24256", score=0, rank=2, src="Vendor"},
                {id=29241, name="Unknown Item 29241", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=24262, name="Unknown Item 24262", score=0, rank=1, src="Vendor"},
                {id=30531, name="Unknown Item 30531", score=0, rank=2, src="Pre-Raid"},
                {id=28185, name="Unknown Item 28185", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=28406, name="Unknown Item 28406", score=0, rank=1, src="Arcatraz"},
                {id=28179, name="Unknown Item 28179", score=0, rank=2, src="Pre-Raid"},
                {id=28410, name="Unknown Item 28410", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=28411, name="Unknown Item 28411", score=0, rank=1, src="Pre-Raid"},
                {id=24250, name="Unknown Item 24250", score=0, rank=2, src="Vendor"},
                {id=29240, name="Unknown Item 29240", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=21847, name="Unknown Item 21847", score=0, rank=1, src="Vendor"},
                {id=29270, name="Unknown Item 29270", score=0, rank=1, src="Pre-Raid"},
                {id=31149, name="Unknown Item 31149", score=0, rank=2, src="Pre-Raid"},
            },
            [11] = {
                {id=28555, name="Seal of the Exorcist", score=44.8, rank=1, src="Pre-Raid"},
                {id=29172, name="Ashyen's Gift", score=51.2, rank=2, src="Pre-Raid"},
                {id=21709, name="Ring of the Fallen God", score=51.9, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=27683, name="Quagmirran's Eye", score=37, rank=1, src="Slave Pens"},
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=2, src="Pre-Raid"},
                {id=23207, name="Mark of the Champion", score=0, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=23050, name="Unknown Item 23050", score=0, rank=1, src="Pre-Raid"},
                {id=22731, name="Unknown Item 22731", score=0, rank=2, src="Pre-Raid"},
                {id=27981, name="Unknown Item 27981", score=0, rank=3, src="Sethekk"},
            },
        },
        [1] = {
            [1] = {
                {id=29076, name="Unknown Item 29076", score=0, rank=1, src="Kara/T4"},
                {id=28415, name="Unknown Item 28415", score=0, rank=2, src="Pre-Raid"},
                {id=28193, name="Unknown Item 28193", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=28530, name="Brooch of Unquenchable Fury", score=63.2, rank=1, src="Kara"},
                {id=28762, name="Adornment of Stolen Souls", score=66.5, rank=2, src="Kara"},
                {id=28134, name="Brooch of Heightened Potential", score=58.1, rank=3, src="Shadow Lab"},
            },
            [3] = {
                {id=29079, name="Unknown Item 29079", score=0, rank=1, src="Kara/T4"},
                {id=30925, name="Unknown Item 30925", score=0, rank=2, src="Kara/T4"},
                {id=27796, name="Unknown Item 27796", score=0, rank=3, src="Slave Pens"},
            },
            [5] = {
                {id=21848, name="Unknown Item 21848", score=0, rank=1, src="Vendor"},
                {id=29077, name="Unknown Item 29077", score=0, rank=2, src="BT/Hyjal"},
                {id=31297, name="Unknown Item 31297", score=0, rank=3, src="Kara/T4"},
            },
            [6] = {
                {id=21846, name="Unknown Item 21846", score=0, rank=1, src="Vendor"},
                {id=30673, name="Unknown Item 30673", score=0, rank=2, src="Kara/T4"},
                {id=24256, name="Unknown Item 24256", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=24262, name="Unknown Item 24262", score=0, rank=1, src="Vendor"},
                {id=30734, name="Unknown Item 30734", score=0, rank=2, src="Kara/T4"},
                {id=29078, name="Unknown Item 29078", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=28585, name="Unknown Item 28585", score=0, rank=1, src="Kara"},
                {id=28517, name="Unknown Item 28517", score=0, rank=2, src="Kara"},
                {id=27821, name="Unknown Item 27821", score=0, rank=3, src="Mana-Tombs"},
            },
            [9] = {
                {id=28411, name="Unknown Item 28411", score=0, rank=1, src="Pre-Raid"},
                {id=24250, name="Unknown Item 24250", score=0, rank=2, src="Vendor"},
                {id=28515, name="Unknown Item 28515", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=21847, name="Unknown Item 21847", score=0, rank=1, src="Vendor"},
                {id=28780, name="Unknown Item 28780", score=0, rank=2, src="Kara/T4"},
                {id=30725, name="Unknown Item 30725", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=28793, name="Band of Crimson Fury", score=67, rank=1, src="Kara/T4"},
                {id=29287, name="Violet Signet of the Archmage", score=65.1, rank=2, src="Kara"},
                {id=21709, name="Ring of the Fallen God", score=51.9, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=1, src="Pre-Raid"},
                {id=27683, name="Quagmirran's Eye", score=37, rank=2, src="Slave Pens"},
                {id=23207, name="Mark of the Champion", score=0, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=28766, name="Unknown Item 28766", score=0, rank=1, src="Kara"},
                {id=30735, name="Unknown Item 30735", score=0, rank=2, src="Kara/T4"},
                {id=28797, name="Unknown Item 28797", score=0, rank=3, src="Gruul"},
            },
        },
        [2] = {
            [1] = {
                {id=32494, name="Unknown Item 32494", score=0, rank=1, src="SSC/TK"},
                {id=30206, name="Unknown Item 30206", score=0, rank=2, src="SSC/TK"},
                {id=29076, name="Unknown Item 29076", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=30015, name="The Sun King's Talisman", score=77.6, rank=1, src="SSC/TK"},
                {id=28530, name="Brooch of Unquenchable Fury", score=63.2, rank=2, src="Kara"},
                {id=28762, name="Adornment of Stolen Souls", score=66.5, rank=3, src="Kara"},
            },
            [3] = {
                {id=30024, name="Unknown Item 30024", score=0, rank=1, src="TK"},
                {id=30210, name="Unknown Item 30210", score=0, rank=2, src="SSC/TK"},
                {id=30079, name="Unknown Item 30079", score=0, rank=3, src="SSC"},
            },
            [5] = {
                {id=30107, name="Unknown Item 30107", score=0, rank=1, src="SSC"},
                {id=21848, name="Unknown Item 21848", score=0, rank=2, src="Vendor"},
                {id=30196, name="Unknown Item 30196", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=30038, name="Unknown Item 30038", score=0, rank=1, src="Vendor"},
                {id=30064, name="Unknown Item 30064", score=0, rank=2, src="SSC"},
                {id=30020, name="Unknown Item 30020", score=0, rank=3, src="SSC/TK"},
            },
            [7] = {
                {id=30207, name="Unknown Item 30207", score=0, rank=1, src="SSC/TK"},
                {id=24262, name="Unknown Item 24262", score=0, rank=2, src="Vendor"},
                {id=30734, name="Unknown Item 30734", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=30067, name="Unknown Item 30067", score=0, rank=1, src="SSC"},
                {id=30037, name="Unknown Item 30037", score=0, rank=2, src="Vendor"},
                {id=28585, name="Unknown Item 28585", score=0, rank=3, src="Kara"},
            },
            [9] = {
                {id=29918, name="Unknown Item 29918", score=0, rank=1, src="TK"},
                {id=32820, name="Unknown Item 32820", score=0, rank=2, src="SSC/TK"},
                {id=24250, name="Unknown Item 24250", score=0, rank=3, src="Vendor"},
            },
            [10] = {
                {id=29987, name="Unknown Item 29987", score=0, rank=1, src="SSC/TK"},
                {id=30205, name="Unknown Item 30205", score=0, rank=2, src="SSC/TK"},
                {id=21847, name="Unknown Item 21847", score=0, rank=3, src="Vendor"},
            },
            [11] = {
                {id=29302, name="Band of Eternity", score=67.9, rank=1, src="SSC/TK"},
                {id=28793, name="Band of Crimson Fury", score=67, rank=2, src="Kara/T4"},
                {id=30109, name="Ring of Endless Coils", score=59.9, rank=3, src="SSC"},
            },
            [13] = {
                {id=30626, name="Sextant of Unstable Currents", score=36, rank=1, src="SSC"},
                {id=27683, name="Quagmirran's Eye", score=37, rank=2, src="Slave Pens"},
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=28766, name="Unknown Item 28766", score=0, rank=1, src="Kara"},
                {id=28797, name="Unknown Item 28797", score=0, rank=2, src="Gruul"},
                {id=30735, name="Unknown Item 30735", score=0, rank=3, src="Kara/T4"},
            },
        },
        [3] = {
            [1] = {
                {id=32525, name="Unknown Item 32525", score=0, rank=1, src="BT"},
                {id=31056, name="Unknown Item 31056", score=0, rank=2, src="BT/Hyjal"},
                {id=32494, name="Unknown Item 32494", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=32589, name="Hellfire-Encased Pendant", score=36.8, rank=1, src="BT/Hyjal"},
                {id=32349, name="Translucent Spellthread Necklace", score=85.6, rank=2, src="BT"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=31059, name="Unknown Item 31059", score=0, rank=1, src="BT/Hyjal"},
                {id=32338, name="Unknown Item 32338", score=0, rank=2, src="BT/Hyjal"},
                {id=30884, name="Unknown Item 30884", score=0, rank=3, src="Hyjal"},
            },
            [5] = {
                {id=31057, name="Unknown Item 31057", score=0, rank=1, src="BT/Hyjal"},
                {id=30107, name="Unknown Item 30107", score=0, rank=2, src="SSC"},
                {id=30913, name="Unknown Item 30913", score=0, rank=3, src="ZA"},
            },
            [6] = {
                {id=30038, name="Unknown Item 30038", score=0, rank=1, src="Vendor"},
                {id=30064, name="Unknown Item 30064", score=0, rank=2, src="SSC"},
                {id=30888, name="Unknown Item 30888", score=0, rank=3, src="Hyjal"},
            },
            [7] = {
                {id=31058, name="Unknown Item 31058", score=0, rank=1, src="BT/Hyjal"},
                {id=30916, name="Unknown Item 30916", score=0, rank=2, src="Hyjal"},
                {id=24262, name="Unknown Item 24262", score=0, rank=3, src="Vendor"},
            },
            [8] = {
                {id=32239, name="Unknown Item 32239", score=0, rank=1, src="BT"},
                {id=30037, name="Unknown Item 30037", score=0, rank=2, src="Vendor"},
                {id=30067, name="Unknown Item 30067", score=0, rank=3, src="SSC"},
            },
            [9] = {
                {id=32586, name="Unknown Item 32586", score=0, rank=1, src="Vendor"},
                {id=30870, name="Unknown Item 30870", score=0, rank=2, src="BT/Hyjal"},
                {id=29918, name="Unknown Item 29918", score=0, rank=3, src="TK"},
            },
            [10] = {
                {id=31055, name="Unknown Item 31055", score=0, rank=1, src="BT/Hyjal"},
                {id=28507, name="Unknown Item 28507", score=0, rank=2, src="Kara"},
                {id=29080, name="Unknown Item 29080", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=1, src="BT"},
                {id=32247, name="Ring of Captured Storms", score=90.9, rank=2, src="BT"},
                {id=29305, name="Band of the Eternal Sage", score=78.4, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=32483, name="The Skull of Gul'dan", score=85, rank=1, src="BT"},
                {id=30720, name="Serpent-Coil Braid", score=41.4, rank=2, src="SSC/TK"},
                {id=32488, name="Ashtongue Talisman of Insight", score=0, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=32331, name="Unknown Item 32331", score=0, rank=2, src="BT"},
                {id=28797, name="Unknown Item 28797", score=0, rank=3, src="Gruul"},
            },
        },
        [4] = {
            [1] = {
                {id=32525, name="Unknown Item 32525", score=0, rank=1, src="BT"},
                {id=31056, name="Unknown Item 31056", score=0, rank=2, src="BT/Hyjal"},
                {id=32494, name="Unknown Item 32494", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=32589, name="Hellfire-Encased Pendant", score=36.8, rank=1, src="BT/Hyjal"},
                {id=24116, name="Eye of the Night", score=42.6, rank=2, src="Vendor"},
                {id=24121, name="Chain of the Twilight Owl", score=36.2, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=31059, name="Unknown Item 31059", score=0, rank=1, src="BT/Hyjal"},
                {id=32338, name="Unknown Item 32338", score=0, rank=2, src="BT/Hyjal"},
                {id=30884, name="Unknown Item 30884", score=0, rank=3, src="Hyjal"},
            },
            [5] = {
                {id=31057, name="Unknown Item 31057", score=0, rank=1, src="BT/Hyjal"},
                {id=30107, name="Unknown Item 30107", score=0, rank=2, src="SSC"},
                {id=30913, name="Unknown Item 30913", score=0, rank=3, src="ZA"},
            },
            [6] = {
                {id=30038, name="Unknown Item 30038", score=0, rank=1, src="Vendor"},
                {id=30064, name="Unknown Item 30064", score=0, rank=2, src="SSC"},
                {id=33291, name="Unknown Item 33291", score=0, rank=3, src="ZA"},
            },
            [7] = {
                {id=31058, name="Unknown Item 31058", score=0, rank=1, src="BT/Hyjal"},
                {id=30916, name="Unknown Item 30916", score=0, rank=2, src="Hyjal"},
                {id=30734, name="Unknown Item 30734", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=32239, name="Unknown Item 32239", score=0, rank=1, src="BT"},
                {id=30037, name="Unknown Item 30037", score=0, rank=2, src="Vendor"},
                {id=33357, name="Unknown Item 33357", score=0, rank=3, src="ZA"},
            },
            [9] = {
                {id=32586, name="Unknown Item 32586", score=0, rank=1, src="Vendor"},
                {id=33588, name="Unknown Item 33588", score=0, rank=2, src="ZA"},
            },
            [10] = {
                {id=31055, name="Unknown Item 31055", score=0, rank=1, src="BT/Hyjal"},
                {id=30725, name="Unknown Item 30725", score=0, rank=2, src="Kara/T4"},
                {id=33586, name="Unknown Item 33586", score=0, rank=3, src="ZA"},
            },
            [11] = {
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=1, src="BT"},
                {id=33497, name="Mana Attuned Band", score=70.8, rank=2, src="ZA"},
                {id=32247, name="Ring of Captured Storms", score=90.9, rank=3, src="BT"},
            },
            [13] = {
                {id=32483, name="The Skull of Gul'dan", score=85, rank=1, src="BT"},
                {id=33829, name="Hex Shrunken Head", score=53, rank=2, src="ZA"},
                {id=30720, name="Serpent-Coil Braid", score=41.4, rank=3, src="SSC/TK"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=33591, name="Unknown Item 33591", score=0, rank=2, src="ZA"},
                {id=32331, name="Unknown Item 32331", score=0, rank=3, src="BT"},
            },
        },
        [5] = {
            [1] = {
                {id=34340, name="Unknown Item 34340", score=0, rank=1, src="SWP"},
                {id=32525, name="Unknown Item 32525", score=0, rank=2, src="BT"},
                {id=34847, name="Unknown Item 34847", score=0, rank=3, src="SWP"},
            },
            [2] = {
                {id=34204, name="Amulet of Unfettered Magics", score=73, rank=1, src="SWP"},
                {id=34359, name="Pendant of Sunfire", score=74.4, rank=2, src="Vendor"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=31059, name="Unknown Item 31059", score=0, rank=1, src="BT/Hyjal"},
                {id=34210, name="Unknown Item 34210", score=0, rank=2, src="SWP"},
                {id=32587, name="Unknown Item 32587", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=34364, name="Unknown Item 34364", score=0, rank=1, src="Vendor"},
                {id=34399, name="Unknown Item 34399", score=0, rank=2, src="SWP"},
                {id=34232, name="Unknown Item 34232", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34557, name="Unknown Item 34557", score=0, rank=1, src="SWP"},
                {id=30038, name="Unknown Item 30038", score=0, rank=2, src="Vendor"},
                {id=30888, name="Unknown Item 30888", score=0, rank=3, src="Hyjal"},
            },
            [7] = {
                {id=34181, name="Unknown Item 34181", score=0, rank=1, src="SWP"},
                {id=31058, name="Unknown Item 31058", score=0, rank=2, src="BT/Hyjal"},
                {id=34386, name="Unknown Item 34386", score=0, rank=3, src="SWP"},
            },
            [8] = {
                {id=34574, name="Unknown Item 34574", score=0, rank=1, src="SWP"},
                {id=32239, name="Unknown Item 32239", score=0, rank=2, src="BT"},
                {id=34919, name="Unknown Item 34919", score=0, rank=3, src="SWP"},
            },
            [9] = {
                {id=34447, name="Unknown Item 34447", score=0, rank=1, src="SWP"},
                {id=32586, name="Unknown Item 32586", score=0, rank=2, src="Vendor"},
            },
            [10] = {
                {id=34344, name="Unknown Item 34344", score=0, rank=1, src="SWP"},
                {id=31055, name="Unknown Item 31055", score=0, rank=2, src="BT/Hyjal"},
                {id=34366, name="Unknown Item 34366", score=0, rank=3, src="Vendor"},
            },
            [11] = {
                {id=34362, name="Loop of Forged Power", score=81.9, rank=1, src="Vendor"},
                {id=33497, name="Mana Attuned Band", score=70.8, rank=2, src="ZA"},
                {id=34230, name="Ring of Omnipotence", score=73.1, rank=3, src="SWP"},
            },
            [13] = {
                {id=34429, name="Shifting Naaru Sliver", score=0, rank=1, src="SWP"},
                {id=32483, name="The Skull of Gul'dan", score=85, rank=2, src="BT"},
                {id=33829, name="Hex Shrunken Head", score=53, rank=3, src="ZA"},
            },
            [15] = {
                {id=34242, name="Unknown Item 34242", score=0, rank=1, src="SWP"},
                {id=32524, name="Unknown Item 32524", score=0, rank=2, src="BT"},
                {id=33591, name="Unknown Item 33591", score=0, rank=3, src="ZA"},
            },
        },
    },
    ["frost_mage"] = {
        [0] = {
            [1] = {
                {id=28193, name="Unknown Item 28193", score=0, rank=1, src="Pre-Raid"},
                {id=32089, name="Unknown Item 32089", score=0, rank=2, src="Pre-Raid"},
                {id=28415, name="Unknown Item 28415", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=28134, name="Brooch of Heightened Potential", score=58.1, rank=1, src="Shadow Lab"},
                {id=24121, name="Chain of the Twilight Owl", score=36.2, rank=2, src="Pre-Raid"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=27796, name="Unknown Item 27796", score=0, rank=1, src="Slave Pens"},
                {id=35343, name="Unknown Item 35343", score=0, rank=2, src="Pre-Raid"},
                {id=28866, name="Unknown Item 28866", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=21848, name="Unknown Item 21848", score=0, rank=1, src="Vendor"},
                {id=31340, name="Unknown Item 31340", score=0, rank=2, src="Pre-Raid"},
                {id=28191, name="Unknown Item 28191", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=21846, name="Unknown Item 21846", score=0, rank=1, src="Vendor"},
                {id=24256, name="Unknown Item 24256", score=0, rank=2, src="Vendor"},
                {id=29241, name="Unknown Item 29241", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=24262, name="Unknown Item 24262", score=0, rank=1, src="Vendor"},
                {id=30531, name="Unknown Item 30531", score=0, rank=2, src="Pre-Raid"},
                {id=28185, name="Unknown Item 28185", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=28406, name="Unknown Item 28406", score=0, rank=1, src="Arcatraz"},
                {id=28179, name="Unknown Item 28179", score=0, rank=2, src="Pre-Raid"},
                {id=28410, name="Unknown Item 28410", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=28411, name="Unknown Item 28411", score=0, rank=1, src="Pre-Raid"},
                {id=24250, name="Unknown Item 24250", score=0, rank=2, src="Vendor"},
                {id=29240, name="Unknown Item 29240", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=21847, name="Unknown Item 21847", score=0, rank=1, src="Vendor"},
                {id=29270, name="Unknown Item 29270", score=0, rank=1, src="Pre-Raid"},
                {id=31149, name="Unknown Item 31149", score=0, rank=2, src="Pre-Raid"},
            },
            [11] = {
                {id=28555, name="Seal of the Exorcist", score=44.8, rank=1, src="Pre-Raid"},
                {id=29172, name="Ashyen's Gift", score=51.2, rank=2, src="Pre-Raid"},
                {id=21709, name="Ring of the Fallen God", score=51.9, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=27683, name="Quagmirran's Eye", score=37, rank=1, src="Slave Pens"},
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=2, src="Pre-Raid"},
                {id=23207, name="Mark of the Champion", score=0, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=23050, name="Unknown Item 23050", score=0, rank=1, src="Pre-Raid"},
                {id=22731, name="Unknown Item 22731", score=0, rank=2, src="Pre-Raid"},
                {id=27981, name="Unknown Item 27981", score=0, rank=3, src="Sethekk"},
            },
        },
        [1] = {
            [1] = {
                {id=29076, name="Unknown Item 29076", score=0, rank=1, src="Kara/T4"},
                {id=28415, name="Unknown Item 28415", score=0, rank=2, src="Pre-Raid"},
                {id=28193, name="Unknown Item 28193", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=28530, name="Brooch of Unquenchable Fury", score=63.2, rank=1, src="Kara"},
                {id=28762, name="Adornment of Stolen Souls", score=66.5, rank=2, src="Kara"},
                {id=28134, name="Brooch of Heightened Potential", score=58.1, rank=3, src="Shadow Lab"},
            },
            [3] = {
                {id=21869, name="Unknown Item 21869", score=0, rank=1, src="Kara/T4"},
                {id=29079, name="Unknown Item 29079", score=0, rank=2, src="Kara/T4"},
                {id=27796, name="Unknown Item 27796", score=0, rank=3, src="Slave Pens"},
            },
            [5] = {
                {id=21871, name="Unknown Item 21871", score=0, rank=1, src="Kara/T4"},
                {id=28602, name="Unknown Item 28602", score=0, rank=2, src="Kara/T4"},
                {id=31340, name="Unknown Item 31340", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=24256, name="Unknown Item 24256", score=0, rank=1, src="Vendor"},
                {id=28799, name="Unknown Item 28799", score=0, rank=2, src="Gruul"},
                {id=28654, name="Unknown Item 28654", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=24262, name="Unknown Item 24262", score=0, rank=1, src="Vendor"},
                {id=30734, name="Unknown Item 30734", score=0, rank=2, src="Kara/T4"},
                {id=29078, name="Unknown Item 29078", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=21870, name="Unknown Item 21870", score=0, rank=1, src="Kara/T4"},
                {id=28585, name="Unknown Item 28585", score=0, rank=2, src="Kara"},
                {id=28517, name="Unknown Item 28517", score=0, rank=3, src="Kara"},
            },
            [9] = {
                {id=28411, name="Unknown Item 28411", score=0, rank=1, src="Pre-Raid"},
                {id=24250, name="Unknown Item 24250", score=0, rank=2, src="Vendor"},
                {id=27462, name="Unknown Item 27462", score=0, rank=3, src="Ramparts"},
            },
            [10] = {
                {id=30725, name="Unknown Item 30725", score=0, rank=1, src="Kara/T4"},
                {id=29080, name="Unknown Item 29080", score=0, rank=2, src="Kara/T4"},
                {id=28507, name="Unknown Item 28507", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=29287, name="Violet Signet of the Archmage", score=65.1, rank=1, src="Kara"},
                {id=28793, name="Band of Crimson Fury", score=67, rank=2, src="Kara/T4"},
                {id=28753, name="Ring of Recurrence", score=62.6, rank=3, src="Kara"},
            },
            [13] = {
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=1, src="Pre-Raid"},
                {id=27683, name="Quagmirran's Eye", score=37, rank=2, src="Slave Pens"},
                {id=23207, name="Mark of the Champion", score=0, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=28766, name="Unknown Item 28766", score=0, rank=1, src="Kara"},
                {id=28797, name="Unknown Item 28797", score=0, rank=2, src="Gruul"},
                {id=30735, name="Unknown Item 30735", score=0, rank=3, src="Kara/T4"},
            },
        },
        [2] = {
            [1] = {
                {id=30206, name="Unknown Item 30206", score=0, rank=1, src="SSC/TK"},
                {id=32494, name="Unknown Item 32494", score=0, rank=2, src="SSC/TK"},
                {id=29076, name="Unknown Item 29076", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=30015, name="The Sun King's Talisman", score=77.6, rank=1, src="SSC/TK"},
                {id=28134, name="Brooch of Heightened Potential", score=58.1, rank=2, src="Shadow Lab"},
                {id=28530, name="Brooch of Unquenchable Fury", score=63.2, rank=3, src="Kara"},
            },
            [3] = {
                {id=30210, name="Unknown Item 30210", score=0, rank=1, src="SSC/TK"},
                {id=30024, name="Unknown Item 30024", score=0, rank=2, src="TK"},
                {id=21869, name="Unknown Item 21869", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=30107, name="Unknown Item 30107", score=0, rank=1, src="SSC"},
                {id=21871, name="Unknown Item 21871", score=0, rank=2, src="Kara/T4"},
                {id=30196, name="Unknown Item 30196", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=30038, name="Unknown Item 30038", score=0, rank=1, src="Vendor"},
                {id=30064, name="Unknown Item 30064", score=0, rank=2, src="SSC"},
                {id=24256, name="Unknown Item 24256", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=30207, name="Unknown Item 30207", score=0, rank=1, src="SSC/TK"},
                {id=30734, name="Unknown Item 30734", score=0, rank=2, src="Kara/T4"},
                {id=24262, name="Unknown Item 24262", score=0, rank=3, src="Vendor"},
            },
            [8] = {
                {id=30067, name="Unknown Item 30067", score=0, rank=1, src="SSC"},
                {id=32795, name="Unknown Item 32795", score=0, rank=2, src="SSC/TK"},
                {id=30037, name="Unknown Item 30037", score=0, rank=3, src="Vendor"},
            },
            [9] = {
                {id=29918, name="Unknown Item 29918", score=0, rank=1, src="TK"},
                {id=32820, name="Unknown Item 32820", score=0, rank=2, src="SSC/TK"},
                {id=24250, name="Unknown Item 24250", score=0, rank=3, src="Vendor"},
            },
            [10] = {
                {id=30205, name="Unknown Item 30205", score=0, rank=1, src="SSC/TK"},
                {id=29987, name="Unknown Item 29987", score=0, rank=2, src="SSC/TK"},
                {id=30725, name="Unknown Item 30725", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=29302, name="Band of Eternity", score=67.9, rank=1, src="SSC/TK"},
                {id=30109, name="Ring of Endless Coils", score=59.9, rank=2, src="SSC"},
                {id=28793, name="Band of Crimson Fury", score=67, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=30720, name="Serpent-Coil Braid", score=41.4, rank=1, src="SSC/TK"},
                {id=27683, name="Quagmirran's Eye", score=37, rank=2, src="Slave Pens"},
                {id=30626, name="Sextant of Unstable Currents", score=36, rank=3, src="SSC"},
            },
            [15] = {
                {id=28766, name="Unknown Item 28766", score=0, rank=1, src="Kara"},
                {id=30735, name="Unknown Item 30735", score=0, rank=2, src="Kara/T4"},
                {id=28797, name="Unknown Item 28797", score=0, rank=3, src="Gruul"},
            },
        },
        [3] = {
            [1] = {
                {id=32525, name="Unknown Item 32525", score=0, rank=1, src="BT"},
                {id=31056, name="Unknown Item 31056", score=0, rank=2, src="BT/Hyjal"},
                {id=32494, name="Unknown Item 32494", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=30015, name="The Sun King's Talisman", score=77.6, rank=1, src="SSC/TK"},
                {id=32349, name="Translucent Spellthread Necklace", score=85.6, rank=2, src="BT"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=31059, name="Unknown Item 31059", score=0, rank=1, src="BT/Hyjal"},
                {id=30884, name="Unknown Item 30884", score=0, rank=2, src="Hyjal"},
                {id=32587, name="Unknown Item 32587", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=31057, name="Unknown Item 31057", score=0, rank=1, src="BT/Hyjal"},
                {id=30107, name="Unknown Item 30107", score=0, rank=2, src="SSC"},
                {id=30913, name="Unknown Item 30913", score=0, rank=3, src="ZA"},
            },
            [6] = {
                {id=32256, name="Unknown Item 32256", score=0, rank=1, src="BT/Hyjal"},
                {id=30888, name="Unknown Item 30888", score=0, rank=2, src="Hyjal"},
                {id=30038, name="Unknown Item 30038", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=31058, name="Unknown Item 31058", score=0, rank=1, src="BT/Hyjal"},
                {id=30916, name="Unknown Item 30916", score=0, rank=2, src="Hyjal"},
                {id=24262, name="Unknown Item 24262", score=0, rank=3, src="Vendor"},
            },
            [8] = {
                {id=32239, name="Unknown Item 32239", score=0, rank=1, src="BT"},
                {id=33914, name="Unknown Item 33914", score=0, rank=2, src="BT/Hyjal"},
                {id=30037, name="Unknown Item 30037", score=0, rank=3, src="Vendor"},
            },
            [9] = {
                {id=32586, name="Unknown Item 32586", score=0, rank=1, src="Vendor"},
                {id=30870, name="Unknown Item 30870", score=0, rank=2, src="BT/Hyjal"},
                {id=29918, name="Unknown Item 29918", score=0, rank=3, src="TK"},
            },
            [10] = {
                {id=31055, name="Unknown Item 31055", score=0, rank=1, src="BT/Hyjal"},
                {id=29080, name="Unknown Item 29080", score=0, rank=2, src="Kara/T4"},
                {id=28507, name="Unknown Item 28507", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=1, src="BT"},
                {id=32247, name="Ring of Captured Storms", score=90.9, rank=2, src="BT"},
                {id=29305, name="Band of the Eternal Sage", score=78.4, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=32483, name="The Skull of Gul'dan", score=85, rank=1, src="BT"},
                {id=32488, name="Ashtongue Talisman of Insight", score=0, rank=2, src="BT/Hyjal"},
                {id=30720, name="Serpent-Coil Braid", score=41.4, rank=3, src="SSC/TK"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=32331, name="Unknown Item 32331", score=0, rank=2, src="BT"},
                {id=28797, name="Unknown Item 28797", score=0, rank=3, src="Gruul"},
            },
        },
        [4] = {
            [1] = {
                {id=32525, name="Unknown Item 32525", score=0, rank=1, src="BT"},
                {id=31056, name="Unknown Item 31056", score=0, rank=2, src="BT/Hyjal"},
                {id=32494, name="Unknown Item 32494", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=33281, name="Brooch of Nature's Mercy", score=44.2, rank=1, src="ZA"},
                {id=33466, name="Loop of Cursed Bones", score=49.9, rank=2, src="ZA"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=31059, name="Unknown Item 31059", score=0, rank=1, src="BT/Hyjal"},
                {id=30884, name="Unknown Item 30884", score=0, rank=2, src="Hyjal"},
                {id=32587, name="Unknown Item 32587", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=31057, name="Unknown Item 31057", score=0, rank=1, src="BT/Hyjal"},
                {id=30107, name="Unknown Item 30107", score=0, rank=2, src="SSC"},
                {id=30913, name="Unknown Item 30913", score=0, rank=3, src="ZA"},
            },
            [6] = {
                {id=32256, name="Unknown Item 32256", score=0, rank=1, src="BT/Hyjal"},
                {id=30888, name="Unknown Item 30888", score=0, rank=2, src="Hyjal"},
                {id=30038, name="Unknown Item 30038", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=31058, name="Unknown Item 31058", score=0, rank=1, src="BT/Hyjal"},
                {id=30916, name="Unknown Item 30916", score=0, rank=2, src="Hyjal"},
                {id=33584, name="Unknown Item 33584", score=0, rank=3, src="ZA"},
            },
            [8] = {
                {id=32239, name="Unknown Item 32239", score=0, rank=1, src="BT"},
                {id=33357, name="Unknown Item 33357", score=0, rank=2, src="ZA"},
                {id=30037, name="Unknown Item 30037", score=0, rank=3, src="Vendor"},
            },
            [9] = {
                {id=32586, name="Unknown Item 32586", score=0, rank=1, src="Vendor"},
                {id=33588, name="Unknown Item 33588", score=0, rank=2, src="ZA"},
            },
            [10] = {
                {id=31055, name="Unknown Item 31055", score=0, rank=1, src="BT/Hyjal"},
                {id=30725, name="Unknown Item 30725", score=0, rank=2, src="Kara/T4"},
                {id=33586, name="Unknown Item 33586", score=0, rank=3, src="ZA"},
            },
            [11] = {
                {id=33497, name="Mana Attuned Band", score=70.8, rank=1, src="ZA"},
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=2, src="BT"},
                {id=32247, name="Ring of Captured Storms", score=90.9, rank=3, src="BT"},
            },
            [13] = {
                {id=32483, name="The Skull of Gul'dan", score=85, rank=1, src="BT"},
                {id=33829, name="Hex Shrunken Head", score=53, rank=2, src="ZA"},
                {id=32488, name="Ashtongue Talisman of Insight", score=0, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=33591, name="Unknown Item 33591", score=0, rank=2, src="ZA"},
                {id=32331, name="Unknown Item 32331", score=0, rank=3, src="BT"},
            },
        },
        [5] = {
            [1] = {
                {id=34340, name="Unknown Item 34340", score=0, rank=1, src="SWP"},
                {id=34847, name="Unknown Item 34847", score=0, rank=2, src="SWP"},
                {id=32525, name="Unknown Item 32525", score=0, rank=3, src="BT"},
            },
            [2] = {
                {id=34204, name="Amulet of Unfettered Magics", score=73, rank=1, src="SWP"},
                {id=34359, name="Pendant of Sunfire", score=74.4, rank=2, src="Vendor"},
                {id=37928, name="Guardian's Pendant of Subjugation", score=45.9, rank=3, src="SWP"},
            },
            [3] = {
                {id=31059, name="Unknown Item 31059", score=0, rank=1, src="BT/Hyjal"},
                {id=34210, name="Unknown Item 34210", score=0, rank=2, src="SWP"},
                {id=32587, name="Unknown Item 32587", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=34364, name="Unknown Item 34364", score=0, rank=1, src="Vendor"},
                {id=34232, name="Unknown Item 34232", score=0, rank=2, src="SWP"},
                {id=34399, name="Unknown Item 34399", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34557, name="Unknown Item 34557", score=0, rank=1, src="SWP"},
                {id=30888, name="Unknown Item 30888", score=0, rank=2, src="Hyjal"},
                {id=30038, name="Unknown Item 30038", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=34181, name="Unknown Item 34181", score=0, rank=1, src="SWP"},
                {id=34386, name="Unknown Item 34386", score=0, rank=2, src="SWP"},
                {id=31058, name="Unknown Item 31058", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=34574, name="Unknown Item 34574", score=0, rank=1, src="SWP"},
                {id=32239, name="Unknown Item 32239", score=0, rank=2, src="BT"},
                {id=34919, name="Unknown Item 34919", score=0, rank=3, src="SWP"},
            },
            [9] = {
                {id=34447, name="Unknown Item 34447", score=0, rank=1, src="SWP"},
                {id=32586, name="Unknown Item 32586", score=0, rank=2, src="Vendor"},
            },
            [10] = {
                {id=34344, name="Unknown Item 34344", score=0, rank=1, src="SWP"},
                {id=31055, name="Unknown Item 31055", score=0, rank=2, src="BT/Hyjal"},
                {id=34366, name="Unknown Item 34366", score=0, rank=3, src="Vendor"},
            },
            [11] = {
                {id=34362, name="Loop of Forged Power", score=81.9, rank=1, src="Vendor"},
                {id=34230, name="Ring of Omnipotence", score=73.1, rank=2, src="SWP"},
                {id=33497, name="Mana Attuned Band", score=70.8, rank=3, src="ZA"},
            },
            [13] = {
                {id=34429, name="Shifting Naaru Sliver", score=0, rank=1, src="SWP"},
                {id=32483, name="The Skull of Gul'dan", score=85, rank=2, src="BT"},
                {id=33829, name="Hex Shrunken Head", score=53, rank=3, src="ZA"},
            },
            [15] = {
                {id=34242, name="Unknown Item 34242", score=0, rank=1, src="SWP"},
                {id=32524, name="Unknown Item 32524", score=0, rank=2, src="BT"},
                {id=33591, name="Unknown Item 33591", score=0, rank=3, src="ZA"},
            },
        },
    },
}
for k,v in pairs(_d) do IRR_BIS_DATA[k] = v end
end
