-- BIS_Data_PALADIN.lua  (Auto-generated by scripts/update-bis.ps1)
-- Generated: 2026-03-01 19:52  -- DO NOT EDIT MANUALLY
IRR_BIS_DATA = IRR_BIS_DATA or {}
do local _d = {
    ["holy_paladin"] = {
        [0] = {
        },
        [1] = {
            [1] = {
                {id=29061, name="Unknown Item 29061", score=0, rank=1, src="Kara/T4"},
                {id=30728, name="Unknown Item 30728", score=0, rank=2, src="Kara/T4"},
                {id=32084, name="Unknown Item 32084", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=30726, name="Archaic Charm of Presence", score=83.6, rank=1, src="Kara/T4"},
                {id=29374, name="Necklace of Eternal Hope", score=60.1, rank=2, src="Pre-Raid"},
                {id=28822, name="Teeth of Gruul", score=65.6, rank=3, src="Kara/T4"},
            },
            [3] = {
                {id=29064, name="Unknown Item 29064", score=0, rank=1, src="Kara/T4"},
                {id=28666, name="Unknown Item 28666", score=0, rank=2, src="Kara/T4"},
                {id=21874, name="Unknown Item 21874", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=29062, name="Unknown Item 29062", score=0, rank=1, src="Kara/T4"},
                {id=29522, name="Unknown Item 29522", score=0, rank=2, src="Vendor"},
                {id=28662, name="Unknown Item 28662", score=0, rank=3, src="Kara/T4"},
            },
            [6] = {
                {id=29524, name="Unknown Item 29524", score=0, rank=1, src="Vendor"},
                {id=28733, name="Unknown Item 28733", score=0, rank=2, src="Kara/T4"},
                {id=28655, name="Unknown Item 28655", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=28748, name="Unknown Item 28748", score=0, rank=1, src="Kara/T4"},
                {id=28751, name="Unknown Item 28751", score=0, rank=2, src="Kara/T4"},
                {id=28591, name="Unknown Item 28591", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=28569, name="Unknown Item 28569", score=0, rank=1, src="Kara/T4"},
                {id=28752, name="Unknown Item 28752", score=0, rank=2, src="Kara/T4"},
                {id=30737, name="Unknown Item 30737", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=29523, name="Unknown Item 29523", score=0, rank=1, src="Vendor"},
                {id=23539, name="Unknown Item 23539", score=0, rank=2, src="Kara/T4"},
                {id=29183, name="Unknown Item 29183", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=29065, name="Unknown Item 29065", score=0, rank=1, src="Kara/T4"},
                {id=28771, name="Unknown Item 28771", score=0, rank=1, src="Kara/T4"},
                {id=28505, name="Unknown Item 28505", score=0, rank=2, src="Kara/T4"},
            },
            [11] = {
                {id=28790, name="Naaru Lightwarden's Band", score=69.1, rank=1, src="Kara/T4"},
                {id=29290, name="Violet Signet of the Grand Restorer", score=76.5, rank=2, src="Kara/T4"},
                {id=30736, name="Ring of Flowing Light", score=79, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=28727, name="Pendant of the Violet Eye", score=28, rank=2, src="Kara/T4"},
                {id=30841, name="Lower City Prayerbook", score=63, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=28765, name="Unknown Item 28765", score=0, rank=1, src="Kara/T4"},
                {id=27946, name="Unknown Item 27946", score=0, rank=2, src="Pre-Raid"},
                {id=29354, name="Unknown Item 29354", score=0, rank=3, src="Kara/T4"},
            },
        },
        [2] = {
            [1] = {
                {id=30136, name="Unknown Item 30136", score=0, rank=1, src="SSC/TK"},
                {id=32472, name="Unknown Item 32472", score=0, rank=2, src="SSC/TK"},
                {id=30728, name="Unknown Item 30728", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=30018, name="Lord Sanguinar's Claim", score=86.9, rank=1, src="BT/Hyjal"},
                {id=30726, name="Archaic Charm of Presence", score=83.6, rank=2, src="Kara/T4"},
                {id=28609, name="Emberspur Talisman", score=59.4, rank=3, src="Kara/T4"},
            },
            [3] = {
                {id=30138, name="Unknown Item 30138", score=0, rank=1, src="SSC/TK"},
                {id=30097, name="Unknown Item 30097", score=0, rank=2, src="SSC/TK"},
                {id=29064, name="Unknown Item 29064", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=30134, name="Unknown Item 30134", score=0, rank=1, src="SSC/TK"},
                {id=29062, name="Unknown Item 29062", score=0, rank=2, src="Kara/T4"},
                {id=21875, name="Unknown Item 21875", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=30030, name="Unknown Item 30030", score=0, rank=1, src="SSC/TK"},
                {id=29965, name="Unknown Item 29965", score=0, rank=2, src="SSC/TK"},
                {id=21873, name="Unknown Item 21873", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=29991, name="Unknown Item 29991", score=0, rank=1, src="SSC/TK"},
                {id=30727, name="Unknown Item 30727", score=0, rank=2, src="Kara/T4"},
                {id=30137, name="Unknown Item 30137", score=0, rank=3, src="SSC/TK"},
            },
            [8] = {
                {id=30027, name="Unknown Item 30027", score=0, rank=1, src="SSC/TK"},
                {id=30737, name="Unknown Item 30737", score=0, rank=2, src="Kara/T4"},
                {id=30092, name="Unknown Item 30092", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=30047, name="Unknown Item 30047", score=0, rank=1, src="SSC/TK"},
                {id=29523, name="Unknown Item 29523", score=0, rank=2, src="Vendor"},
                {id=23539, name="Unknown Item 23539", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=30112, name="Unknown Item 30112", score=0, rank=1, src="SSC/TK"},
                {id=29976, name="Unknown Item 29976", score=0, rank=2, src="SSC/TK"},
                {id=30135, name="Unknown Item 30135", score=0, rank=3, src="SSC/TK"},
            },
            [11] = {
                {id=30110, name="Coral Band of the Revived", score=92.9, rank=1, src="BT/Hyjal"},
                {id=30736, name="Ring of Flowing Light", score=79, rank=2, src="Kara/T4"},
                {id=28790, name="Naaru Lightwarden's Band", score=69.1, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=28590, name="Ribbon of Sacrifice", score=65.7, rank=2, src="SSC/TK"},
                {id=23047, name="Eye of the Dead", score=63, rank=3, src="SSC/TK"},
            },
            [15] = {
                {id=29989, name="Unknown Item 29989", score=0, rank=1, src="BT/Hyjal"},
                {id=28765, name="Unknown Item 28765", score=0, rank=2, src="Kara/T4"},
                {id=31329, name="Unknown Item 31329", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [3] = {
            [1] = {
                {id=30988, name="Unknown Item 30988", score=0, rank=1, src="BT/Hyjal"},
                {id=32354, name="Unknown Item 32354", score=0, rank=2, src="BT/Hyjal"},
                {id=32241, name="Unknown Item 32241", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=32370, name="Nadina's Pendant of Purity", score=92, rank=1, src="BT/Hyjal"},
                {id=30018, name="Lord Sanguinar's Claim", score=86.9, rank=2, src="BT/Hyjal"},
                {id=30726, name="Archaic Charm of Presence", score=83.6, rank=3, src="Kara/T4"},
            },
            [3] = {
                {id=30996, name="Unknown Item 30996", score=0, rank=1, src="BT/Hyjal"},
                {id=30878, name="Unknown Item 30878", score=0, rank=2, src="BT/Hyjal"},
                {id=30138, name="Unknown Item 30138", score=0, rank=3, src="SSC/TK"},
            },
            [5] = {
                {id=30992, name="Unknown Item 30992", score=0, rank=1, src="BT/Hyjal"},
                {id=30904, name="Unknown Item 30904", score=0, rank=2, src="BT/Hyjal"},
                {id=30134, name="Unknown Item 30134", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=30897, name="Unknown Item 30897", score=0, rank=1, src="BT/Hyjal"},
                {id=30030, name="Unknown Item 30030", score=0, rank=2, src="SSC/TK"},
                {id=29965, name="Unknown Item 29965", score=0, rank=3, src="SSC/TK"},
            },
            [7] = {
                {id=30994, name="Unknown Item 30994", score=0, rank=1, src="BT/Hyjal"},
                {id=30912, name="Unknown Item 30912", score=0, rank=2, src="BT/Hyjal"},
                {id=32271, name="Unknown Item 32271", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=32243, name="Unknown Item 32243", score=0, rank=1, src="BT/Hyjal"},
                {id=30027, name="Unknown Item 30027", score=0, rank=2, src="SSC/TK"},
                {id=32609, name="Unknown Item 32609", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=30862, name="Unknown Item 30862", score=0, rank=1, src="BT/Hyjal"},
                {id=30869, name="Unknown Item 30869", score=0, rank=2, src="BT/Hyjal"},
                {id=32571, name="Unknown Item 32571", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=30112, name="Unknown Item 30112", score=0, rank=1, src="SSC/TK"},
                {id=30983, name="Unknown Item 30983", score=0, rank=2, src="BT/Hyjal"},
                {id=29976, name="Unknown Item 29976", score=0, rank=3, src="SSC/TK"},
            },
            [11] = {
                {id=32528, name="Blessed Band of Karabor", score=81.7, rank=1, src="BT/Hyjal"},
                {id=32238, name="Ring of Calming Waves", score=90.4, rank=2, src="BT/Hyjal"},
                {id=29309, name="Band of the Eternal Restorer", score=77.9, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=32496, name="Memento of Tyrande", score=106.2, rank=1, src="BT/Hyjal"},
                {id=29376, name="Essence of the Martyr", score=75.6, rank=2, src="Pre-Raid"},
                {id=38288, name="Direbrew Hops", score=75.6, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=34012, name="Unknown Item 34012", score=0, rank=2, src="BT/Hyjal"},
                {id=29989, name="Unknown Item 29989", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [4] = {
            [1] = {
                {id=30988, name="Unknown Item 30988", score=0, rank=1, src="BT/Hyjal"},
                {id=32354, name="Unknown Item 32354", score=0, rank=2, src="BT/Hyjal"},
                {id=32241, name="Unknown Item 32241", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=32370, name="Nadina's Pendant of Purity", score=92, rank=1, src="BT/Hyjal"},
                {id=30018, name="Lord Sanguinar's Claim", score=86.9, rank=2, src="BT/Hyjal"},
                {id=30726, name="Archaic Charm of Presence", score=83.6, rank=3, src="Kara/T4"},
            },
            [3] = {
                {id=30996, name="Unknown Item 30996", score=0, rank=1, src="BT/Hyjal"},
                {id=30878, name="Unknown Item 30878", score=0, rank=2, src="BT/Hyjal"},
                {id=30138, name="Unknown Item 30138", score=0, rank=3, src="SSC/TK"},
            },
            [5] = {
                {id=30992, name="Unknown Item 30992", score=0, rank=1, src="BT/Hyjal"},
                {id=30904, name="Unknown Item 30904", score=0, rank=2, src="BT/Hyjal"},
                {id=30134, name="Unknown Item 30134", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=30897, name="Unknown Item 30897", score=0, rank=1, src="BT/Hyjal"},
                {id=33446, name="Unknown Item 33446", score=0, rank=2, src="ZA"},
                {id=30030, name="Unknown Item 30030", score=0, rank=3, src="SSC/TK"},
            },
            [7] = {
                {id=30994, name="Unknown Item 30994", score=0, rank=1, src="BT/Hyjal"},
                {id=30912, name="Unknown Item 30912", score=0, rank=2, src="BT/Hyjal"},
                {id=32271, name="Unknown Item 32271", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=32243, name="Unknown Item 32243", score=0, rank=1, src="BT/Hyjal"},
                {id=30027, name="Unknown Item 30027", score=0, rank=2, src="SSC/TK"},
                {id=32609, name="Unknown Item 32609", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=30862, name="Unknown Item 30862", score=0, rank=1, src="BT/Hyjal"},
                {id=30869, name="Unknown Item 30869", score=0, rank=2, src="BT/Hyjal"},
                {id=32571, name="Unknown Item 32571", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=30112, name="Unknown Item 30112", score=0, rank=1, src="SSC/TK"},
                {id=30983, name="Unknown Item 30983", score=0, rank=2, src="BT/Hyjal"},
                {id=29976, name="Unknown Item 29976", score=0, rank=3, src="SSC/TK"},
            },
            [11] = {
                {id=32528, name="Blessed Band of Karabor", score=81.7, rank=1, src="BT/Hyjal"},
                {id=32238, name="Ring of Calming Waves", score=90.4, rank=2, src="BT/Hyjal"},
                {id=29309, name="Band of the Eternal Restorer", score=77.9, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=32496, name="Memento of Tyrande", score=106.2, rank=1, src="BT/Hyjal"},
                {id=29376, name="Essence of the Martyr", score=75.6, rank=2, src="Pre-Raid"},
                {id=38288, name="Direbrew Hops", score=75.6, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=34012, name="Unknown Item 34012", score=0, rank=2, src="BT/Hyjal"},
                {id=33592, name="Unknown Item 33592", score=0, rank=3, src="ZA"},
            },
        },
        [5] = {
            [1] = {
                {id=34243, name="Unknown Item 34243", score=0, rank=1, src="SWP"},
                {id=34402, name="Unknown Item 34402", score=0, rank=2, src="SWP"},
                {id=35185, name="Unknown Item 35185", score=0, rank=3, src="SWP"},
            },
            [2] = {
                {id=32370, name="Nadina's Pendant of Purity", score=92, rank=1, src="BT/Hyjal"},
                {id=34360, name="Amulet of Flowing Life", score=73.6, rank=2, src="SWP"},
                {id=34184, name="Brooch of the Highborne", score=81.7, rank=3, src="SWP"},
            },
            [3] = {
                {id=34193, name="Unknown Item 34193", score=0, rank=1, src="SWP"},
                {id=34208, name="Unknown Item 34208", score=0, rank=2, src="SWP"},
                {id=30996, name="Unknown Item 30996", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=34229, name="Unknown Item 34229", score=0, rank=1, src="SWP"},
                {id=34379, name="Unknown Item 34379", score=0, rank=2, src="SWP"},
                {id=34395, name="Unknown Item 34395", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34487, name="Unknown Item 34487", score=0, rank=1, src="SWP"},
                {id=33446, name="Unknown Item 33446", score=0, rank=2, src="ZA"},
                {id=30030, name="Unknown Item 30030", score=0, rank=3, src="SSC/TK"},
            },
            [7] = {
                {id=34167, name="Unknown Item 34167", score=0, rank=1, src="SWP"},
                {id=34383, name="Unknown Item 34383", score=0, rank=2, src="SWP"},
                {id=30994, name="Unknown Item 30994", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=34559, name="Unknown Item 34559", score=0, rank=1, src="SWP"},
                {id=32243, name="Unknown Item 32243", score=0, rank=2, src="BT/Hyjal"},
                {id=30027, name="Unknown Item 30027", score=0, rank=3, src="SSC/TK"},
            },
            [9] = {
                {id=34432, name="Unknown Item 34432", score=0, rank=1, src="SWP"},
                {id=30862, name="Unknown Item 30862", score=0, rank=2, src="BT/Hyjal"},
                {id=30869, name="Unknown Item 30869", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=34380, name="Unknown Item 34380", score=0, rank=1, src="SWP"},
                {id=34240, name="Unknown Item 34240", score=0, rank=2, src="SWP"},
                {id=30112, name="Unknown Item 30112", score=0, rank=3, src="SSC/TK"},
            },
            [11] = {
                {id=34363, name="Ring of Flowing Life", score=79.9, rank=1, src="SWP"},
                {id=32528, name="Blessed Band of Karabor", score=81.7, rank=2, src="BT/Hyjal"},
                {id=34166, name="Band of Lucent Beams", score=85.6, rank=3, src="SWP"},
            },
            [13] = {
                {id=34430, name="Glimmering Naaru Sliver", score=107.1, rank=1, src="SWP"},
                {id=35750, name="Redeemer's Alchemist Stone", score=107.1, rank=2, src="SWP"},
                {id=32496, name="Memento of Tyrande", score=106.2, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=34012, name="Unknown Item 34012", score=0, rank=2, src="BT/Hyjal"},
                {id=33592, name="Unknown Item 33592", score=0, rank=3, src="ZA"},
            },
        },
    },
    ["prot_paladin"] = {
        [0] = {
            [1] = {
                {id=32083, name="Unknown Item 32083", score=0, rank=1, src="Pre-Raid"},
                {id=27704, name="Unknown Item 27704", score=0, rank=2, src="Pre-Raid"},
                {id=23536, name="Unknown Item 23536", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=28245, name="Pendant of Dominance", score=62, rank=1, src="Pre-Raid"},
                {id=27871, name="Maladaar's Blessed Chaplet", score=150, rank=2, src="Pre-Raid"},
                {id=29336, name="Mark of the Ravenguard", score=131, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=27706, name="Unknown Item 27706", score=0, rank=1, src="Pre-Raid"},
                {id=27847, name="Unknown Item 27847", score=0, rank=2, src="Pre-Raid"},
                {id=27739, name="Unknown Item 27739", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=28203, name="Unknown Item 28203", score=0, rank=1, src="Pre-Raid"},
                {id=28262, name="Unknown Item 28262", score=0, rank=2, src="Pre-Raid"},
                {id=27702, name="Unknown Item 27702", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=29253, name="Unknown Item 29253", score=0, rank=1, src="Pre-Raid"},
                {id=31460, name="Unknown Item 31460", score=0, rank=2, src="Pre-Raid"},
                {id=28641, name="Unknown Item 28641", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=29184, name="Unknown Item 29184", score=0, rank=1, src="Pre-Raid"},
                {id=27839, name="Unknown Item 27839", score=0, rank=2, src="Pre-Raid"},
                {id=23518, name="Unknown Item 23518", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=29254, name="Unknown Item 29254", score=0, rank=1, src="Pre-Raid"},
                {id=28642, name="Unknown Item 28642", score=0, rank=2, src="Pre-Raid"},
                {id=29239, name="Unknown Item 29239", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=29252, name="Unknown Item 29252", score=0, rank=1, src="Pre-Raid"},
                {id=23538, name="Unknown Item 23538", score=0, rank=2, src="Pre-Raid"},
                {id=28643, name="Unknown Item 28643", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=30741, name="Unknown Item 30741", score=0, rank=1, src="Pre-Raid"},
                {id=27535, name="Unknown Item 27535", score=0, rank=2, src="Pre-Raid"},
                {id=27703, name="Unknown Item 27703", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=28407, name="Elementium Band of the Sentry", score=155.5, rank=1, src="Pre-Raid"},
                {id=29172, name="Ashyen's Gift", score=60, rank=2, src="Pre-Raid"},
                {id=28555, name="Seal of the Exorcist", score=48, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=27529, name="Figurine of the Colossus", score=0, rank=1, src="Pre-Raid"},
                {id=23836, name="Goblin Rocket Launcher", score=90, rank=2, src="Pre-Raid"},
                {id=23835, name="Gnomish Poultryizer", score=90, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=27804, name="Unknown Item 27804", score=0, rank=1, src="Pre-Raid"},
                {id=24253, name="Unknown Item 24253", score=0, rank=2, src="Pre-Raid"},
                {id=27988, name="Unknown Item 27988", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [1] = {
            [1] = {
                {id=29068, name="Unknown Item 29068", score=0, rank=1, src="Kara/T4"},
                {id=32083, name="Unknown Item 32083", score=0, rank=2, src="Pre-Raid"},
                {id=28593, name="Unknown Item 28593", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=28516, name="Barbed Choker of Discipline", score=178.5, rank=1, src="Kara/T4"},
                {id=28245, name="Pendant of Dominance", score=62, rank=2, src="Pre-Raid"},
                {id=28530, name="Brooch of Unquenchable Fury", score=48, rank=3, src="Kara"},
            },
            [3] = {
                {id=29070, name="Unknown Item 29070", score=0, rank=1, src="Kara/T4"},
                {id=27706, name="Unknown Item 27706", score=0, rank=2, src="Pre-Raid"},
                {id=28743, name="Unknown Item 28743", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=29066, name="Unknown Item 29066", score=0, rank=1, src="Kara/T4"},
                {id=28597, name="Unknown Item 28597", score=0, rank=2, src="Kara/T4"},
                {id=27702, name="Unknown Item 27702", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=29253, name="Unknown Item 29253", score=0, rank=1, src="Pre-Raid"},
                {id=28566, name="Unknown Item 28566", score=0, rank=2, src="Kara/T4"},
                {id=28641, name="Unknown Item 28641", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=29069, name="Unknown Item 29069", score=0, rank=1, src="Kara/T4"},
                {id=28621, name="Unknown Item 28621", score=0, rank=2, src="Kara/T4"},
                {id=27705, name="Unknown Item 27705", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=29254, name="Unknown Item 29254", score=0, rank=1, src="Pre-Raid"},
                {id=30641, name="Unknown Item 30641", score=0, rank=2, src="Kara/T4"},
                {id=28642, name="Unknown Item 28642", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=29252, name="Unknown Item 29252", score=0, rank=1, src="Pre-Raid"},
                {id=23538, name="Unknown Item 23538", score=0, rank=2, src="Pre-Raid"},
                {id=28643, name="Unknown Item 28643", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=29067, name="Unknown Item 29067", score=0, rank=1, src="Kara/T4"},
                {id=28518, name="Unknown Item 28518", score=0, rank=2, src="Kara/T4"},
                {id=30741, name="Unknown Item 30741", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=28407, name="Elementium Band of the Sentry", score=155.5, rank=1, src="Pre-Raid"},
                {id=29172, name="Ashyen's Gift", score=60, rank=2, src="Pre-Raid"},
                {id=29279, name="Violet Signet of the Great Protector", score=134.9, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=27529, name="Figurine of the Colossus", score=0, rank=1, src="Pre-Raid"},
                {id=28528, name="Moroes' Lucky Pocket Watch", score=95, rank=2, src="Kara/T4"},
                {id=23836, name="Goblin Rocket Launcher", score=90, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=27804, name="Unknown Item 27804", score=0, rank=1, src="Pre-Raid"},
                {id=28766, name="Unknown Item 28766", score=0, rank=2, src="Kara"},
                {id=28660, name="Unknown Item 28660", score=0, rank=3, src="Kara/T4"},
            },
        },
        [2] = {
        },
        [3] = {
            [1] = {
                {id=32521, name="Unknown Item 32521", score=0, rank=1, src="BT/Hyjal"},
                {id=30987, name="Unknown Item 30987", score=0, rank=2, src="BT/Hyjal"},
                {id=30125, name="Unknown Item 30125", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=32362, name="Pendant of Titans", score=211.5, rank=1, src="BT/Hyjal"},
                {id=30007, name="The Darkener's Grasp", score=218.5, rank=2, src="BT/Hyjal"},
                {id=33921, name="Vindicator's Pendant of Dominance", score=70, rank=3, src="BT/Hyjal"},
            },
            [3] = {
                {id=30998, name="Unknown Item 30998", score=0, rank=1, src="BT/Hyjal"},
                {id=29070, name="Unknown Item 29070", score=0, rank=2, src="Kara/T4"},
                {id=32250, name="Unknown Item 32250", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=30991, name="Unknown Item 30991", score=0, rank=1, src="BT/Hyjal"},
                {id=30896, name="Unknown Item 30896", score=0, rank=2, src="BT/Hyjal"},
                {id=33695, name="Unknown Item 33695", score=0, rank=3, src="BT/Hyjal"},
            },
            [6] = {
                {id=32342, name="Unknown Item 32342", score=0, rank=1, src="BT/Hyjal"},
                {id=32333, name="Unknown Item 32333", score=0, rank=2, src="BT/Hyjal"},
                {id=30096, name="Unknown Item 30096", score=0, rank=3, src="BT/Hyjal"},
            },
            [7] = {
                {id=30995, name="Unknown Item 30995", score=0, rank=1, src="BT/Hyjal"},
                {id=32263, name="Unknown Item 32263", score=0, rank=2, src="BT/Hyjal"},
                {id=33698, name="Unknown Item 33698", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=32245, name="Unknown Item 32245", score=0, rank=1, src="BT/Hyjal"},
                {id=32267, name="Unknown Item 32267", score=0, rank=2, src="BT/Hyjal"},
                {id=30894, name="Unknown Item 30894", score=0, rank=3, src="Hyjal"},
            },
            [9] = {
                {id=32279, name="Unknown Item 32279", score=0, rank=1, src="BT/Hyjal"},
                {id=32232, name="Unknown Item 32232", score=0, rank=2, src="BT/Hyjal"},
                {id=33889, name="Unknown Item 33889", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=30985, name="Unknown Item 30985", score=0, rank=1, src="BT/Hyjal"},
                {id=29998, name="Unknown Item 29998", score=0, rank=2, src="BT/Hyjal"},
                {id=30124, name="Unknown Item 30124", score=0, rank=3, src="BT/Hyjal"},
            },
            [11] = {
                {id=30083, name="Ring of Sundered Souls", score=206.5, rank=1, src="BT/Hyjal"},
                {id=32261, name="Band of the Abyssal Lord", score=187, rank=2, src="BT/Hyjal"},
                {id=29172, name="Ashyen's Gift", score=60, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=31858, name="Darkmoon Card: Vengeance", score=102, rank=1, src="BT/Hyjal"},
                {id=31859, name="Darkmoon Card: Madness", score=102, rank=2, src="BT/Hyjal"},
                {id=23836, name="Goblin Rocket Launcher", score=90, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=34010, name="Unknown Item 34010", score=0, rank=1, src="BT/Hyjal"},
                {id=29925, name="Unknown Item 29925", score=0, rank=2, src="BT/Hyjal"},
                {id=28766, name="Unknown Item 28766", score=0, rank=3, src="Kara"},
            },
        },
        [4] = {
            [1] = {
                {id=32521, name="Unknown Item 32521", score=0, rank=1, src="BT/Hyjal"},
                {id=30987, name="Unknown Item 30987", score=0, rank=2, src="BT/Hyjal"},
                {id=33421, name="Unknown Item 33421", score=0, rank=3, src="ZA"},
            },
            [2] = {
                {id=32362, name="Pendant of Titans", score=211.5, rank=1, src="BT/Hyjal"},
                {id=30007, name="The Darkener's Grasp", score=218.5, rank=2, src="BT/Hyjal"},
                {id=33921, name="Vindicator's Pendant of Dominance", score=70, rank=3, src="BT/Hyjal"},
            },
            [3] = {
                {id=30998, name="Unknown Item 30998", score=0, rank=1, src="BT/Hyjal"},
                {id=29070, name="Unknown Item 29070", score=0, rank=2, src="Kara/T4"},
                {id=33481, name="Unknown Item 33481", score=0, rank=3, src="ZA"},
            },
            [5] = {
                {id=30991, name="Unknown Item 30991", score=0, rank=1, src="BT/Hyjal"},
                {id=30896, name="Unknown Item 30896", score=0, rank=2, src="BT/Hyjal"},
                {id=33473, name="Unknown Item 33473", score=0, rank=3, src="ZA"},
            },
            [6] = {
                {id=32342, name="Unknown Item 32342", score=0, rank=1, src="BT/Hyjal"},
                {id=33524, name="Unknown Item 33524", score=0, rank=2, src="ZA"},
                {id=32333, name="Unknown Item 32333", score=0, rank=3, src="BT/Hyjal"},
            },
            [7] = {
                {id=30995, name="Unknown Item 30995", score=0, rank=1, src="BT/Hyjal"},
                {id=32263, name="Unknown Item 32263", score=0, rank=2, src="BT/Hyjal"},
                {id=33515, name="Unknown Item 33515", score=0, rank=3, src="ZA"},
            },
            [8] = {
                {id=32245, name="Unknown Item 32245", score=0, rank=1, src="BT/Hyjal"},
                {id=33523, name="Unknown Item 33523", score=0, rank=2, src="ZA"},
                {id=32267, name="Unknown Item 32267", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=32279, name="Unknown Item 32279", score=0, rank=1, src="BT/Hyjal"},
                {id=32232, name="Unknown Item 32232", score=0, rank=2, src="BT/Hyjal"},
                {id=33889, name="Unknown Item 33889", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=30985, name="Unknown Item 30985", score=0, rank=1, src="BT/Hyjal"},
                {id=29998, name="Unknown Item 29998", score=0, rank=2, src="BT/Hyjal"},
                {id=33517, name="Unknown Item 33517", score=0, rank=3, src="ZA"},
            },
            [11] = {
                {id=30083, name="Ring of Sundered Souls", score=206.5, rank=1, src="BT/Hyjal"},
                {id=32261, name="Band of the Abyssal Lord", score=187, rank=2, src="BT/Hyjal"},
                {id=29172, name="Ashyen's Gift", score=60, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=31858, name="Darkmoon Card: Vengeance", score=102, rank=1, src="BT/Hyjal"},
                {id=31859, name="Darkmoon Card: Madness", score=102, rank=2, src="BT/Hyjal"},
                {id=23836, name="Goblin Rocket Launcher", score=90, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=34010, name="Unknown Item 34010", score=0, rank=1, src="BT/Hyjal"},
                {id=33593, name="Unknown Item 33593", score=0, rank=2, src="ZA"},
                {id=29925, name="Unknown Item 29925", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [5] = {
            [1] = {
                {id=34401, name="Unknown Item 34401", score=0, rank=1, src="SWP"},
                {id=34400, name="Unknown Item 34400", score=0, rank=2, src="SWP"},
                {id=32521, name="Unknown Item 32521", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=34178, name="Collar of the Pit Lord", score=201, rank=1, src="SWP"},
                {id=30007, name="The Darkener's Grasp", score=218.5, rank=2, src="BT/Hyjal"},
                {id=32362, name="Pendant of Titans", score=211.5, rank=3, src="BT/Hyjal"},
            },
            [3] = {
                {id=34389, name="Unknown Item 34389", score=0, rank=1, src="SWP"},
                {id=34192, name="Unknown Item 34192", score=0, rank=2, src="SWP"},
                {id=30998, name="Unknown Item 30998", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=34216, name="Unknown Item 34216", score=0, rank=1, src="SWP"},
                {id=30991, name="Unknown Item 30991", score=0, rank=2, src="BT/Hyjal"},
                {id=34945, name="Unknown Item 34945", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34488, name="Unknown Item 34488", score=0, rank=1, src="SWP"},
                {id=32342, name="Unknown Item 32342", score=0, rank=2, src="BT/Hyjal"},
                {id=33524, name="Unknown Item 33524", score=0, rank=3, src="ZA"},
            },
            [7] = {
                {id=34382, name="Unknown Item 34382", score=0, rank=1, src="SWP"},
                {id=30995, name="Unknown Item 30995", score=0, rank=2, src="BT/Hyjal"},
                {id=32263, name="Unknown Item 32263", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=34560, name="Unknown Item 34560", score=0, rank=1, src="SWP"},
                {id=32245, name="Unknown Item 32245", score=0, rank=2, src="BT/Hyjal"},
                {id=34947, name="Unknown Item 34947", score=0, rank=3, src="SWP"},
            },
            [9] = {
                {id=34433, name="Unknown Item 34433", score=0, rank=1, src="SWP"},
                {id=32232, name="Unknown Item 32232", score=0, rank=2, src="BT/Hyjal"},
                {id=32279, name="Unknown Item 32279", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=34352, name="Unknown Item 34352", score=0, rank=1, src="SWP"},
                {id=30985, name="Unknown Item 30985", score=0, rank=2, src="BT/Hyjal"},
                {id=29998, name="Unknown Item 29998", score=0, rank=3, src="BT/Hyjal"},
            },
            [11] = {
                {id=34213, name="Ring of Hardened Resolve", score=195.1, rank=1, src="SWP"},
                {id=34888, name="Ring of the Stalwart Protector", score=163.9, rank=2, src="SWP"},
                {id=30083, name="Ring of Sundered Souls", score=206.5, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=34473, name="Commendation of Kael'thas", score=114, rank=1, src="SWP"},
                {id=31858, name="Darkmoon Card: Vengeance", score=102, rank=2, src="BT/Hyjal"},
                {id=31859, name="Darkmoon Card: Madness", score=102, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=34190, name="Unknown Item 34190", score=0, rank=1, src="SWP"},
                {id=33593, name="Unknown Item 33593", score=0, rank=2, src="ZA"},
                {id=28766, name="Unknown Item 28766", score=0, rank=3, src="Kara"},
            },
        },
    },
    ["ret_paladin"] = {
        [0] = {
        },
        [1] = {
            [1] = {
                {id=29073, name="Unknown Item 29073", score=0, rank=1, src="Kara/T4"},
                {id=32087, name="Unknown Item 32087", score=0, rank=2, src="Kara/T4"},
                {id=27881, name="Unknown Item 27881", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=29381, name="Choker of Vile Intent", score=109.8, rank=1, src="Pre-Raid"},
                {id=28509, name="Worgen Claw Necklace", score=108.1, rank=2, src="Kara"},
                {id=28745, name="Mithril Chain of Heroism", score=96.8, rank=3, src="Kara/T4"},
            },
            [3] = {
                {id=30740, name="Unknown Item 30740", score=0, rank=1, src="Kara/T4"},
                {id=29075, name="Unknown Item 29075", score=0, rank=2, src="Kara/T4"},
                {id=33173, name="Unknown Item 33173", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=28484, name="Unknown Item 28484", score=0, rank=1, src="Kara/T4"},
                {id=30730, name="Unknown Item 30730", score=0, rank=2, src="Kara/T4"},
                {id=29071, name="Unknown Item 29071", score=0, rank=3, src="Kara/T4"},
            },
            [6] = {
                {id=28779, name="Unknown Item 28779", score=0, rank=1, src="Kara/T4"},
                {id=28828, name="Unknown Item 28828", score=0, rank=2, src="Kara/T4"},
                {id=29247, name="Unknown Item 29247", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=30257, name="Unknown Item 30257", score=0, rank=1, src="Kara/T4"},
                {id=31544, name="Unknown Item 31544", score=0, rank=2, src="Kara/T4"},
                {id=30739, name="Unknown Item 30739", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=28608, name="Unknown Item 28608", score=0, rank=1, src="Kara/T4"},
                {id=28545, name="Unknown Item 28545", score=0, rank=2, src="Kara"},
                {id=28176, name="Unknown Item 28176", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=28795, name="Unknown Item 28795", score=0, rank=1, src="Kara/T4"},
                {id=23537, name="Unknown Item 23537", score=0, rank=2, src="Kara/T4"},
                {id=28646, name="Unknown Item 28646", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=30644, name="Unknown Item 30644", score=0, rank=1, src="Kara"},
                {id=30341, name="Unknown Item 30341", score=0, rank=2, src="Kara/T4"},
                {id=28824, name="Unknown Item 28824", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=30834, name="Shapeshifter's Signet", score=79.3, rank=1, src="Kara/T4"},
                {id=28757, name="Ring of a Thousand Marks", score=116.3, rank=2, src="Kara/T4"},
                {id=31920, name="Shaffar's Band of Brutality", score=106, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=19343, name="Scrolls of Blinding Light", score=0, rank=2, src="Kara/T4"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=24259, name="Unknown Item 24259", score=0, rank=1, src="Vendor"},
                {id=30729, name="Unknown Item 30729", score=0, rank=2, src="Kara/T4"},
                {id=28672, name="Unknown Item 28672", score=0, rank=3, src="Kara"},
            },
        },
        [2] = {
            [1] = {
                {id=32461, name="Unknown Item 32461", score=0, rank=1, src="SSC/TK"},
                {id=30131, name="Unknown Item 30131", score=0, rank=2, src="SSC/TK"},
                {id=32041, name="Unknown Item 32041", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=30022, name="Pendant of the Perilous", score=105, rank=1, src="SSC/TK"},
                {id=29381, name="Choker of Vile Intent", score=109.8, rank=2, src="Pre-Raid"},
                {id=28509, name="Worgen Claw Necklace", score=108.1, rank=3, src="Kara"},
            },
            [3] = {
                {id=30055, name="Unknown Item 30055", score=0, rank=1, src="SSC"},
                {id=30133, name="Unknown Item 30133", score=0, rank=2, src="SSC/TK"},
                {id=29075, name="Unknown Item 29075", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=30129, name="Unknown Item 30129", score=0, rank=1, src="SSC/TK"},
                {id=28484, name="Unknown Item 28484", score=0, rank=2, src="Kara/T4"},
                {id=30101, name="Unknown Item 30101", score=0, rank=3, src="SSC"},
            },
            [6] = {
                {id=30106, name="Unknown Item 30106", score=0, rank=1, src="SSC"},
                {id=28779, name="Unknown Item 28779", score=0, rank=2, src="Kara/T4"},
                {id=28828, name="Unknown Item 28828", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=29950, name="Unknown Item 29950", score=0, rank=1, src="SSC/TK"},
                {id=30257, name="Unknown Item 30257", score=0, rank=2, src="Kara/T4"},
                {id=29995, name="Unknown Item 29995", score=0, rank=3, src="SSC/TK"},
            },
            [8] = {
                {id=30081, name="Unknown Item 30081", score=0, rank=1, src="SSC/TK"},
                {id=29951, name="Unknown Item 29951", score=0, rank=2, src="SSC/TK"},
                {id=30104, name="Unknown Item 30104", score=0, rank=3, src="SSC/TK"},
            },
            [9] = {
                {id=30057, name="Unknown Item 30057", score=0, rank=1, src="SSC/TK"},
                {id=28795, name="Unknown Item 28795", score=0, rank=2, src="Kara/T4"},
                {id=23537, name="Unknown Item 23537", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=29947, name="Unknown Item 29947", score=0, rank=1, src="TK"},
                {id=30644, name="Unknown Item 30644", score=0, rank=2, src="Kara"},
                {id=30341, name="Unknown Item 30341", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=30834, name="Shapeshifter's Signet", score=79.3, rank=1, src="Kara/T4"},
                {id=29997, name="Band of the Ranger-General", score=133.9, rank=2, src="SSC/TK"},
                {id=30061, name="Ancestral Ring of Conquest", score=104.9, rank=3, src="SSC/TK"},
            },
            [13] = {
                {id=29383, name="Bloodlust Brooch", score=72, rank=1, src="Kara/T4"},
                {id=28830, name="Dragonspine Trophy", score=40, rank=2, src="Gruul"},
                {id=23206, name="Mark of the Champion", score=0, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=30098, name="Unknown Item 30098", score=0, rank=1, src="SSC"},
                {id=24259, name="Unknown Item 24259", score=0, rank=2, src="Vendor"},
                {id=33122, name="Unknown Item 33122", score=0, rank=3, src="SSC/TK"},
            },
        },
        [3] = {
            [1] = {
                {id=32235, name="Unknown Item 32235", score=0, rank=1, src="BT"},
                {id=32376, name="Unknown Item 32376", score=0, rank=2, src="BT/Hyjal"},
                {id=32373, name="Unknown Item 32373", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=30022, name="Pendant of the Perilous", score=105, rank=1, src="SSC/TK"},
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=2, src="BT"},
                {id=29381, name="Choker of Vile Intent", score=109.8, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=30055, name="Unknown Item 30055", score=0, rank=1, src="SSC"},
                {id=32581, name="Unknown Item 32581", score=0, rank=2, src="BT/Hyjal"},
                {id=30997, name="Unknown Item 30997", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=30905, name="Unknown Item 30905", score=0, rank=1, src="BT/Hyjal"},
                {id=30990, name="Unknown Item 30990", score=0, rank=2, src="BT/Hyjal"},
                {id=30129, name="Unknown Item 30129", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=30106, name="Unknown Item 30106", score=0, rank=1, src="SSC"},
                {id=28779, name="Unknown Item 28779", score=0, rank=2, src="Kara/T4"},
                {id=28828, name="Unknown Item 28828", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=30900, name="Unknown Item 30900", score=0, rank=1, src="BT/Hyjal"},
                {id=30993, name="Unknown Item 30993", score=0, rank=2, src="BT/Hyjal"},
                {id=30257, name="Unknown Item 30257", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=32366, name="Unknown Item 32366", score=0, rank=1, src="BT"},
                {id=32345, name="Unknown Item 32345", score=0, rank=2, src="BT/Hyjal"},
                {id=30081, name="Unknown Item 30081", score=0, rank=3, src="SSC/TK"},
            },
            [9] = {
                {id=32574, name="Unknown Item 32574", score=0, rank=1, src="BT/Hyjal"},
                {id=32568, name="Unknown Item 32568", score=0, rank=2, src="BT/Hyjal"},
                {id=30057, name="Unknown Item 30057", score=0, rank=3, src="SSC/TK"},
            },
            [10] = {
                {id=29947, name="Unknown Item 29947", score=0, rank=1, src="TK"},
                {id=32347, name="Unknown Item 32347", score=0, rank=2, src="BT/Hyjal"},
                {id=30644, name="Unknown Item 30644", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=30834, name="Shapeshifter's Signet", score=79.3, rank=1, src="Kara/T4"},
                {id=32526, name="Band of Devastation", score=70.4, rank=2, src="BT/Hyjal"},
                {id=29997, name="Band of the Ranger-General", score=133.9, rank=3, src="SSC/TK"},
            },
            [13] = {
                {id=29383, name="Bloodlust Brooch", score=72, rank=1, src="Kara/T4"},
                {id=28830, name="Dragonspine Trophy", score=40, rank=2, src="Gruul"},
                {id=23206, name="Mark of the Champion", score=0, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=33122, name="Unknown Item 33122", score=0, rank=1, src="SSC/TK"},
                {id=30098, name="Unknown Item 30098", score=0, rank=2, src="SSC"},
                {id=24259, name="Unknown Item 24259", score=0, rank=3, src="Vendor"},
            },
        },
        [4] = {
            [1] = {
                {id=32235, name="Unknown Item 32235", score=0, rank=1, src="BT"},
                {id=32376, name="Unknown Item 32376", score=0, rank=2, src="BT/Hyjal"},
                {id=32373, name="Unknown Item 32373", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=30022, name="Pendant of the Perilous", score=105, rank=1, src="SSC/TK"},
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=2, src="BT"},
                {id=33296, name="Brooch of Deftness", score=90.8, rank=3, src="ZA"},
            },
            [3] = {
                {id=30055, name="Unknown Item 30055", score=0, rank=1, src="SSC"},
                {id=32581, name="Unknown Item 32581", score=0, rank=2, src="BT/Hyjal"},
                {id=30997, name="Unknown Item 30997", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=30905, name="Unknown Item 30905", score=0, rank=1, src="BT/Hyjal"},
                {id=30990, name="Unknown Item 30990", score=0, rank=2, src="BT/Hyjal"},
                {id=30129, name="Unknown Item 30129", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=30106, name="Unknown Item 30106", score=0, rank=1, src="SSC"},
                {id=32265, name="Unknown Item 32265", score=0, rank=2, src="ZA"},
                {id=28779, name="Unknown Item 28779", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=30900, name="Unknown Item 30900", score=0, rank=1, src="BT/Hyjal"},
                {id=30993, name="Unknown Item 30993", score=0, rank=2, src="BT/Hyjal"},
                {id=30257, name="Unknown Item 30257", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=32366, name="Unknown Item 32366", score=0, rank=1, src="BT"},
                {id=32345, name="Unknown Item 32345", score=0, rank=2, src="BT/Hyjal"},
                {id=30081, name="Unknown Item 30081", score=0, rank=3, src="SSC/TK"},
            },
            [9] = {
                {id=32574, name="Unknown Item 32574", score=0, rank=1, src="BT/Hyjal"},
                {id=32568, name="Unknown Item 32568", score=0, rank=2, src="BT/Hyjal"},
                {id=30057, name="Unknown Item 30057", score=0, rank=3, src="SSC/TK"},
            },
            [10] = {
                {id=29947, name="Unknown Item 29947", score=0, rank=1, src="TK"},
                {id=32347, name="Unknown Item 32347", score=0, rank=2, src="BT/Hyjal"},
                {id=30644, name="Unknown Item 30644", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=30834, name="Shapeshifter's Signet", score=79.3, rank=1, src="Kara/T4"},
                {id=32526, name="Band of Devastation", score=70.4, rank=2, src="BT/Hyjal"},
                {id=29997, name="Band of the Ranger-General", score=133.9, rank=3, src="SSC/TK"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=33831, name="Berserker's Call", score=90, rank=2, src="ZA"},
                {id=23206, name="Mark of the Champion", score=0, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=33590, name="Unknown Item 33590", score=0, rank=1, src="ZA"},
                {id=33122, name="Unknown Item 33122", score=0, rank=2, src="SSC/TK"},
                {id=30098, name="Unknown Item 30098", score=0, rank=3, src="SSC"},
            },
        },
        [5] = {
            [1] = {
                {id=34244, name="Unknown Item 34244", score=0, rank=1, src="SWP"},
                {id=34333, name="Unknown Item 34333", score=0, rank=2, src="SWP"},
                {id=34354, name="Unknown Item 34354", score=0, rank=3, src="SWP"},
            },
            [2] = {
                {id=34177, name="Clutch of Demise", score=104.8, rank=1, src="SWP"},
                {id=34358, name="Hard Khorium Choker", score=302.2, rank=2, src="Vendor"},
                {id=34679, name="Shattered Sun Pendant of Might", score=92.9, rank=3, src="SWP"},
            },
            [3] = {
                {id=34388, name="Unknown Item 34388", score=0, rank=1, src="SWP"},
                {id=34392, name="Unknown Item 34392", score=0, rank=2, src="SWP"},
                {id=34195, name="Unknown Item 34195", score=0, rank=3, src="SWP"},
            },
            [5] = {
                {id=34397, name="Unknown Item 34397", score=0, rank=1, src="SWP"},
                {id=34215, name="Unknown Item 34215", score=0, rank=2, src="SWP"},
                {id=34369, name="Unknown Item 34369", score=0, rank=3, src="Vendor"},
            },
            [6] = {
                {id=34485, name="Unknown Item 34485", score=0, rank=1, src="SWP"},
                {id=30106, name="Unknown Item 30106", score=0, rank=2, src="SSC"},
                {id=32265, name="Unknown Item 32265", score=0, rank=3, src="ZA"},
            },
            [7] = {
                {id=34180, name="Unknown Item 34180", score=0, rank=1, src="SWP"},
                {id=34188, name="Unknown Item 34188", score=0, rank=2, src="SWP"},
                {id=30900, name="Unknown Item 30900", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=34561, name="Unknown Item 34561", score=0, rank=1, src="SWP"},
                {id=32366, name="Unknown Item 32366", score=0, rank=2, src="BT"},
                {id=32345, name="Unknown Item 32345", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=34431, name="Unknown Item 34431", score=0, rank=1, src="SWP"},
                {id=32574, name="Unknown Item 32574", score=0, rank=2, src="BT/Hyjal"},
                {id=32568, name="Unknown Item 32568", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=34343, name="Unknown Item 34343", score=0, rank=1, src="SWP"},
                {id=34370, name="Unknown Item 34370", score=0, rank=2, src="Vendor"},
                {id=29947, name="Unknown Item 29947", score=0, rank=3, src="TK"},
            },
            [11] = {
                {id=34361, name="Hard Khorium Band", score=107.2, rank=1, src="SWP"},
                {id=34189, name="Band of Ruinous Delight", score=371.4, rank=2, src="SWP"},
                {id=30834, name="Shapeshifter's Signet", score=79.3, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=34472, name="Shard of Contempt", score=88, rank=1, src="SWP"},
                {id=34427, name="Blackened Naaru Sliver", score=0, rank=2, src="SWP"},
                {id=28830, name="Dragonspine Trophy", score=40, rank=3, src="Gruul"},
            },
            [15] = {
                {id=34241, name="Unknown Item 34241", score=0, rank=1, src="SWP"},
                {id=33590, name="Unknown Item 33590", score=0, rank=2, src="ZA"},
                {id=33122, name="Unknown Item 33122", score=0, rank=3, src="SSC/TK"},
            },
        },
    },
}
for k,v in pairs(_d) do IRR_BIS_DATA[k] = v end
end
