-- BIS_Data_SHAMAN.lua  (Auto-generated by scripts/update-bis.ps1)
-- Generated: 2026-03-01 19:52  -- DO NOT EDIT MANUALLY
IRR_BIS_DATA = IRR_BIS_DATA or {}
do local _d = {
    ["elemental_shaman"] = {
        [0] = {
            [1] = {
                {id=32086, name="Unknown Item 32086", score=0, rank=1, src="Pre-Raid"},
                {id=28415, name="Unknown Item 28415", score=0, rank=2, src="Pre-Raid"},
                {id=28278, name="Unknown Item 28278", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=28134, name="Brooch of Heightened Potential", score=58.1, rank=1, src="Shadow Lab"},
                {id=31692, name="Natasha's Ember Necklace", score=50, rank=2, src="Pre-Raid"},
                {id=29333, name="Torc of the Sethekk Prophet", score=52.3, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=32078, name="Unknown Item 32078", score=0, rank=1, src="Pre-Raid"},
                {id=30925, name="Unknown Item 30925", score=0, rank=2, src="Kara/T4"},
                {id=27796, name="Unknown Item 27796", score=0, rank=3, src="Slave Pens"},
            },
            [5] = {
                {id=29519, name="Unknown Item 29519", score=0, rank=1, src="Pre-Raid"},
                {id=29522, name="Unknown Item 29522", score=0, rank=2, src="Vendor"},
                {id=28191, name="Unknown Item 28191", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=29520, name="Unknown Item 29520", score=0, rank=1, src="Pre-Raid"},
                {id=24256, name="Unknown Item 24256", score=0, rank=2, src="Vendor"},
                {id=29524, name="Unknown Item 29524", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=24262, name="Unknown Item 24262", score=0, rank=1, src="Vendor"},
                {id=30541, name="Unknown Item 30541", score=0, rank=2, src="Pre-Raid"},
                {id=30709, name="Unknown Item 30709", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=28406, name="Unknown Item 28406", score=0, rank=1, src="Arcatraz"},
                {id=28179, name="Unknown Item 28179", score=0, rank=2, src="Pre-Raid"},
            },
            [9] = {
                {id=29521, name="Unknown Item 29521", score=0, rank=1, src="Pre-Raid"},
                {id=29523, name="Unknown Item 29523", score=0, rank=2, src="Vendor"},
                {id=24250, name="Unknown Item 24250", score=0, rank=3, src="Vendor"},
            },
            [10] = {
                {id=27465, name="Unknown Item 27465", score=0, rank=1, src="Pre-Raid"},
                {id=27793, name="Unknown Item 27793", score=0, rank=2, src="Pre-Raid"},
                {id=31149, name="Unknown Item 31149", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=29126, name="Seer's Signet", score=47.2, rank=1, src="Pre-Raid"},
                {id=29367, name="Ring of Cryptic Dreams", score=56.2, rank=2, src="Pre-Raid"},
                {id=29352, name="Cobalt Band of Tyrigosa", score=50.5, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=1, src="Pre-Raid"},
                {id=27683, name="Quagmirran's Eye", score=37, rank=2, src="Slave Pens"},
                {id=23207, name="Mark of the Champion", score=0, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=29369, name="Unknown Item 29369", score=0, rank=1, src="Pre-Raid"},
                {id=31201, name="Unknown Item 31201", score=0, rank=2, src="SSC/TK"},
                {id=27981, name="Unknown Item 27981", score=0, rank=3, src="Sethekk"},
            },
        },
        [1] = {
            [1] = {
                {id=29035, name="Unknown Item 29035", score=0, rank=1, src="Kara/T4"},
                {id=32086, name="Unknown Item 32086", score=0, rank=2, src="Pre-Raid"},
                {id=28415, name="Unknown Item 28415", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=28762, name="Adornment of Stolen Souls", score=66.5, rank=1, src="Kara"},
                {id=28530, name="Brooch of Unquenchable Fury", score=63.2, rank=2, src="Kara"},
                {id=28134, name="Brooch of Heightened Potential", score=58.1, rank=3, src="Shadow Lab"},
            },
            [3] = {
                {id=29037, name="Unknown Item 29037", score=0, rank=1, src="Kara/T4"},
                {id=32078, name="Unknown Item 32078", score=0, rank=2, src="Pre-Raid"},
                {id=30925, name="Unknown Item 30925", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=29519, name="Unknown Item 29519", score=0, rank=1, src="Pre-Raid"},
                {id=29522, name="Unknown Item 29522", score=0, rank=2, src="Vendor"},
                {id=29033, name="Unknown Item 29033", score=0, rank=3, src="Kara/T4"},
            },
            [6] = {
                {id=29520, name="Unknown Item 29520", score=0, rank=1, src="Pre-Raid"},
                {id=24256, name="Unknown Item 24256", score=0, rank=2, src="Vendor"},
                {id=29524, name="Unknown Item 29524", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=24262, name="Unknown Item 24262", score=0, rank=1, src="Vendor"},
                {id=30734, name="Unknown Item 30734", score=0, rank=2, src="Kara/T4"},
                {id=30541, name="Unknown Item 30541", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=28517, name="Unknown Item 28517", score=0, rank=1, src="Kara"},
                {id=28810, name="Unknown Item 28810", score=0, rank=2, src="Kara/T4"},
                {id=28406, name="Unknown Item 28406", score=0, rank=3, src="Arcatraz"},
            },
            [9] = {
                {id=29521, name="Unknown Item 29521", score=0, rank=1, src="Pre-Raid"},
                {id=29523, name="Unknown Item 29523", score=0, rank=2, src="Vendor"},
                {id=24250, name="Unknown Item 24250", score=0, rank=3, src="Vendor"},
            },
            [10] = {
                {id=28780, name="Unknown Item 28780", score=0, rank=1, src="Kara/T4"},
                {id=28507, name="Unknown Item 28507", score=0, rank=2, src="Kara"},
                {id=29034, name="Unknown Item 29034", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=30667, name="Ring of Unrelenting Storms", score=29.1, rank=1, src="Kara/T4"},
                {id=28753, name="Ring of Recurrence", score=62.6, rank=2, src="Kara"},
                {id=29287, name="Violet Signet of the Archmage", score=65.1, rank=3, src="Kara"},
            },
            [13] = {
                {id=28785, name="The Lightning Capacitor", score=0, rank=1, src="Kara/T4"},
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=2, src="Pre-Raid"},
                {id=23207, name="Mark of the Champion", score=0, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=28797, name="Unknown Item 28797", score=0, rank=1, src="Gruul"},
                {id=28766, name="Unknown Item 28766", score=0, rank=2, src="Kara"},
                {id=30735, name="Unknown Item 30735", score=0, rank=3, src="Kara/T4"},
            },
        },
        [2] = {
            [1] = {
                {id=29035, name="Unknown Item 29035", score=0, rank=1, src="Kara/T4"},
                {id=30171, name="Unknown Item 30171", score=0, rank=2, src="SSC/TK"},
                {id=32476, name="Unknown Item 32476", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=30015, name="The Sun King's Talisman", score=77.6, rank=1, src="SSC/TK"},
                {id=28762, name="Adornment of Stolen Souls", score=66.5, rank=2, src="Kara"},
                {id=28530, name="Brooch of Unquenchable Fury", score=63.2, rank=3, src="Kara"},
            },
            [3] = {
                {id=29037, name="Unknown Item 29037", score=0, rank=1, src="Kara/T4"},
                {id=30173, name="Unknown Item 30173", score=0, rank=2, src="SSC/TK"},
                {id=30024, name="Unknown Item 30024", score=0, rank=3, src="TK"},
            },
            [5] = {
                {id=30169, name="Unknown Item 30169", score=0, rank=1, src="SSC/TK"},
                {id=30107, name="Unknown Item 30107", score=0, rank=2, src="SSC"},
                {id=29519, name="Unknown Item 29519", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=30038, name="Unknown Item 30038", score=0, rank=1, src="Vendor"},
                {id=30064, name="Unknown Item 30064", score=0, rank=2, src="SSC"},
                {id=29520, name="Unknown Item 29520", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=30172, name="Unknown Item 30172", score=0, rank=1, src="SSC/TK"},
                {id=24262, name="Unknown Item 24262", score=0, rank=2, src="Vendor"},
                {id=30734, name="Unknown Item 30734", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=30067, name="Unknown Item 30067", score=0, rank=1, src="SSC"},
                {id=30037, name="Unknown Item 30037", score=0, rank=2, src="Vendor"},
                {id=30043, name="Unknown Item 30043", score=0, rank=3, src="SSC/TK"},
            },
            [9] = {
                {id=29918, name="Unknown Item 29918", score=0, rank=1, src="TK"},
                {id=29521, name="Unknown Item 29521", score=0, rank=2, src="Pre-Raid"},
                {id=29523, name="Unknown Item 29523", score=0, rank=3, src="Vendor"},
            },
            [10] = {
                {id=28780, name="Unknown Item 28780", score=0, rank=1, src="Kara/T4"},
                {id=30170, name="Unknown Item 30170", score=0, rank=2, src="SSC/TK"},
                {id=28507, name="Unknown Item 28507", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=30667, name="Ring of Unrelenting Storms", score=29.1, rank=1, src="Kara/T4"},
                {id=29302, name="Band of Eternity", score=67.9, rank=2, src="SSC/TK"},
                {id=30109, name="Ring of Endless Coils", score=59.9, rank=3, src="SSC"},
            },
            [13] = {
                {id=23207, name="Mark of the Champion", score=0, rank=1, src="Pre-Raid"},
                {id=28785, name="The Lightning Capacitor", score=0, rank=2, src="Kara/T4"},
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=28797, name="Unknown Item 28797", score=0, rank=1, src="Gruul"},
                {id=29992, name="Unknown Item 29992", score=0, rank=2, src="SSC/TK"},
                {id=28766, name="Unknown Item 28766", score=0, rank=3, src="Kara"},
            },
        },
        [3] = {
            [1] = {
                {id=31014, name="Unknown Item 31014", score=0, rank=1, src="BT/Hyjal"},
                {id=32525, name="Unknown Item 32525", score=0, rank=2, src="BT"},
                {id=29035, name="Unknown Item 29035", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=30015, name="The Sun King's Talisman", score=77.6, rank=1, src="SSC/TK"},
                {id=32349, name="Translucent Spellthread Necklace", score=85.6, rank=2, src="BT"},
                {id=28762, name="Adornment of Stolen Souls", score=66.5, rank=3, src="Kara"},
            },
            [3] = {
                {id=31023, name="Unknown Item 31023", score=0, rank=1, src="BT/Hyjal"},
                {id=32587, name="Unknown Item 32587", score=0, rank=2, src="BT/Hyjal"},
                {id=30884, name="Unknown Item 30884", score=0, rank=3, src="Hyjal"},
            },
            [5] = {
                {id=31017, name="Unknown Item 31017", score=0, rank=1, src="BT/Hyjal"},
                {id=32592, name="Unknown Item 32592", score=0, rank=2, src="BT/Hyjal"},
                {id=30169, name="Unknown Item 30169", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=32276, name="Unknown Item 32276", score=0, rank=1, src="BT/Hyjal"},
                {id=32256, name="Unknown Item 32256", score=0, rank=2, src="BT/Hyjal"},
                {id=30038, name="Unknown Item 30038", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=30916, name="Unknown Item 30916", score=0, rank=1, src="Hyjal"},
                {id=31020, name="Unknown Item 31020", score=0, rank=2, src="BT/Hyjal"},
                {id=30172, name="Unknown Item 30172", score=0, rank=3, src="SSC/TK"},
            },
            [8] = {
                {id=32239, name="Unknown Item 32239", score=0, rank=1, src="BT"},
                {id=32352, name="Unknown Item 32352", score=0, rank=2, src="BT"},
                {id=32242, name="Unknown Item 32242", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=32586, name="Unknown Item 32586", score=0, rank=1, src="Vendor"},
                {id=30870, name="Unknown Item 30870", score=0, rank=2, src="BT/Hyjal"},
                {id=32259, name="Unknown Item 32259", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=31008, name="Unknown Item 31008", score=0, rank=1, src="BT/Hyjal"},
                {id=32328, name="Unknown Item 32328", score=0, rank=2, src="BT/Hyjal"},
                {id=32275, name="Unknown Item 32275", score=0, rank=3, src="BT/Hyjal"},
            },
            [11] = {
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=1, src="BT"},
                {id=29305, name="Band of the Eternal Sage", score=78.4, rank=2, src="BT/Hyjal"},
                {id=32247, name="Ring of Captured Storms", score=90.9, rank=3, src="BT"},
            },
            [13] = {
                {id=23207, name="Mark of the Champion", score=0, rank=1, src="Pre-Raid"},
                {id=32483, name="The Skull of Gul'dan", score=85, rank=2, src="BT"},
                {id=28785, name="The Lightning Capacitor", score=0, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=32331, name="Unknown Item 32331", score=0, rank=1, src="BT"},
                {id=28797, name="Unknown Item 28797", score=0, rank=2, src="Gruul"},
                {id=29992, name="Unknown Item 29992", score=0, rank=3, src="SSC/TK"},
            },
        },
        [4] = {
            [1] = {
                {id=31014, name="Unknown Item 31014", score=0, rank=1, src="BT/Hyjal"},
                {id=32525, name="Unknown Item 32525", score=0, rank=2, src="BT"},
                {id=29035, name="Unknown Item 29035", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=33281, name="Brooch of Nature's Mercy", score=44.2, rank=1, src="ZA"},
                {id=33466, name="Loop of Cursed Bones", score=49.9, rank=2, src="ZA"},
                {id=30015, name="The Sun King's Talisman", score=77.6, rank=3, src="SSC/TK"},
            },
            [3] = {
                {id=31023, name="Unknown Item 31023", score=0, rank=1, src="BT/Hyjal"},
                {id=30884, name="Unknown Item 30884", score=0, rank=2, src="Hyjal"},
                {id=33970, name="Unknown Item 33970", score=0, rank=3, src="ZA"},
            },
            [5] = {
                {id=31017, name="Unknown Item 31017", score=0, rank=1, src="BT/Hyjal"},
                {id=33965, name="Unknown Item 33965", score=0, rank=2, src="ZA"},
                {id=32592, name="Unknown Item 32592", score=0, rank=3, src="BT/Hyjal"},
            },
            [6] = {
                {id=32276, name="Unknown Item 32276", score=0, rank=1, src="BT/Hyjal"},
                {id=32256, name="Unknown Item 32256", score=0, rank=2, src="BT/Hyjal"},
                {id=30038, name="Unknown Item 30038", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=30916, name="Unknown Item 30916", score=0, rank=1, src="Hyjal"},
                {id=33584, name="Unknown Item 33584", score=0, rank=2, src="ZA"},
                {id=31020, name="Unknown Item 31020", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=32239, name="Unknown Item 32239", score=0, rank=1, src="BT"},
                {id=32352, name="Unknown Item 32352", score=0, rank=2, src="BT"},
                {id=33357, name="Unknown Item 33357", score=0, rank=3, src="ZA"},
            },
            [9] = {
                {id=32586, name="Unknown Item 32586", score=0, rank=1, src="Vendor"},
                {id=30870, name="Unknown Item 30870", score=0, rank=2, src="BT/Hyjal"},
                {id=32259, name="Unknown Item 32259", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=31008, name="Unknown Item 31008", score=0, rank=1, src="BT/Hyjal"},
                {id=32328, name="Unknown Item 32328", score=0, rank=2, src="BT/Hyjal"},
                {id=33586, name="Unknown Item 33586", score=0, rank=3, src="ZA"},
            },
            [11] = {
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=1, src="BT"},
                {id=29305, name="Band of the Eternal Sage", score=78.4, rank=2, src="BT/Hyjal"},
                {id=33497, name="Mana Attuned Band", score=70.8, rank=3, src="ZA"},
            },
            [13] = {
                {id=23207, name="Mark of the Champion", score=0, rank=1, src="Pre-Raid"},
                {id=32483, name="The Skull of Gul'dan", score=85, rank=2, src="BT"},
                {id=28785, name="The Lightning Capacitor", score=0, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=32331, name="Unknown Item 32331", score=0, rank=1, src="BT"},
                {id=33591, name="Unknown Item 33591", score=0, rank=2, src="ZA"},
                {id=35321, name="Unknown Item 35321", score=0, rank=3, src="ZA"},
            },
        },
        [5] = {
            [1] = {
                {id=34332, name="Unknown Item 34332", score=0, rank=1, src="SWP"},
                {id=34340, name="Unknown Item 34340", score=0, rank=2, src="SWP"},
                {id=34355, name="Unknown Item 34355", score=0, rank=3, src="SWP"},
            },
            [2] = {
                {id=34359, name="Pendant of Sunfire", score=74.4, rank=1, src="Vendor"},
                {id=34204, name="Amulet of Unfettered Magics", score=73, rank=2, src="SWP"},
                {id=37928, name="Guardian's Pendant of Subjugation", score=45.9, rank=3, src="SWP"},
            },
            [3] = {
                {id=31023, name="Unknown Item 31023", score=0, rank=1, src="BT/Hyjal"},
                {id=34210, name="Unknown Item 34210", score=0, rank=2, src="SWP"},
                {id=34390, name="Unknown Item 34390", score=0, rank=3, src="SWP"},
            },
            [5] = {
                {id=34364, name="Unknown Item 34364", score=0, rank=1, src="Vendor"},
                {id=34396, name="Unknown Item 34396", score=0, rank=2, src="SWP"},
                {id=34232, name="Unknown Item 34232", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34542, name="Unknown Item 34542", score=0, rank=1, src="SWP"},
                {id=32276, name="Unknown Item 32276", score=0, rank=2, src="BT/Hyjal"},
                {id=34935, name="Unknown Item 34935", score=0, rank=3, src="SWP"},
            },
            [7] = {
                {id=34186, name="Unknown Item 34186", score=0, rank=1, src="SWP"},
                {id=34181, name="Unknown Item 34181", score=0, rank=2, src="SWP"},
                {id=34169, name="Unknown Item 34169", score=0, rank=3, src="SWP"},
            },
            [8] = {
                {id=34566, name="Unknown Item 34566", score=0, rank=1, src="SWP"},
                {id=32239, name="Unknown Item 32239", score=0, rank=2, src="BT"},
                {id=32352, name="Unknown Item 32352", score=0, rank=3, src="BT"},
            },
            [9] = {
                {id=34437, name="Unknown Item 34437", score=0, rank=1, src="SWP"},
                {id=32586, name="Unknown Item 32586", score=0, rank=2, src="Vendor"},
                {id=30870, name="Unknown Item 30870", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=34350, name="Unknown Item 34350", score=0, rank=1, src="SWP"},
                {id=34406, name="Unknown Item 34406", score=0, rank=2, src="SWP"},
                {id=34344, name="Unknown Item 34344", score=0, rank=3, src="SWP"},
            },
            [11] = {
                {id=34230, name="Ring of Omnipotence", score=73.1, rank=1, src="SWP"},
                {id=34362, name="Loop of Forged Power", score=81.9, rank=2, src="Vendor"},
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=3, src="BT"},
            },
            [13] = {
                {id=34429, name="Shifting Naaru Sliver", score=0, rank=1, src="SWP"},
                {id=32483, name="The Skull of Gul'dan", score=85, rank=2, src="BT"},
                {id=28785, name="The Lightning Capacitor", score=0, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=34242, name="Unknown Item 34242", score=0, rank=1, src="SWP"},
                {id=32331, name="Unknown Item 32331", score=0, rank=2, src="BT"},
                {id=33591, name="Unknown Item 33591", score=0, rank=3, src="ZA"},
            },
        },
    },
    ["enhance_shaman"] = {
        [0] = {
            [1] = {
                {id=28224, name="Unknown Item 28224", score=0, rank=1, src="Pre-Raid"},
                {id=32087, name="Unknown Item 32087", score=0, rank=2, src="Kara/T4"},
                {id=28182, name="Unknown Item 28182", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=29381, name="Choker of Vile Intent", score=109.8, rank=1, src="Pre-Raid"},
                {id=29119, name="Haramad's Bargain", score=94.7, rank=2, src="Pre-Raid"},
                {id=31695, name="Natasha's Choker", score=91, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=27797, name="Unknown Item 27797", score=0, rank=1, src="Kara/T4"},
                {id=27434, name="Unknown Item 27434", score=0, rank=2, src="Black Morass"},
                {id=25790, name="Unknown Item 25790", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=29525, name="Unknown Item 29525", score=0, rank=1, src="Vendor"},
                {id=29515, name="Unknown Item 29515", score=0, rank=2, src="Pre-Raid"},
                {id=30933, name="Unknown Item 30933", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=29526, name="Unknown Item 29526", score=0, rank=1, src="Pre-Raid"},
                {id=29516, name="Unknown Item 29516", score=0, rank=2, src="Pre-Raid"},
                {id=29247, name="Unknown Item 29247", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=31544, name="Unknown Item 31544", score=0, rank=1, src="Kara/T4"},
                {id=25687, name="Unknown Item 25687", score=0, rank=2, src="Pre-Raid"},
                {id=30538, name="Unknown Item 30538", score=0, rank=3, src="Slave Pens"},
            },
            [8] = {
                {id=25686, name="Unknown Item 25686", score=0, rank=1, src="Vendor"},
                {id=27867, name="Unknown Item 27867", score=0, rank=2, src="Pre-Raid"},
                {id=31288, name="Unknown Item 31288", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=29527, name="Unknown Item 29527", score=0, rank=1, src="Pre-Raid"},
                {id=29517, name="Unknown Item 29517", score=0, rank=2, src="Pre-Raid"},
                {id=25697, name="Unknown Item 25697", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=25685, name="Unknown Item 25685", score=0, rank=1, src="Vendor"},
                {id=30341, name="Unknown Item 30341", score=0, rank=2, src="Kara/T4"},
                {id=27509, name="Unknown Item 27509", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=30834, name="Shapeshifter's Signet", score=79.3, rank=1, src="Kara/T4"},
                {id=31920, name="Shaffar's Band of Brutality", score=106, rank=2, src="Kara/T4"},
                {id=30860, name="Kaylaan's Signet", score=92.5, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=29383, name="Bloodlust Brooch", score=72, rank=1, src="Kara/T4"},
                {id=23206, name="Mark of the Champion", score=0, rank=2, src="Kara/T4"},
                {id=28288, name="Abacus of Violent Odds", score=64, rank=3, src="ZA"},
            },
            [15] = {
                {id=24259, name="Unknown Item 24259", score=0, rank=1, src="Vendor"},
                {id=33122, name="Unknown Item 33122", score=0, rank=2, src="SSC/TK"},
                {id=29382, name="Unknown Item 29382", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [1] = {
            [1] = {
                {id=29040, name="Unknown Item 29040", score=0, rank=1, src="Kara/T4"},
                {id=32087, name="Unknown Item 32087", score=0, rank=2, src="Kara/T4"},
                {id=28732, name="Unknown Item 28732", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=29381, name="Choker of Vile Intent", score=109.8, rank=1, src="Pre-Raid"},
                {id=28509, name="Worgen Claw Necklace", score=108.1, rank=2, src="Kara"},
                {id=31695, name="Natasha's Choker", score=91, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=29043, name="Unknown Item 29043", score=0, rank=1, src="Kara/T4"},
                {id=28755, name="Unknown Item 28755", score=0, rank=2, src="Kara"},
                {id=27797, name="Unknown Item 27797", score=0, rank=3, src="Kara/T4"},
            },
            [5] = {
                {id=30730, name="Unknown Item 30730", score=0, rank=1, src="Kara/T4"},
                {id=29515, name="Unknown Item 29515", score=0, rank=2, src="Pre-Raid"},
                {id=29038, name="Unknown Item 29038", score=0, rank=3, src="Kara/T4"},
            },
            [6] = {
                {id=29516, name="Unknown Item 29516", score=0, rank=1, src="Pre-Raid"},
                {id=28828, name="Unknown Item 28828", score=0, rank=2, src="Kara/T4"},
                {id=29526, name="Unknown Item 29526", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=28741, name="Unknown Item 28741", score=0, rank=1, src="Kara"},
                {id=30257, name="Unknown Item 30257", score=0, rank=2, src="Kara/T4"},
                {id=31544, name="Unknown Item 31544", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=28545, name="Unknown Item 28545", score=0, rank=1, src="Kara"},
                {id=28746, name="Unknown Item 28746", score=0, rank=2, src="Kara/T4"},
                {id=25686, name="Unknown Item 25686", score=0, rank=3, src="Vendor"},
            },
            [9] = {
                {id=29517, name="Unknown Item 29517", score=0, rank=1, src="Pre-Raid"},
                {id=28514, name="Unknown Item 28514", score=0, rank=2, src="Kara/T4"},
                {id=29527, name="Unknown Item 29527", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=28776, name="Unknown Item 28776", score=0, rank=1, src="Kara/T4"},
                {id=30644, name="Unknown Item 30644", score=0, rank=2, src="Kara"},
                {id=29039, name="Unknown Item 29039", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=30834, name="Shapeshifter's Signet", score=79.3, rank=1, src="Kara/T4"},
                {id=28757, name="Ring of a Thousand Marks", score=116.3, rank=2, src="Kara/T4"},
                {id=28649, name="Garona's Signet Ring", score=108.5, rank=3, src="Kara"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=2, src="Kara/T4"},
                {id=28034, name="Hourglass of the Unraveller", score=44.8, rank=3, src="Black Morass"},
            },
            [15] = {
                {id=24259, name="Unknown Item 24259", score=0, rank=1, src="Vendor"},
                {id=28672, name="Unknown Item 28672", score=0, rank=2, src="Kara"},
                {id=27878, name="Unknown Item 27878", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [2] = {
            [1] = {
                {id=30190, name="Unknown Item 30190", score=0, rank=1, src="SSC/TK"},
                {id=32474, name="Unknown Item 32474", score=0, rank=2, src="SSC/TK"},
                {id=29040, name="Unknown Item 29040", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=30017, name="Telonicus's Pendant of Mayhem", score=113.1, rank=1, src="SSC/TK"},
                {id=30022, name="Pendant of the Perilous", score=105, rank=2, src="SSC/TK"},
                {id=29381, name="Choker of Vile Intent", score=109.8, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=30055, name="Unknown Item 30055", score=0, rank=1, src="SSC"},
                {id=29043, name="Unknown Item 29043", score=0, rank=2, src="Kara/T4"},
                {id=28755, name="Unknown Item 28755", score=0, rank=3, src="Kara"},
            },
            [5] = {
                {id=30185, name="Unknown Item 30185", score=0, rank=1, src="SSC/TK"},
                {id=29038, name="Unknown Item 29038", score=0, rank=2, src="Kara/T4"},
                {id=30730, name="Unknown Item 30730", score=0, rank=3, src="Kara/T4"},
            },
            [6] = {
                {id=30106, name="Unknown Item 30106", score=0, rank=1, src="SSC"},
                {id=29526, name="Unknown Item 29526", score=0, rank=2, src="Pre-Raid"},
                {id=28828, name="Unknown Item 28828", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=30192, name="Unknown Item 30192", score=0, rank=1, src="SSC/TK"},
                {id=28741, name="Unknown Item 28741", score=0, rank=2, src="Kara"},
                {id=30257, name="Unknown Item 30257", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=30039, name="Unknown Item 30039", score=0, rank=1, src="Vendor"},
                {id=30104, name="Unknown Item 30104", score=0, rank=2, src="SSC/TK"},
                {id=28545, name="Unknown Item 28545", score=0, rank=3, src="Kara"},
            },
            [9] = {
                {id=30091, name="Unknown Item 30091", score=0, rank=1, src="SSC/TK"},
                {id=29966, name="Unknown Item 29966", score=0, rank=2, src="TK"},
                {id=28514, name="Unknown Item 28514", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=30189, name="Unknown Item 30189", score=0, rank=1, src="SSC/TK"},
                {id=28776, name="Unknown Item 28776", score=0, rank=2, src="Kara/T4"},
                {id=30644, name="Unknown Item 30644", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=29997, name="Band of the Ranger-General", score=133.9, rank=1, src="SSC/TK"},
                {id=30052, name="Ring of Lethality", score=125.9, rank=2, src="SSC"},
                {id=28757, name="Ring of a Thousand Marks", score=116.3, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=2, src="Kara/T4"},
                {id=30627, name="Tsunami Talisman", score=73.2, rank=3, src="SSC"},
            },
            [15] = {
                {id=24259, name="Unknown Item 24259", score=0, rank=1, src="Vendor"},
                {id=29994, name="Unknown Item 29994", score=0, rank=2, src="SSC/TK"},
                {id=28672, name="Unknown Item 28672", score=0, rank=3, src="Kara"},
            },
        },
        [3] = {
            [1] = {
                {id=32235, name="Unknown Item 32235", score=0, rank=1, src="BT"},
                {id=31015, name="Unknown Item 31015", score=0, rank=2, src="BT/Hyjal"},
                {id=32376, name="Unknown Item 32376", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=1, src="BT"},
                {id=32591, name="Choker of Serrated Blades", score=353.7, rank=2, src="BT"},
                {id=30017, name="Telonicus's Pendant of Mayhem", score=113.1, rank=3, src="SSC/TK"},
            },
            [3] = {
                {id=32581, name="Unknown Item 32581", score=0, rank=1, src="BT/Hyjal"},
                {id=32575, name="Unknown Item 32575", score=0, rank=2, src="BT/Hyjal"},
                {id=30055, name="Unknown Item 30055", score=0, rank=3, src="SSC"},
            },
            [5] = {
                {id=30905, name="Unknown Item 30905", score=0, rank=1, src="BT/Hyjal"},
                {id=32252, name="Unknown Item 32252", score=0, rank=2, src="BT"},
                {id=30101, name="Unknown Item 30101", score=0, rank=3, src="SSC"},
            },
            [6] = {
                {id=30106, name="Unknown Item 30106", score=0, rank=1, src="SSC"},
                {id=32346, name="Unknown Item 32346", score=0, rank=2, src="BT/Hyjal"},
                {id=32265, name="Unknown Item 32265", score=0, rank=3, src="ZA"},
            },
            [7] = {
                {id=30900, name="Unknown Item 30900", score=0, rank=1, src="BT/Hyjal"},
                {id=30898, name="Unknown Item 30898", score=0, rank=2, src="Hyjal"},
                {id=30192, name="Unknown Item 30192", score=0, rank=3, src="SSC/TK"},
            },
            [8] = {
                {id=32366, name="Unknown Item 32366", score=0, rank=1, src="BT"},
                {id=32510, name="Unknown Item 32510", score=0, rank=2, src="BT/Hyjal"},
                {id=30880, name="Unknown Item 30880", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=30863, name="Unknown Item 30863", score=0, rank=1, src="Hyjal"},
                {id=32574, name="Unknown Item 32574", score=0, rank=2, src="BT/Hyjal"},
                {id=32324, name="Unknown Item 32324", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=32234, name="Unknown Item 32234", score=0, rank=1, src="BT/Hyjal"},
                {id=32347, name="Unknown Item 32347", score=0, rank=2, src="BT/Hyjal"},
                {id=29947, name="Unknown Item 29947", score=0, rank=3, src="TK"},
            },
            [11] = {
                {id=32497, name="Stormrage Signet Ring", score=330.9, rank=1, src="BT"},
                {id=29301, name="Band of the Eternal Champion", score=107.8, rank=2, src="BT/Hyjal"},
                {id=29997, name="Band of the Ranger-General", score=133.9, rank=3, src="SSC/TK"},
            },
            [13] = {
                {id=32505, name="Madness of the Betrayer", score=124, rank=1, src="BT"},
                {id=29383, name="Bloodlust Brooch", score=72, rank=2, src="Kara/T4"},
                {id=28830, name="Dragonspine Trophy", score=40, rank=3, src="Gruul"},
            },
            [15] = {
                {id=32323, name="Unknown Item 32323", score=0, rank=1, src="BT/Hyjal"},
                {id=29994, name="Unknown Item 29994", score=0, rank=2, src="SSC/TK"},
                {id=33122, name="Unknown Item 33122", score=0, rank=3, src="SSC/TK"},
            },
        },
        [4] = {
            [1] = {
                {id=32235, name="Unknown Item 32235", score=0, rank=1, src="BT"},
                {id=31015, name="Unknown Item 31015", score=0, rank=2, src="BT/Hyjal"},
                {id=32376, name="Unknown Item 32376", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=1, src="BT"},
                {id=32591, name="Choker of Serrated Blades", score=353.7, rank=2, src="BT"},
                {id=30017, name="Telonicus's Pendant of Mayhem", score=113.1, rank=3, src="SSC/TK"},
            },
            [3] = {
                {id=32581, name="Unknown Item 32581", score=0, rank=1, src="BT/Hyjal"},
                {id=32575, name="Unknown Item 32575", score=0, rank=2, src="BT/Hyjal"},
                {id=30055, name="Unknown Item 30055", score=0, rank=3, src="SSC"},
            },
            [5] = {
                {id=30905, name="Unknown Item 30905", score=0, rank=1, src="BT/Hyjal"},
                {id=32252, name="Unknown Item 32252", score=0, rank=2, src="BT"},
                {id=30101, name="Unknown Item 30101", score=0, rank=3, src="SSC"},
            },
            [6] = {
                {id=30106, name="Unknown Item 30106", score=0, rank=1, src="SSC"},
                {id=32346, name="Unknown Item 32346", score=0, rank=2, src="BT/Hyjal"},
                {id=32265, name="Unknown Item 32265", score=0, rank=3, src="ZA"},
            },
            [7] = {
                {id=30900, name="Unknown Item 30900", score=0, rank=1, src="BT/Hyjal"},
                {id=30898, name="Unknown Item 30898", score=0, rank=2, src="Hyjal"},
                {id=33538, name="Unknown Item 33538", score=0, rank=3, src="ZA"},
            },
            [8] = {
                {id=32510, name="Unknown Item 32510", score=0, rank=1, src="BT/Hyjal"},
                {id=32366, name="Unknown Item 32366", score=0, rank=2, src="BT"},
                {id=33222, name="Unknown Item 33222", score=0, rank=3, src="SWP"},
            },
            [9] = {
                {id=30863, name="Unknown Item 30863", score=0, rank=1, src="Hyjal"},
                {id=32574, name="Unknown Item 32574", score=0, rank=2, src="BT/Hyjal"},
                {id=32324, name="Unknown Item 32324", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=32234, name="Unknown Item 32234", score=0, rank=1, src="BT/Hyjal"},
                {id=32347, name="Unknown Item 32347", score=0, rank=2, src="BT/Hyjal"},
                {id=29947, name="Unknown Item 29947", score=0, rank=3, src="TK"},
            },
            [11] = {
                {id=32497, name="Stormrage Signet Ring", score=330.9, rank=1, src="BT"},
                {id=33496, name="Signet of Primal Wrath", score=304.6, rank=2, src="ZA"},
                {id=29301, name="Band of the Eternal Champion", score=107.8, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=28830, name="Dragonspine Trophy", score=40, rank=1, src="Gruul"},
                {id=32505, name="Madness of the Betrayer", score=124, rank=2, src="BT"},
                {id=33831, name="Berserker's Call", score=90, rank=3, src="ZA"},
            },
            [15] = {
                {id=32323, name="Unknown Item 32323", score=0, rank=1, src="BT/Hyjal"},
                {id=33590, name="Unknown Item 33590", score=0, rank=2, src="ZA"},
                {id=29994, name="Unknown Item 29994", score=0, rank=3, src="SSC/TK"},
            },
        },
        [5] = {
            [1] = {
                {id=34244, name="Unknown Item 34244", score=0, rank=1, src="SWP"},
                {id=34333, name="Unknown Item 34333", score=0, rank=2, src="SWP"},
                {id=32235, name="Unknown Item 32235", score=0, rank=3, src="BT"},
            },
            [2] = {
                {id=34358, name="Hard Khorium Choker", score=302.2, rank=1, src="Vendor"},
                {id=34177, name="Clutch of Demise", score=104.8, rank=2, src="SWP"},
                {id=32260, name="Choker of Endless Nightmares", score=151.8, rank=3, src="BT"},
            },
            [3] = {
                {id=34392, name="Unknown Item 34392", score=0, rank=1, src="SWP"},
                {id=34194, name="Unknown Item 34194", score=0, rank=2, src="SWP"},
                {id=31024, name="Unknown Item 31024", score=0, rank=3, src="SWP"},
            },
            [5] = {
                {id=34397, name="Unknown Item 34397", score=0, rank=1, src="SWP"},
                {id=34369, name="Unknown Item 34369", score=0, rank=2, src="Vendor"},
                {id=34373, name="Unknown Item 34373", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34545, name="Unknown Item 34545", score=0, rank=1, src="SWP"},
                {id=30106, name="Unknown Item 30106", score=0, rank=2, src="SSC"},
                {id=32346, name="Unknown Item 32346", score=0, rank=3, src="BT/Hyjal"},
            },
            [7] = {
                {id=34188, name="Unknown Item 34188", score=0, rank=1, src="SWP"},
                {id=30900, name="Unknown Item 30900", score=0, rank=2, src="BT/Hyjal"},
                {id=34168, name="Unknown Item 34168", score=0, rank=3, src="SWP"},
            },
            [8] = {
                {id=34567, name="Unknown Item 34567", score=0, rank=1, src="SWP"},
                {id=32510, name="Unknown Item 32510", score=0, rank=2, src="BT/Hyjal"},
                {id=32366, name="Unknown Item 32366", score=0, rank=3, src="BT"},
            },
            [9] = {
                {id=34439, name="Unknown Item 34439", score=0, rank=1, src="SWP"},
                {id=30863, name="Unknown Item 30863", score=0, rank=2, src="Hyjal"},
                {id=32574, name="Unknown Item 32574", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=34343, name="Unknown Item 34343", score=0, rank=1, src="SWP"},
                {id=34370, name="Unknown Item 34370", score=0, rank=2, src="Vendor"},
                {id=34234, name="Unknown Item 34234", score=0, rank=3, src="SWP"},
            },
            [11] = {
                {id=34189, name="Band of Ruinous Delight", score=371.4, rank=1, src="SWP"},
                {id=32497, name="Stormrage Signet Ring", score=330.9, rank=2, src="BT"},
                {id=34361, name="Hard Khorium Band", score=107.2, rank=3, src="SWP"},
            },
            [13] = {
                {id=34427, name="Blackened Naaru Sliver", score=0, rank=1, src="SWP"},
                {id=34472, name="Shard of Contempt", score=88, rank=2, src="SWP"},
                {id=28830, name="Dragonspine Trophy", score=40, rank=3, src="Gruul"},
            },
            [15] = {
                {id=34241, name="Unknown Item 34241", score=0, rank=1, src="SWP"},
                {id=32323, name="Unknown Item 32323", score=0, rank=2, src="BT/Hyjal"},
                {id=33590, name="Unknown Item 33590", score=0, rank=3, src="ZA"},
            },
        },
    },
    ["resto_shaman"] = {
        [0] = {
            [1] = {
                {id=24264, name="Unknown Item 24264", score=0, rank=1, src="Pre-Raid"},
                {id=31400, name="Unknown Item 31400", score=0, rank=2, src="Pre-Raid"},
                {id=32090, name="Unknown Item 32090", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=31691, name="Natasha's Guardian Cord", score=56.5, rank=1, src="Pre-Raid"},
                {id=30377, name="Karja's Medallion", score=65, rank=2, src="Pre-Raid"},
                {id=29374, name="Necklace of Eternal Hope", score=60.1, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=21874, name="Unknown Item 21874", score=0, rank=1, src="Pre-Raid"},
                {id=27775, name="Unknown Item 27775", score=0, rank=2, src="Pre-Raid"},
                {id=31407, name="Unknown Item 31407", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=21875, name="Unknown Item 21875", score=0, rank=1, src="Pre-Raid"},
                {id=29522, name="Unknown Item 29522", score=0, rank=2, src="Vendor"},
                {id=31396, name="Unknown Item 31396", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=29524, name="Unknown Item 29524", score=0, rank=1, src="Vendor"},
                {id=21873, name="Unknown Item 21873", score=0, rank=2, src="Pre-Raid"},
                {id=29250, name="Unknown Item 29250", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=30543, name="Unknown Item 30543", score=0, rank=1, src="Pre-Raid"},
                {id=24261, name="Unknown Item 24261", score=0, rank=2, src="Pre-Raid"},
                {id=31343, name="Unknown Item 31343", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=27411, name="Unknown Item 27411", score=0, rank=1, src="Pre-Raid"},
                {id=29251, name="Unknown Item 29251", score=0, rank=2, src="Pre-Raid"},
                {id=27525, name="Unknown Item 27525", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=29523, name="Unknown Item 29523", score=0, rank=1, src="Vendor"},
                {id=29183, name="Unknown Item 29183", score=0, rank=2, src="Pre-Raid"},
                {id=29249, name="Unknown Item 29249", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=29506, name="Unknown Item 29506", score=0, rank=1, src="Pre-Raid"},
                {id=31397, name="Unknown Item 31397", score=0, rank=2, src="Pre-Raid"},
                {id=24393, name="Unknown Item 24393", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=27780, name="Ring of Fabled Hope", score=67, rank=1, src="Pre-Raid"},
                {id=29814, name="Celestial Jewel Ring", score=58.6, rank=2, src="Pre-Raid"},
                {id=31383, name="Spiritualist's Mark of the Sha'tar", score=63.6, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=30841, name="Lower City Prayerbook", score=63, rank=2, src="Pre-Raid"},
                {id=28190, name="Scarab of the Infinite Cycle", score=63, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=31329, name="Unknown Item 31329", score=0, rank=1, src="Pre-Raid"},
                {id=24254, name="Unknown Item 24254", score=0, rank=2, src="Pre-Raid"},
                {id=29354, name="Unknown Item 29354", score=0, rank=3, src="Kara/T4"},
            },
        },
        [1] = {
            [1] = {
                {id=24264, name="Unknown Item 24264", score=0, rank=1, src="Pre-Raid"},
                {id=30728, name="Unknown Item 30728", score=0, rank=2, src="Kara/T4"},
                {id=29028, name="Unknown Item 29028", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=30726, name="Archaic Charm of Presence", score=83.6, rank=1, src="Kara/T4"},
                {id=28609, name="Emberspur Talisman", score=59.4, rank=2, src="Kara/T4"},
                {id=31691, name="Natasha's Guardian Cord", score=56.5, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=29031, name="Unknown Item 29031", score=0, rank=1, src="Kara/T4"},
                {id=29037, name="Unknown Item 29037", score=0, rank=2, src="Kara/T4"},
                {id=21874, name="Unknown Item 21874", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=29522, name="Unknown Item 29522", score=0, rank=1, src="Vendor"},
                {id=29029, name="Unknown Item 29029", score=0, rank=2, src="Kara/T4"},
                {id=21875, name="Unknown Item 21875", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=29524, name="Unknown Item 29524", score=0, rank=1, src="Vendor"},
                {id=21873, name="Unknown Item 21873", score=0, rank=2, src="Pre-Raid"},
                {id=28751, name="Unknown Item 28751", score=0, rank=3, src="Kara/T4"},
            },
            [7] = {
                {id=30727, name="Unknown Item 30727", score=0, rank=1, src="Kara/T4"},
                {id=28751, name="Unknown Item 28751", score=0, rank=2, src="Kara/T4"},
                {id=28591, name="Unknown Item 28591", score=0, rank=3, src="Kara/T4"},
            },
            [8] = {
                {id=30737, name="Unknown Item 30737", score=0, rank=1, src="Kara/T4"},
                {id=28752, name="Unknown Item 28752", score=0, rank=2, src="Kara/T4"},
                {id=27411, name="Unknown Item 27411", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=29523, name="Unknown Item 29523", score=0, rank=1, src="Vendor"},
                {id=29183, name="Unknown Item 29183", score=0, rank=2, src="Pre-Raid"},
                {id=28503, name="Unknown Item 28503", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=28520, name="Unknown Item 28520", score=0, rank=1, src="Kara/T4"},
                {id=28521, name="Unknown Item 28521", score=0, rank=2, src="Kara/T4"},
                {id=28508, name="Unknown Item 28508", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=28763, name="Jade Ring of the Everliving", score=61.2, rank=1, src="Kara/T4"},
                {id=28790, name="Naaru Lightwarden's Band", score=69.1, rank=2, src="Kara/T4"},
                {id=30736, name="Ring of Flowing Light", score=79, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=28590, name="Ribbon of Sacrifice", score=65.7, rank=2, src="SSC/TK"},
                {id=30841, name="Lower City Prayerbook", score=63, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=28765, name="Unknown Item 28765", score=0, rank=1, src="Kara/T4"},
                {id=31329, name="Unknown Item 31329", score=0, rank=2, src="Pre-Raid"},
                {id=24254, name="Unknown Item 24254", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [2] = {
        },
        [3] = {
            [1] = {
                {id=31012, name="Unknown Item 31012", score=0, rank=1, src="BT/Hyjal"},
                {id=32241, name="Unknown Item 32241", score=0, rank=2, src="BT/Hyjal"},
                {id=30166, name="Unknown Item 30166", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=32370, name="Nadina's Pendant of Purity", score=92, rank=1, src="BT/Hyjal"},
                {id=30018, name="Lord Sanguinar's Claim", score=86.9, rank=2, src="BT/Hyjal"},
                {id=33922, name="Vindicator's Pendant of Salvation", score=60.5, rank=3, src="BT/Hyjal"},
            },
            [3] = {
                {id=31022, name="Unknown Item 31022", score=0, rank=1, src="BT/Hyjal"},
                {id=32579, name="Unknown Item 32579", score=0, rank=2, src="BT/Hyjal"},
                {id=30168, name="Unknown Item 30168", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=31016, name="Unknown Item 31016", score=0, rank=1, src="BT/Hyjal"},
                {id=30164, name="Unknown Item 30164", score=0, rank=2, src="BT/Hyjal"},
                {id=30887, name="Unknown Item 30887", score=0, rank=3, src="BT/Hyjal"},
            },
            [6] = {
                {id=32258, name="Unknown Item 32258", score=0, rank=1, src="BT/Hyjal"},
                {id=32339, name="Unknown Item 32339", score=0, rank=2, src="BT/Hyjal"},
                {id=30895, name="Unknown Item 30895", score=0, rank=3, src="BT/Hyjal"},
            },
            [7] = {
                {id=31019, name="Unknown Item 31019", score=0, rank=1, src="BT/Hyjal"},
                {id=30912, name="Unknown Item 30912", score=0, rank=2, src="BT/Hyjal"},
                {id=32271, name="Unknown Item 32271", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=30873, name="Unknown Item 30873", score=0, rank=1, src="BT/Hyjal"},
                {id=32609, name="Unknown Item 32609", score=0, rank=2, src="BT/Hyjal"},
                {id=30737, name="Unknown Item 30737", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=32577, name="Unknown Item 32577", score=0, rank=1, src="BT/Hyjal"},
                {id=32584, name="Unknown Item 32584", score=0, rank=2, src="BT/Hyjal"},
                {id=32582, name="Unknown Item 32582", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=32328, name="Unknown Item 32328", score=0, rank=1, src="BT/Hyjal"},
                {id=32275, name="Unknown Item 32275", score=0, rank=2, src="BT/Hyjal"},
                {id=29976, name="Unknown Item 29976", score=0, rank=3, src="SSC/TK"},
            },
            [11] = {
                {id=32528, name="Blessed Band of Karabor", score=81.7, rank=1, src="BT/Hyjal"},
                {id=29309, name="Band of the Eternal Restorer", score=77.9, rank=2, src="BT/Hyjal"},
                {id=32238, name="Ring of Calming Waves", score=90.4, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=32496, name="Memento of Tyrande", score=106.2, rank=1, src="BT/Hyjal"},
                {id=29376, name="Essence of the Martyr", score=75.6, rank=2, src="Pre-Raid"},
                {id=38288, name="Direbrew Hops", score=75.6, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=34012, name="Unknown Item 34012", score=0, rank=2, src="BT/Hyjal"},
                {id=29989, name="Unknown Item 29989", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [4] = {
            [1] = {
                {id=31012, name="Unknown Item 31012", score=0, rank=1, src="BT/Hyjal"},
                {id=32241, name="Unknown Item 32241", score=0, rank=2, src="BT/Hyjal"},
                {id=30166, name="Unknown Item 30166", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=33281, name="Brooch of Nature's Mercy", score=93.8, rank=1, src="ZA"},
                {id=32370, name="Nadina's Pendant of Purity", score=92, rank=2, src="BT/Hyjal"},
                {id=35317, name="Vindicator's Pendant of Reprieve", score=59.3, rank=3, src="ZA"},
            },
            [3] = {
                {id=31022, name="Unknown Item 31022", score=0, rank=1, src="BT/Hyjal"},
                {id=32579, name="Unknown Item 32579", score=0, rank=2, src="BT/Hyjal"},
                {id=33464, name="Unknown Item 33464", score=0, rank=3, src="ZA"},
            },
            [5] = {
                {id=31016, name="Unknown Item 31016", score=0, rank=1, src="BT/Hyjal"},
                {id=30164, name="Unknown Item 30164", score=0, rank=2, src="BT/Hyjal"},
                {id=33469, name="Unknown Item 33469", score=0, rank=3, src="ZA"},
            },
            [6] = {
                {id=32258, name="Unknown Item 32258", score=0, rank=1, src="BT/Hyjal"},
                {id=32339, name="Unknown Item 32339", score=0, rank=2, src="BT/Hyjal"},
                {id=30895, name="Unknown Item 30895", score=0, rank=3, src="BT/Hyjal"},
            },
            [7] = {
                {id=31019, name="Unknown Item 31019", score=0, rank=1, src="BT/Hyjal"},
                {id=30912, name="Unknown Item 30912", score=0, rank=2, src="BT/Hyjal"},
                {id=32271, name="Unknown Item 32271", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=33324, name="Unknown Item 33324", score=0, rank=1, src="ZA"},
                {id=33471, name="Unknown Item 33471", score=0, rank=2, src="ZA"},
                {id=30873, name="Unknown Item 30873", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=32577, name="Unknown Item 32577", score=0, rank=1, src="BT/Hyjal"},
                {id=32584, name="Unknown Item 32584", score=0, rank=2, src="BT/Hyjal"},
                {id=32582, name="Unknown Item 32582", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=32328, name="Unknown Item 32328", score=0, rank=1, src="BT/Hyjal"},
                {id=32275, name="Unknown Item 32275", score=0, rank=2, src="BT/Hyjal"},
                {id=29976, name="Unknown Item 29976", score=0, rank=3, src="SSC/TK"},
            },
            [11] = {
                {id=32528, name="Blessed Band of Karabor", score=81.7, rank=1, src="BT/Hyjal"},
                {id=33498, name="Signet of the Quiet Forest", score=67.7, rank=2, src="ZA"},
                {id=29309, name="Band of the Eternal Restorer", score=77.9, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=32496, name="Memento of Tyrande", score=106.2, rank=1, src="BT/Hyjal"},
                {id=29376, name="Essence of the Martyr", score=75.6, rank=2, src="Pre-Raid"},
                {id=38288, name="Direbrew Hops", score=75.6, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=34012, name="Unknown Item 34012", score=0, rank=2, src="BT/Hyjal"},
                {id=33592, name="Unknown Item 33592", score=0, rank=3, src="ZA"},
            },
        },
        [5] = {
            [1] = {
                {id=34402, name="Unknown Item 34402", score=0, rank=1, src="SWP"},
                {id=34339, name="Unknown Item 34339", score=0, rank=2, src="SWP"},
                {id=35184, name="Unknown Item 35184", score=0, rank=3, src="SWP"},
            },
            [2] = {
                {id=34360, name="Amulet of Flowing Life", score=73.6, rank=1, src="SWP"},
                {id=33281, name="Brooch of Nature's Mercy", score=93.8, rank=2, src="ZA"},
                {id=34184, name="Brooch of the Highborne", score=81.7, rank=3, src="SWP"},
            },
            [3] = {
                {id=31022, name="Unknown Item 31022", score=0, rank=1, src="BT/Hyjal"},
                {id=34208, name="Unknown Item 34208", score=0, rank=2, src="SWP"},
                {id=34202, name="Unknown Item 34202", score=0, rank=3, src="SWP"},
            },
            [5] = {
                {id=34375, name="Unknown Item 34375", score=0, rank=1, src="SWP"},
                {id=34212, name="Unknown Item 34212", score=0, rank=2, src="SWP"},
                {id=34229, name="Unknown Item 34229", score=0, rank=3, src="SWP"},
            },
            [6] = {
                {id=34543, name="Unknown Item 34543", score=0, rank=1, src="SWP"},
                {id=32258, name="Unknown Item 32258", score=0, rank=2, src="BT/Hyjal"},
                {id=32339, name="Unknown Item 32339", score=0, rank=3, src="BT/Hyjal"},
            },
            [7] = {
                {id=34383, name="Unknown Item 34383", score=0, rank=1, src="SWP"},
                {id=31019, name="Unknown Item 31019", score=0, rank=2, src="BT/Hyjal"},
                {id=34931, name="Unknown Item 34931", score=0, rank=3, src="SWP"},
            },
            [8] = {
                {id=34565, name="Unknown Item 34565", score=0, rank=1, src="SWP"},
                {id=33324, name="Unknown Item 33324", score=0, rank=2, src="ZA"},
                {id=33471, name="Unknown Item 33471", score=0, rank=3, src="ZA"},
            },
            [9] = {
                {id=34438, name="Unknown Item 34438", score=0, rank=1, src="SWP"},
                {id=32577, name="Unknown Item 32577", score=0, rank=2, src="BT/Hyjal"},
                {id=32584, name="Unknown Item 32584", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=32328, name="Unknown Item 32328", score=0, rank=1, src="BT/Hyjal"},
                {id=34372, name="Unknown Item 34372", score=0, rank=2, src="SWP"},
                {id=34409, name="Unknown Item 34409", score=0, rank=3, src="SWP"},
            },
            [11] = {
                {id=32528, name="Blessed Band of Karabor", score=81.7, rank=1, src="BT/Hyjal"},
                {id=34363, name="Ring of Flowing Life", score=79.9, rank=2, src="SWP"},
                {id=34166, name="Band of Lucent Beams", score=85.6, rank=3, src="SWP"},
            },
            [13] = {
                {id=35750, name="Redeemer's Alchemist Stone", score=107.1, rank=1, src="SWP"},
                {id=28823, name="Eye of Gruul", score=39.6, rank=2, src="Kara/T4"},
                {id=32496, name="Memento of Tyrande", score=106.2, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=34242, name="Unknown Item 34242", score=0, rank=2, src="SWP"},
                {id=34205, name="Unknown Item 34205", score=0, rank=3, src="SWP"},
            },
        },
    },
}
for k,v in pairs(_d) do IRR_BIS_DATA[k] = v end
end
