-- BIS_Data_PRIEST.lua  (Auto-generated by scripts/update-bis.ps1)
-- Generated: 2026-03-01 19:52  -- DO NOT EDIT MANUALLY
IRR_BIS_DATA = IRR_BIS_DATA or {}
do local _d = {
    ["shadow_priest"] = {
        [0] = {
            [1] = {
                {id=24266, name="Unknown Item 24266", score=0, rank=1, src="Vendor"},
                {id=31104, name="Unknown Item 31104", score=0, rank=2, src="Pre-Raid"},
                {id=28415, name="Unknown Item 28415", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=28245, name="Pendant of Dominance", score=38.7, rank=1, src="Pre-Raid"},
                {id=18814, name="Choker of the Fire Lord", score=40.3, rank=2, src="Pre-Raid"},
                {id=31693, name="Natasha's Arcane Filament", score=39.2, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=21869, name="Unknown Item 21869", score=0, rank=1, src="Kara/T4"},
                {id=27778, name="Unknown Item 27778", score=0, rank=2, src="Shadow Lab"},
                {id=27738, name="Unknown Item 27738", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=21871, name="Unknown Item 21871", score=0, rank=1, src="Kara/T4"},
                {id=28232, name="Unknown Item 28232", score=0, rank=2, src="Pre-Raid"},
                {id=31297, name="Unknown Item 31297", score=0, rank=3, src="Kara/T4"},
            },
            [6] = {
                {id=24256, name="Unknown Item 24256", score=0, rank=1, src="Vendor"},
                {id=27843, name="Unknown Item 27843", score=0, rank=2, src="Pre-Raid"},
                {id=31461, name="Unknown Item 31461", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=24262, name="Unknown Item 24262", score=0, rank=1, src="Vendor"},
                {id=30531, name="Unknown Item 30531", score=0, rank=2, src="Pre-Raid"},
                {id=30532, name="Unknown Item 30532", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=21870, name="Unknown Item 21870", score=0, rank=1, src="Kara/T4"},
                {id=28179, name="Unknown Item 28179", score=0, rank=2, src="Pre-Raid"},
                {id=28406, name="Unknown Item 28406", score=0, rank=3, src="Arcatraz"},
            },
            [9] = {
                {id=24250, name="Unknown Item 24250", score=0, rank=1, src="Vendor"},
                {id=27746, name="Unknown Item 27746", score=0, rank=2, src="Pre-Raid"},
                {id=28174, name="Unknown Item 28174", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=29317, name="Unknown Item 29317", score=0, rank=1, src="Pre-Raid"},
                {id=24450, name="Unknown Item 24450", score=0, rank=2, src="Pre-Raid"},
                {id=27889, name="Unknown Item 27889", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=21709, name="Ring of the Fallen God", score=51.9, rank=1, src="Pre-Raid"},
                {id=23031, name="Band of the Inevitable", score=45.6, rank=2, src="Pre-Raid"},
                {id=29352, name="Cobalt Band of Tyrigosa", score=50.5, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=1, src="Pre-Raid"},
                {id=27683, name="Quagmirran's Eye", score=37, rank=2, src="Slave Pens"},
                {id=23207, name="Mark of the Champion", score=0, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=24252, name="Unknown Item 24252", score=0, rank=1, src="Pre-Raid"},
                {id=22731, name="Unknown Item 22731", score=0, rank=2, src="Pre-Raid"},
                {id=30971, name="Unknown Item 30971", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [1] = {
            [1] = {
                {id=24266, name="Unknown Item 24266", score=0, rank=1, src="Vendor"},
                {id=28804, name="Unknown Item 28804", score=0, rank=2, src="Kara/T4"},
                {id=29058, name="Unknown Item 29058", score=0, rank=3, src="Kara/T4"},
            },
            [2] = {
                {id=30666, name="Ritssyn's Lost Pendant", score=2.4, rank=1, src="Kara/T4"},
                {id=24121, name="Chain of the Twilight Owl", score=36.2, rank=2, src="Pre-Raid"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=21869, name="Unknown Item 21869", score=0, rank=1, src="Kara/T4"},
                {id=29060, name="Unknown Item 29060", score=0, rank=2, src="Kara/T4"},
                {id=27778, name="Unknown Item 27778", score=0, rank=3, src="Shadow Lab"},
            },
            [5] = {
                {id=21871, name="Unknown Item 21871", score=0, rank=1, src="Kara/T4"},
                {id=29056, name="Unknown Item 29056", score=0, rank=2, src="Kara/T4"},
                {id=28232, name="Unknown Item 28232", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=28799, name="Unknown Item 28799", score=0, rank=1, src="Gruul"},
                {id=24256, name="Unknown Item 24256", score=0, rank=2, src="Vendor"},
            },
            [7] = {
                {id=24262, name="Unknown Item 24262", score=0, rank=1, src="Vendor"},
                {id=30734, name="Unknown Item 30734", score=0, rank=2, src="Kara/T4"},
                {id=28594, name="Unknown Item 28594", score=0, rank=3, src="Kara"},
            },
            [8] = {
                {id=21870, name="Unknown Item 21870", score=0, rank=1, src="Kara/T4"},
                {id=28517, name="Unknown Item 28517", score=0, rank=2, src="Kara"},
                {id=28585, name="Unknown Item 28585", score=0, rank=3, src="Kara"},
            },
            [9] = {
                {id=24250, name="Unknown Item 24250", score=0, rank=1, src="Vendor"},
                {id=28515, name="Unknown Item 28515", score=0, rank=2, src="Kara/T4"},
                {id=28477, name="Unknown Item 28477", score=0, rank=3, src="Kara/T4"},
            },
            [10] = {
                {id=28507, name="Unknown Item 28507", score=0, rank=1, src="Kara"},
                {id=28780, name="Unknown Item 28780", score=0, rank=2, src="Kara/T4"},
                {id=30725, name="Unknown Item 30725", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=21709, name="Ring of the Fallen God", score=51.9, rank=1, src="Pre-Raid"},
                {id=23031, name="Band of the Inevitable", score=45.6, rank=2, src="Pre-Raid"},
                {id=28753, name="Ring of Recurrence", score=62.6, rank=3, src="Kara"},
            },
            [13] = {
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=1, src="Pre-Raid"},
                {id=27683, name="Quagmirran's Eye", score=37, rank=2, src="Slave Pens"},
                {id=28789, name="Eye of Magtheridon", score=54, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=28570, name="Unknown Item 28570", score=0, rank=1, src="Kara/T4"},
                {id=28766, name="Unknown Item 28766", score=0, rank=2, src="Kara"},
                {id=28797, name="Unknown Item 28797", score=0, rank=3, src="Gruul"},
            },
        },
        [2] = {
            [1] = {
                {id=32494, name="Unknown Item 32494", score=0, rank=1, src="SSC/TK"},
                {id=30161, name="Unknown Item 30161", score=0, rank=2, src="SSC/TK"},
                {id=29986, name="Unknown Item 29986", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=30666, name="Ritssyn's Lost Pendant", score=2.4, rank=1, src="Kara/T4"},
                {id=24121, name="Chain of the Twilight Owl", score=36.2, rank=2, src="Pre-Raid"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=30163, name="Unknown Item 30163", score=0, rank=1, src="SSC/TK"},
                {id=21869, name="Unknown Item 21869", score=0, rank=2, src="Kara/T4"},
                {id=30079, name="Unknown Item 30079", score=0, rank=3, src="SSC"},
            },
            [5] = {
                {id=30107, name="Unknown Item 30107", score=0, rank=1, src="SSC"},
                {id=30159, name="Unknown Item 30159", score=0, rank=2, src="SSC/TK"},
                {id=21871, name="Unknown Item 21871", score=0, rank=3, src="Kara/T4"},
            },
            [6] = {
                {id=30675, name="Unknown Item 30675", score=0, rank=1, src="SSC/TK"},
                {id=30038, name="Unknown Item 30038", score=0, rank=2, src="Vendor"},
                {id=30064, name="Unknown Item 30064", score=0, rank=3, src="SSC"},
            },
            [7] = {
                {id=29972, name="Unknown Item 29972", score=0, rank=1, src="SSC/TK"},
                {id=30162, name="Unknown Item 30162", score=0, rank=2, src="SSC/TK"},
                {id=24262, name="Unknown Item 24262", score=0, rank=3, src="Vendor"},
            },
            [8] = {
                {id=30680, name="Unknown Item 30680", score=0, rank=1, src="SSC/TK"},
                {id=21870, name="Unknown Item 21870", score=0, rank=2, src="Kara/T4"},
                {id=30050, name="Unknown Item 30050", score=0, rank=3, src="SSC/TK"},
            },
            [9] = {
                {id=30684, name="Unknown Item 30684", score=0, rank=1, src="SSC/TK"},
                {id=31225, name="Unknown Item 31225", score=0, rank=2, src="SSC/TK"},
                {id=24692, name="Unknown Item 24692", score=0, rank=3, src="SSC/TK"},
            },
            [10] = {
                {id=31166, name="Unknown Item 31166", score=0, rank=1, src="SSC/TK"},
                {id=28507, name="Unknown Item 28507", score=0, rank=2, src="Kara"},
                {id=28780, name="Unknown Item 28780", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=30109, name="Ring of Endless Coils", score=59.9, rank=1, src="SSC"},
                {id=29922, name="Band of Al'ar", score=57.8, rank=2, src="SSC/TK"},
                {id=21709, name="Ring of the Fallen God", score=51.9, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=1, src="Pre-Raid"},
                {id=27683, name="Quagmirran's Eye", score=37, rank=2, src="Slave Pens"},
                {id=28789, name="Eye of Magtheridon", score=54, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=31201, name="Unknown Item 31201", score=0, rank=1, src="SSC/TK"},
                {id=29992, name="Unknown Item 29992", score=0, rank=2, src="SSC/TK"},
                {id=25043, name="Unknown Item 25043", score=0, rank=3, src="SSC/TK"},
            },
        },
        [3] = {
            [1] = {
                {id=31064, name="Unknown Item 31064", score=0, rank=1, src="BT/Hyjal"},
                {id=32525, name="Unknown Item 32525", score=0, rank=2, src="BT"},
                {id=32494, name="Unknown Item 32494", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=32349, name="Translucent Spellthread Necklace", score=85.6, rank=1, src="BT"},
                {id=24121, name="Chain of the Twilight Owl", score=36.2, rank=2, src="Pre-Raid"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=31070, name="Unknown Item 31070", score=0, rank=1, src="BT/Hyjal"},
                {id=32587, name="Unknown Item 32587", score=0, rank=2, src="BT/Hyjal"},
                {id=30884, name="Unknown Item 30884", score=0, rank=3, src="Hyjal"},
            },
            [5] = {
                {id=31065, name="Unknown Item 31065", score=0, rank=1, src="BT/Hyjal"},
                {id=30107, name="Unknown Item 30107", score=0, rank=2, src="SSC"},
                {id=30159, name="Unknown Item 30159", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=32256, name="Unknown Item 32256", score=0, rank=1, src="BT/Hyjal"},
                {id=30038, name="Unknown Item 30038", score=0, rank=2, src="Vendor"},
                {id=30675, name="Unknown Item 30675", score=0, rank=3, src="SSC/TK"},
            },
            [7] = {
                {id=30916, name="Unknown Item 30916", score=0, rank=1, src="Hyjal"},
                {id=32367, name="Unknown Item 32367", score=0, rank=2, src="BT"},
                {id=31067, name="Unknown Item 31067", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=32239, name="Unknown Item 32239", score=0, rank=1, src="BT"},
                {id=21870, name="Unknown Item 21870", score=0, rank=2, src="Kara/T4"},
                {id=30680, name="Unknown Item 30680", score=0, rank=3, src="SSC/TK"},
            },
            [9] = {
                {id=32586, name="Unknown Item 32586", score=0, rank=1, src="Vendor"},
                {id=30870, name="Unknown Item 30870", score=0, rank=2, src="BT/Hyjal"},
                {id=32270, name="Unknown Item 32270", score=0, rank=3, src="BT"},
            },
            [10] = {
                {id=31061, name="Unknown Item 31061", score=0, rank=1, src="BT/Hyjal"},
                {id=28507, name="Unknown Item 28507", score=0, rank=2, src="Kara"},
                {id=28780, name="Unknown Item 28780", score=0, rank=3, src="Kara/T4"},
            },
            [11] = {
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=1, src="BT"},
                {id=32528, name="Blessed Band of Karabor", score=43, rank=2, src="BT/Hyjal"},
                {id=32247, name="Ring of Captured Storms", score=90.9, rank=3, src="BT"},
            },
            [13] = {
                {id=32483, name="The Skull of Gul'dan", score=85, rank=1, src="BT"},
                {id=31856, name="Darkmoon Card: Crusade", score=0, rank=2, src="BT/Hyjal"},
                {id=29370, name="Icon of the Silver Crescent", score=43, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=32590, name="Unknown Item 32590", score=0, rank=1, src="BT/Hyjal"},
                {id=32524, name="Unknown Item 32524", score=0, rank=2, src="BT"},
                {id=32331, name="Unknown Item 32331", score=0, rank=3, src="BT"},
            },
        },
        [4] = {
            [1] = {
                {id=31064, name="Unknown Item 31064", score=0, rank=1, src="BT/Hyjal"},
                {id=32525, name="Unknown Item 32525", score=0, rank=2, src="BT"},
                {id=32494, name="Unknown Item 32494", score=0, rank=3, src="SSC/TK"},
            },
            [2] = {
                {id=33466, name="Loop of Cursed Bones", score=49.9, rank=1, src="ZA"},
                {id=24121, name="Chain of the Twilight Owl", score=36.2, rank=2, src="Pre-Raid"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=31070, name="Unknown Item 31070", score=0, rank=1, src="BT/Hyjal"},
                {id=32587, name="Unknown Item 32587", score=0, rank=2, src="BT/Hyjal"},
                {id=30884, name="Unknown Item 30884", score=0, rank=3, src="Hyjal"},
            },
            [5] = {
                {id=31065, name="Unknown Item 31065", score=0, rank=1, src="BT/Hyjal"},
                {id=30107, name="Unknown Item 30107", score=0, rank=2, src="SSC"},
                {id=30159, name="Unknown Item 30159", score=0, rank=3, src="SSC/TK"},
            },
            [6] = {
                {id=32256, name="Unknown Item 32256", score=0, rank=1, src="BT/Hyjal"},
                {id=30038, name="Unknown Item 30038", score=0, rank=2, src="Vendor"},
                {id=30675, name="Unknown Item 30675", score=0, rank=3, src="SSC/TK"},
            },
            [7] = {
                {id=30916, name="Unknown Item 30916", score=0, rank=1, src="Hyjal"},
                {id=32367, name="Unknown Item 32367", score=0, rank=2, src="BT"},
                {id=33584, name="Unknown Item 33584", score=0, rank=3, src="ZA"},
            },
            [8] = {
                {id=32239, name="Unknown Item 32239", score=0, rank=1, src="BT"},
                {id=21870, name="Unknown Item 21870", score=0, rank=2, src="Kara/T4"},
                {id=33357, name="Unknown Item 33357", score=0, rank=3, src="ZA"},
            },
            [9] = {
                {id=32586, name="Unknown Item 32586", score=0, rank=1, src="Vendor"},
                {id=30870, name="Unknown Item 30870", score=0, rank=2, src="BT/Hyjal"},
                {id=32270, name="Unknown Item 32270", score=0, rank=3, src="BT"},
            },
            [10] = {
                {id=31061, name="Unknown Item 31061", score=0, rank=1, src="BT/Hyjal"},
                {id=33586, name="Unknown Item 33586", score=0, rank=2, src="ZA"},
                {id=28507, name="Unknown Item 28507", score=0, rank=3, src="Kara"},
            },
            [11] = {
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=1, src="BT"},
                {id=33497, name="Mana Attuned Band", score=70.8, rank=2, src="ZA"},
                {id=29305, name="Band of the Eternal Sage", score=78.4, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=33829, name="Hex Shrunken Head", score=53, rank=1, src="ZA"},
                {id=32483, name="The Skull of Gul'dan", score=85, rank=2, src="BT"},
                {id=23207, name="Mark of the Champion", score=0, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=32590, name="Unknown Item 32590", score=0, rank=1, src="BT/Hyjal"},
                {id=33591, name="Unknown Item 33591", score=0, rank=2, src="ZA"},
                {id=32524, name="Unknown Item 32524", score=0, rank=3, src="BT"},
            },
        },
        [5] = {
            [1] = {
                {id=34340, name="Unknown Item 34340", score=0, rank=1, src="SWP"},
                {id=34847, name="Unknown Item 34847", score=0, rank=2, src="SWP"},
                {id=31064, name="Unknown Item 31064", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=34204, name="Amulet of Unfettered Magics", score=73, rank=1, src="SWP"},
                {id=24121, name="Chain of the Twilight Owl", score=36.2, rank=2, src="Pre-Raid"},
                {id=24116, name="Eye of the Night", score=42.6, rank=3, src="Vendor"},
            },
            [3] = {
                {id=31070, name="Unknown Item 31070", score=0, rank=1, src="BT/Hyjal"},
                {id=34210, name="Unknown Item 34210", score=0, rank=2, src="SWP"},
                {id=34393, name="Unknown Item 34393", score=0, rank=3, src="SWP"},
            },
            [5] = {
                {id=34364, name="Unknown Item 34364", score=0, rank=1, src="Vendor"},
                {id=34232, name="Unknown Item 34232", score=0, rank=2, src="SWP"},
                {id=31065, name="Unknown Item 31065", score=0, rank=3, src="BT/Hyjal"},
            },
            [6] = {
                {id=34528, name="Unknown Item 34528", score=0, rank=1, src="SWP"},
                {id=32256, name="Unknown Item 32256", score=0, rank=2, src="BT/Hyjal"},
                {id=30038, name="Unknown Item 30038", score=0, rank=3, src="Vendor"},
            },
            [7] = {
                {id=34181, name="Unknown Item 34181", score=0, rank=1, src="SWP"},
                {id=34386, name="Unknown Item 34386", score=0, rank=2, src="SWP"},
                {id=30916, name="Unknown Item 30916", score=0, rank=3, src="Hyjal"},
            },
            [8] = {
                {id=34563, name="Unknown Item 34563", score=0, rank=1, src="SWP"},
                {id=32239, name="Unknown Item 32239", score=0, rank=2, src="BT"},
                {id=21870, name="Unknown Item 21870", score=0, rank=3, src="Kara/T4"},
            },
            [9] = {
                {id=34434, name="Unknown Item 34434", score=0, rank=1, src="SWP"},
                {id=32586, name="Unknown Item 32586", score=0, rank=2, src="Vendor"},
                {id=30870, name="Unknown Item 30870", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=34344, name="Unknown Item 34344", score=0, rank=1, src="SWP"},
                {id=31061, name="Unknown Item 31061", score=0, rank=2, src="BT/Hyjal"},
                {id=34406, name="Unknown Item 34406", score=0, rank=3, src="SWP"},
            },
            [11] = {
                {id=34230, name="Ring of Omnipotence", score=73.1, rank=1, src="SWP"},
                {id=32527, name="Ring of Ancient Knowledge", score=58, rank=2, src="BT"},
                {id=34362, name="Loop of Forged Power", score=81.9, rank=3, src="Vendor"},
            },
            [13] = {
                {id=34429, name="Shifting Naaru Sliver", score=0, rank=1, src="SWP"},
                {id=33829, name="Hex Shrunken Head", score=53, rank=2, src="ZA"},
                {id=32483, name="The Skull of Gul'dan", score=85, rank=3, src="BT"},
            },
            [15] = {
                {id=34242, name="Unknown Item 34242", score=0, rank=1, src="SWP"},
                {id=32590, name="Unknown Item 32590", score=0, rank=2, src="BT/Hyjal"},
                {id=33591, name="Unknown Item 33591", score=0, rank=3, src="ZA"},
            },
        },
    },
    ["holy_priest"] = {
        [0] = {
            [1] = {
                {id=32090, name="Unknown Item 32090", score=0, rank=1, src="Pre-Raid"},
                {id=24264, name="Unknown Item 24264", score=0, rank=2, src="Pre-Raid"},
                {id=28413, name="Unknown Item 28413", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=30377, name="Karja's Medallion", score=65, rank=1, src="Pre-Raid"},
                {id=29374, name="Necklace of Eternal Hope", score=60.1, rank=2, src="Pre-Raid"},
                {id=28233, name="Necklace of Resplendent Hope", score=47.7, rank=3, src="Pre-Raid"},
            },
            [3] = {
                {id=21874, name="Unknown Item 21874", score=0, rank=1, src="Pre-Raid"},
                {id=27775, name="Unknown Item 27775", score=0, rank=2, src="Pre-Raid"},
                {id=27433, name="Unknown Item 27433", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=21875, name="Unknown Item 21875", score=0, rank=1, src="Pre-Raid"},
                {id=28230, name="Unknown Item 28230", score=0, rank=2, src="Pre-Raid"},
                {id=24397, name="Unknown Item 24397", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=21873, name="Unknown Item 21873", score=0, rank=1, src="Pre-Raid"},
                {id=29250, name="Unknown Item 29250", score=0, rank=2, src="Pre-Raid"},
                {id=21582, name="Unknown Item 21582", score=0, rank=3, src="Pre-Raid"},
            },
            [7] = {
                {id=24261, name="Unknown Item 24261", score=0, rank=1, src="Pre-Raid"},
                {id=30543, name="Unknown Item 30543", score=0, rank=2, src="Pre-Raid"},
                {id=31343, name="Unknown Item 31343", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=29251, name="Unknown Item 29251", score=0, rank=1, src="Pre-Raid"},
                {id=27411, name="Unknown Item 27411", score=0, rank=2, src="Pre-Raid"},
                {id=28179, name="Unknown Item 28179", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=29183, name="Unknown Item 29183", score=0, rank=1, src="Pre-Raid"},
                {id=29249, name="Unknown Item 29249", score=0, rank=2, src="Pre-Raid"},
                {id=21604, name="Unknown Item 21604", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=27536, name="Unknown Item 27536", score=0, rank=1, src="Pre-Raid"},
                {id=24393, name="Unknown Item 24393", score=0, rank=2, src="Pre-Raid"},
                {id=28304, name="Unknown Item 28304", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=29373, name="Band of Halos", score=58.3, rank=1, src="Pre-Raid"},
                {id=31923, name="Band of the Crystalline Void", score=53.6, rank=2, src="Pre-Raid"},
                {id=31383, name="Spiritualist's Mark of the Sha'tar", score=63.6, rank=3, src="Pre-Raid"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=21625, name="Scarab Brooch", score=0, rank=2, src="Pre-Raid"},
                {id=19288, name="Darkmoon Card: Blue Dragon", score=0, rank=3, src="Pre-Raid"},
            },
            [15] = {
                {id=29354, name="Unknown Item 29354", score=0, rank=1, src="Kara/T4"},
                {id=29375, name="Unknown Item 29375", score=0, rank=2, src="Pre-Raid"},
                {id=24254, name="Unknown Item 24254", score=0, rank=3, src="Pre-Raid"},
            },
        },
        [1] = {
            [1] = {
                {id=29049, name="Unknown Item 29049", score=0, rank=1, src="Kara/T4"},
                {id=32090, name="Unknown Item 32090", score=0, rank=2, src="Pre-Raid"},
                {id=24264, name="Unknown Item 24264", score=0, rank=3, src="Pre-Raid"},
            },
            [2] = {
                {id=30726, name="Archaic Charm of Presence", score=83.6, rank=1, src="Kara/T4"},
                {id=28822, name="Teeth of Gruul", score=65.6, rank=2, src="Kara/T4"},
                {id=28609, name="Emberspur Talisman", score=59.4, rank=3, src="Kara/T4"},
            },
            [3] = {
                {id=21874, name="Unknown Item 21874", score=0, rank=1, src="Pre-Raid"},
                {id=29054, name="Unknown Item 29054", score=0, rank=2, src="Kara/T4"},
                {id=27775, name="Unknown Item 27775", score=0, rank=3, src="Pre-Raid"},
            },
            [5] = {
                {id=21875, name="Unknown Item 21875", score=0, rank=1, src="Pre-Raid"},
                {id=29050, name="Unknown Item 29050", score=0, rank=2, src="Kara/T4"},
                {id=28578, name="Unknown Item 28578", score=0, rank=3, src="Kara/T4"},
            },
            [6] = {
                {id=28652, name="Unknown Item 28652", score=0, rank=1, src="Kara/T4"},
                {id=29250, name="Unknown Item 29250", score=0, rank=2, src="Pre-Raid"},
            },
            [7] = {
                {id=30727, name="Unknown Item 30727", score=0, rank=1, src="Kara/T4"},
                {id=28742, name="Unknown Item 28742", score=0, rank=2, src="Kara/T4"},
                {id=30543, name="Unknown Item 30543", score=0, rank=3, src="Pre-Raid"},
            },
            [8] = {
                {id=28663, name="Unknown Item 28663", score=0, rank=1, src="Kara/T4"},
                {id=29251, name="Unknown Item 29251", score=0, rank=2, src="Pre-Raid"},
                {id=27411, name="Unknown Item 27411", score=0, rank=3, src="Pre-Raid"},
            },
            [9] = {
                {id=29183, name="Unknown Item 29183", score=0, rank=1, src="Pre-Raid"},
                {id=28511, name="Unknown Item 28511", score=0, rank=2, src="Kara/T4"},
                {id=29249, name="Unknown Item 29249", score=0, rank=3, src="Pre-Raid"},
            },
            [10] = {
                {id=28508, name="Unknown Item 28508", score=0, rank=1, src="Kara/T4"},
                {id=29055, name="Unknown Item 29055", score=0, rank=2, src="Kara/T4"},
                {id=24393, name="Unknown Item 24393", score=0, rank=3, src="Pre-Raid"},
            },
            [11] = {
                {id=30736, name="Ring of Flowing Light", score=79, rank=1, src="Kara/T4"},
                {id=29290, name="Violet Signet of the Grand Restorer", score=76.5, rank=2, src="Kara/T4"},
                {id=28763, name="Jade Ring of the Everliving", score=61.2, rank=3, src="Kara/T4"},
            },
            [13] = {
                {id=28823, name="Eye of Gruul", score=39.6, rank=1, src="Kara/T4"},
                {id=28590, name="Ribbon of Sacrifice", score=65.7, rank=2, src="SSC/TK"},
                {id=28190, name="Scarab of the Infinite Cycle", score=63, rank=3, src="Kara/T4"},
            },
            [15] = {
                {id=28765, name="Unknown Item 28765", score=0, rank=1, src="Kara/T4"},
                {id=31329, name="Unknown Item 31329", score=0, rank=2, src="Pre-Raid"},
                {id=29354, name="Unknown Item 29354", score=0, rank=3, src="Kara/T4"},
            },
            [17] = {
                {id=29170, name="Unknown Item 29170", score=0, rank=1, src="Kara/T4"},
                {id=29274, name="Unknown Item 29274", score=0, rank=2, src="Kara/T4"},
                {id=28728, name="Unknown Item 28728", score=0, rank=3, src="Kara/T4"},
            },
        },
        [2] = {
        },
        [3] = {
            [1] = {
                {id=31063, name="Unknown Item 31063", score=0, rank=1, src="BT/Hyjal"},
                {id=30152, name="Unknown Item 30152", score=0, rank=2, src="BT/Hyjal"},
                {id=32329, name="Unknown Item 32329", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=32370, name="Nadina's Pendant of Purity", score=92, rank=1, src="BT/Hyjal"},
                {id=30018, name="Lord Sanguinar's Claim", score=86.9, rank=2, src="BT/Hyjal"},
                {id=33922, name="Vindicator's Pendant of Salvation", score=60.5, rank=3, src="BT/Hyjal"},
            },
            [3] = {
                {id=31069, name="Unknown Item 31069", score=0, rank=1, src="BT/Hyjal"},
                {id=30154, name="Unknown Item 30154", score=0, rank=2, src="BT/Hyjal"},
                {id=32585, name="Unknown Item 32585", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=31066, name="Unknown Item 31066", score=0, rank=1, src="BT/Hyjal"},
                {id=30150, name="Unknown Item 30150", score=0, rank=2, src="BT/Hyjal"},
                {id=21875, name="Unknown Item 21875", score=0, rank=3, src="Pre-Raid"},
            },
            [6] = {
                {id=30895, name="Unknown Item 30895", score=0, rank=1, src="BT/Hyjal"},
                {id=32519, name="Unknown Item 32519", score=0, rank=2, src="BT/Hyjal"},
                {id=30036, name="Unknown Item 30036", score=0, rank=3, src="BT/Hyjal"},
            },
            [7] = {
                {id=30912, name="Unknown Item 30912", score=0, rank=1, src="BT/Hyjal"},
                {id=31068, name="Unknown Item 31068", score=0, rank=2, src="BT/Hyjal"},
                {id=30153, name="Unknown Item 30153", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=32609, name="Unknown Item 32609", score=0, rank=1, src="BT/Hyjal"},
                {id=30100, name="Unknown Item 30100", score=0, rank=2, src="BT/Hyjal"},
                {id=30885, name="Unknown Item 30885", score=0, rank=3, src="BT/Hyjal"},
            },
            [9] = {
                {id=32584, name="Unknown Item 32584", score=0, rank=1, src="BT/Hyjal"},
                {id=30871, name="Unknown Item 30871", score=0, rank=2, src="BT/Hyjal"},
                {id=32513, name="Unknown Item 32513", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=31060, name="Unknown Item 31060", score=0, rank=1, src="BT/Hyjal"},
                {id=30151, name="Unknown Item 30151", score=0, rank=2, src="BT/Hyjal"},
                {id=32353, name="Unknown Item 32353", score=0, rank=3, src="BT/Hyjal"},
            },
            [11] = {
                {id=32528, name="Blessed Band of Karabor", score=81.7, rank=1, src="BT/Hyjal"},
                {id=29309, name="Band of the Eternal Restorer", score=77.9, rank=2, src="BT/Hyjal"},
                {id=30110, name="Coral Band of the Revived", score=92.9, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=38288, name="Direbrew Hops", score=75.6, rank=2, src="BT/Hyjal"},
                {id=32496, name="Memento of Tyrande", score=106.2, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=29989, name="Unknown Item 29989", score=0, rank=2, src="BT/Hyjal"},
                {id=32337, name="Unknown Item 32337", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [4] = {
            [1] = {
                {id=31063, name="Unknown Item 31063", score=0, rank=1, src="BT/Hyjal"},
                {id=30152, name="Unknown Item 30152", score=0, rank=2, src="BT/Hyjal"},
                {id=32329, name="Unknown Item 32329", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=33281, name="Brooch of Nature's Mercy", score=93.8, rank=1, src="ZA"},
                {id=35317, name="Vindicator's Pendant of Reprieve", score=59.3, rank=2, src="ZA"},
                {id=32370, name="Nadina's Pendant of Purity", score=92, rank=3, src="BT/Hyjal"},
            },
            [3] = {
                {id=31069, name="Unknown Item 31069", score=0, rank=1, src="BT/Hyjal"},
                {id=30154, name="Unknown Item 30154", score=0, rank=2, src="BT/Hyjal"},
                {id=32585, name="Unknown Item 32585", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=31066, name="Unknown Item 31066", score=0, rank=1, src="BT/Hyjal"},
                {id=30150, name="Unknown Item 30150", score=0, rank=2, src="BT/Hyjal"},
                {id=33203, name="Unknown Item 33203", score=0, rank=3, src="ZA"},
            },
            [6] = {
                {id=30895, name="Unknown Item 30895", score=0, rank=1, src="BT/Hyjal"},
                {id=32519, name="Unknown Item 32519", score=0, rank=2, src="BT/Hyjal"},
                {id=30036, name="Unknown Item 30036", score=0, rank=3, src="BT/Hyjal"},
            },
            [7] = {
                {id=33585, name="Unknown Item 33585", score=0, rank=1, src="ZA"},
                {id=30912, name="Unknown Item 30912", score=0, rank=2, src="BT/Hyjal"},
                {id=31068, name="Unknown Item 31068", score=0, rank=3, src="BT/Hyjal"},
            },
            [8] = {
                {id=32609, name="Unknown Item 32609", score=0, rank=1, src="BT/Hyjal"},
                {id=30100, name="Unknown Item 30100", score=0, rank=2, src="BT/Hyjal"},
                {id=33471, name="Unknown Item 33471", score=0, rank=3, src="ZA"},
            },
            [9] = {
                {id=32584, name="Unknown Item 32584", score=0, rank=1, src="BT/Hyjal"},
                {id=30871, name="Unknown Item 30871", score=0, rank=2, src="BT/Hyjal"},
                {id=33589, name="Unknown Item 33589", score=0, rank=3, src="ZA"},
            },
            [10] = {
                {id=31060, name="Unknown Item 31060", score=0, rank=1, src="BT/Hyjal"},
                {id=30151, name="Unknown Item 30151", score=0, rank=2, src="BT/Hyjal"},
                {id=33587, name="Unknown Item 33587", score=0, rank=3, src="ZA"},
            },
            [11] = {
                {id=32528, name="Blessed Band of Karabor", score=81.7, rank=1, src="BT/Hyjal"},
                {id=33498, name="Signet of the Quiet Forest", score=67.7, rank=2, src="ZA"},
                {id=29309, name="Band of the Eternal Restorer", score=77.9, rank=3, src="BT/Hyjal"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=38288, name="Direbrew Hops", score=75.6, rank=2, src="BT/Hyjal"},
                {id=32496, name="Memento of Tyrande", score=106.2, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=33592, name="Unknown Item 33592", score=0, rank=2, src="ZA"},
                {id=29989, name="Unknown Item 29989", score=0, rank=3, src="BT/Hyjal"},
            },
        },
        [5] = {
            [1] = {
                {id=34339, name="Unknown Item 34339", score=0, rank=1, src="SWP"},
                {id=35181, name="Unknown Item 35181", score=0, rank=2, src="SWP"},
                {id=31063, name="Unknown Item 31063", score=0, rank=3, src="BT/Hyjal"},
            },
            [2] = {
                {id=33281, name="Brooch of Nature's Mercy", score=93.8, rank=1, src="ZA"},
                {id=34360, name="Amulet of Flowing Life", score=73.6, rank=2, src="SWP"},
                {id=37929, name="Guardian's Pendant of Reprieve", score=67.1, rank=3, src="SWP"},
            },
            [3] = {
                {id=34202, name="Unknown Item 34202", score=0, rank=1, src="SWP"},
                {id=31069, name="Unknown Item 31069", score=0, rank=2, src="BT/Hyjal"},
                {id=30154, name="Unknown Item 30154", score=0, rank=3, src="BT/Hyjal"},
            },
            [5] = {
                {id=34233, name="Unknown Item 34233", score=0, rank=1, src="SWP"},
                {id=34365, name="Unknown Item 34365", score=0, rank=2, src="SWP"},
                {id=31066, name="Unknown Item 31066", score=0, rank=3, src="BT/Hyjal"},
            },
            [6] = {
                {id=34527, name="Unknown Item 34527", score=0, rank=1, src="SWP"},
                {id=30895, name="Unknown Item 30895", score=0, rank=2, src="BT/Hyjal"},
                {id=32519, name="Unknown Item 32519", score=0, rank=3, src="BT/Hyjal"},
            },
            [7] = {
                {id=34170, name="Unknown Item 34170", score=0, rank=1, src="SWP"},
                {id=30912, name="Unknown Item 30912", score=0, rank=2, src="BT/Hyjal"},
                {id=33585, name="Unknown Item 33585", score=0, rank=3, src="ZA"},
            },
            [8] = {
                {id=34562, name="Unknown Item 34562", score=0, rank=1, src="SWP"},
                {id=32609, name="Unknown Item 32609", score=0, rank=2, src="BT/Hyjal"},
                {id=34926, name="Unknown Item 34926", score=0, rank=3, src="SWP"},
            },
            [9] = {
                {id=34435, name="Unknown Item 34435", score=0, rank=1, src="SWP"},
                {id=32584, name="Unknown Item 32584", score=0, rank=2, src="BT/Hyjal"},
                {id=30871, name="Unknown Item 30871", score=0, rank=3, src="BT/Hyjal"},
            },
            [10] = {
                {id=34342, name="Unknown Item 34342", score=0, rank=1, src="SWP"},
                {id=34367, name="Unknown Item 34367", score=0, rank=2, src="SWP"},
                {id=31060, name="Unknown Item 31060", score=0, rank=3, src="BT/Hyjal"},
            },
            [11] = {
                {id=32528, name="Blessed Band of Karabor", score=81.7, rank=1, src="BT/Hyjal"},
                {id=34363, name="Ring of Flowing Life", score=79.9, rank=2, src="SWP"},
                {id=34166, name="Band of Lucent Beams", score=85.6, rank=3, src="SWP"},
            },
            [13] = {
                {id=29376, name="Essence of the Martyr", score=75.6, rank=1, src="Pre-Raid"},
                {id=38288, name="Direbrew Hops", score=75.6, rank=2, src="BT/Hyjal"},
                {id=32496, name="Memento of Tyrande", score=106.2, rank=3, src="BT/Hyjal"},
            },
            [15] = {
                {id=32524, name="Unknown Item 32524", score=0, rank=1, src="BT"},
                {id=33592, name="Unknown Item 33592", score=0, rank=2, src="ZA"},
                {id=29989, name="Unknown Item 29989", score=0, rank=3, src="BT/Hyjal"},
            },
        },
    },
}
for k,v in pairs(_d) do IRR_BIS_DATA[k] = v end
end
